### ISSUE TITLE
Issue with resetting the image

### ISSUE THREAD

**Issue by nishan-guiddit** [TimOliver/TOCropViewController#1]
Hi Tim,

I have implemented the crop view and it works perfectly fine. Is there a way to reset the image. I'm trying to incorporate filters into the crop view your suggested. But filters are implemented fine, but the applied filters are not shown in the imageview. I'm not able to reset the imageview which the cropview has already used. 

Can you please help me out ? How image can be reset in your code or is there any way to do so ?

**Comment by TimOliver** [comment]
Hi there nishan!

Um... do you have a screenshot? I'm not exactly sure what you're trying to do here. The crop view works off one UIImage, but there are 2 UIImageView elements inside the crop view that display it.

**Comment by cherishloveyou** [comment]
i think he need  do/undo i

**Comment by TimOliver** [comment]
Sorry guys. I'm not exactly sure what you're trying to achieve here. :/

You can reset the cropping/rotation settings by tapping the white button in the very middle of the toolbar. 

The main function of this view controller is to crop/rotate images, so if you want to apply filters to them, I'd recommend looking at Instagram's model of having a separate view controller to apply filters to the already-cropped image. Given how complex this thing ended up becoming, trying to apply filters to images inside this view controller might be kind of messy. ;)

In any case, if you've already got it somewhat working, please upload a sample app and let me see. And as always, I'm happy to review and potentially merge any pull requests you send my way!

Thanks!
