### ISSUE TITLE
I need no matter how to rotate the picture, gridOverlayView is guaranteed for the horizontal 1:2 ratio, rather than the horizontal 1:2, rotation for the vertical into the 2:1, meaning that only the rotation of the picture, the clip box does not rotate

### ISSUE THREAD

**Issue by huangxuan518** [TimOliver/TOCropViewController#100]
I need no matter how to rotate the picture, gridOverlayView is guaranteed for the horizontal 1:2 ratio, rather than the horizontal 1:2, rotation for the vertical into the 2:1, meaning that only the rotation of the picture, the clip box does not rotate

**Comment by TimOliver** [comment]
I think this is a duplicate of https://github.com/TimOliver/TOCropViewController/issues/51. :)
