### ISSUE TITLE
Circular image has black background when I share image to whatsapp

### ISSUE THREAD

**Issue by KrLikeblue** [TimOliver/TOCropViewController#107]
Hello Tim,

Your Crop Controller is really damn good. I love to use it but I am getting one problem here. I have described below the problem.

I am cropping my images in circular type using your controller and it is cropping very nice.
Now I am storing those images in my app's document directory folder.
Now in my app, i am displaying all images which i have stored in document directory.
Now when I select particular image to share on whatsapp using UIPasterboard, it shared successfully, but it has black blackground behind circular image.
So Can we solve it or whatsapp will apply black color to everyimage I share ?
I am confuse here, that is why i want to ask you can you change something in code that circular image will have plain background while sharing.

Waiting for your reply.

Thanks,
Patel

**Comment by TimOliver** [comment]
Hi Patel! 

Thanks a lot! I'm glad you've found my crop controller useful! :)

Hmmm, okay! How are you saving the images to disk exactly? Are you saving them as PNG, or JPG?
The circular crop mode exports the images transparently clipped via their alpha channel. So as long as the images are saved as PNG, it SHOULD just work.

That being said, if WhatsApp does any file conversions on its own (i.e., it converts images from PNG to JPG before it uploads), then the alpha data will be lost, and the surrounding area of the image will be black.

If this is the case (i.e., PNG is a no-go in WhatsApp), then you could get your app to take the `UIImage` generated from the crop controller, and then use Core Graphics to generate a new `UIImage` where the image was overlaid on top of a solid colour of your choice to get rid of the alpha transparency.

I hope that helped! :)
