### ISSUE TITLE
crashed in iPhone 6

### ISSUE THREAD

**Issue by ArjunSa786** [TimOliver/TOCropViewController#11]
hi tim
i have implemented your code .it was superrr.i have faced this issue in iphone 6 .
Received memory warning.
Communications error: <OS_xpc_error: <error: 0x19b382a80> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x19b382e78> { length = 22, contents = "Connection interrupted" }
}>
 Connection to assetsd was interrupted or assetsd died
Terminating since there is no system app.

**Comment by TimOliver** [comment]
Hi Arjun! Glad you're enjoying the app!

Oh dear! I remember seeing that once or twice during development in the simulator, but never on the device. I did a bit of research just now and it looked like it's an issue that arrises if a memory warning occurs.

How big is the image you were trying to crop?

**Comment by ArjunSa786** [comment]
hi tim thanks for reply
images size is 1.9 MB

**Comment by TimOliver** [comment]
Hrmm, and what was its pixel resolution? When you're manipulating it in the crop controller, it gets decompressed into raw pixel data, which can take up a lot more memory than what's on disk.

I might have to look into making the controller a bit more memory efficient. Or if worse comes to worse, you can always downscale your images before sending them to the crop controller.

**Comment by ArjunSa786** [comment]
750X1334 resolution.i was pick image in image picher controller and pass to image in cropview.

**Comment by TimOliver** [comment]
Aw. That's absolutely tiny. That shouldn't be causing any memory issues. :S

I'm not sure then. Is it happening reliably each time you use the cropper?
And, just in case, are you doing any rotations to the image?

-Tim

**Comment by ArjunSa786** [comment]
No, i am not doing any rotation,it will come 4 times each of 10 using crop

**Comment by ArjunSa786** [comment]
![screen shot 2015-08-05 at 4 08 35 pm](https://cloud.githubusercontent.com/assets/10627749/9083985/76fff080-3b8c-11e5-9da8-d7c1f7a85771.png)

Connection to assetsd was interrupted or assetsd died

**Comment by ArjunSa786** [comment]
i have passed image 3264.0,2448.0 but when done button click ruturn image is 6528,4892 ..where i change??

**Comment by TimOliver** [comment]
Hrmm... there's literally none of my code in that call stack. I wonder what's going on. :S

**Comment by ArjunSa786** [comment]
hi tim
the image size 4mp and original image dime 3246 X 2448 but return image is double and bytes are double .please say how to reduse ?

**Comment by ArjunSa786** [comment]
iMAGE RESOLUTION {3208, 2404} orientation 0 scale 2.000000
when convert into byte 1203580 bytes  using
              let imageData = UIImageJPEGRepresentation(image, 0.0)
any idea reduse size but not dimension ?

**Comment by ArjunSa786** [comment]
[self.image croppedImageWithFrame:cropFrame angle:angle] when call this method dimention is double. how to change?

**Comment by iori57** [comment]
My app is crashing as well when trying to crop a very large image. The image is 3.3MB in size and with resolution 3264x2448 which is a photo taken using iPhone 6 plus. If I don't reduce the crop area but use the full size and press the Done button, half of the time it will crash the app with error 'Received memory warning.' Sometimes I can even see the white apple logo after the crash but the device is not restarting, it just go back to home screen :)

I have uploaded a sample image that i used here:
https://dl.dropboxusercontent.com/u/9307455/largeimage.zip

**Comment by ArjunSa786** [comment]
hi  lori57

please change UIImage+CropRotate.m file  
- (UIImage *)croppedImageWithFrame:(CGRect)frame angle:(NSInteger)angle
{
  UIGraphicsBeginImageContextWithOptions(frame.size, YES, 1.0f);
    {
}
}

hope it help

**Comment by TimOliver** [comment]
Oh! That actually did it! I didn't think to look there; I was looking at my actual layout code to try and figure out what was going on. I can't believe I completely missed that.

Anyway, I've updated it in the repo now (I elected to use the `image.scale` property instead of 1.0f just in case). Please give it a try and tell me if it's working for you now (And I'll reopen this issue).

Thanks again!
