### ISSUE TITLE
Feature request: add support for making Navigation Bar visible

### ISSUE THREAD

**Issue by Sander-Kornev** [TimOliver/TOCropViewController#111]
I recently have updated the version of the library in application and realized that my navigation bar  isn't shown when TOCropViewController is root in UINavigationController.

Then I found the reason in the commit https://github.com/TimOliver/TOCropViewController/commit/9193046b94307c266ebd7a072790b190d237f15a
In my application I use your library to crop several images in row with different aspect ratios and on the navigation bar I Showed current step (kind of 1/2 , 2/2).
Now as you understood it doesn't work.

What do you think of it? Of course, I can make a pull request with the feature, but I want to be sure we are on the same page regarding this feature.

So my vision is following. 
Add BOOL flag to TOCropViewController.h like leaveNavigationBarShown and if current croppingStyle isn't TOCropViewControllerToolbarPositionTop just don't do  

```
[self.navigationController setNavigationBarHidden:YES animated:animated];
```

and 

```
[self.navigationController setNavigationBarHidden:self.navigationBarHidden animated:animated];
```

Do I need to change anything else in order not to broke any other functionality?
Or may be it will be better to make the feature yourself?
Thanks.

**Comment by TimOliver** [comment]
Hi @Sander-Kornev! Thanks for the issue! Oh dear, sorry I caused a regression in your app!

Woah. Yeah? What did that look like exactly? Did you take out the 'Cancel' and 'Done' buttons in the toolbar too? Can you post a screenshot of what it used to look like?

Yep! I'm happy for you to file a PR that adds a property called `navigationBarHidden` to explicitly unhide the navigation bar in this controller.

For quality purposes, two things I'd want:

1. When the navigation bar is visible, 'Cancel' is removed, and (Assuming this fits your design) 'Done' is move to the top right side of the navigation bar.
2. Make sure the navigation bar matches the theme of the crop controller (i.e., it can't be the default white. :) )

Thank you so much for taking the time to ask me before starting a PR. I really appreciate that. :D

**Comment by Sander-Kornev** [comment]
Hi @TimOliver !
Thanks for the answer.
Here is how my two screens look like.
![c0e5e50ebaf8413683e7dbc8d79d9538](https://cloud.githubusercontent.com/assets/3295273/16547740/ec2959c4-417f-11e6-9cdb-1b69043f90e8.png)
Probably you imagined it in another way.
I'll try to make the PR soon.

**Comment by TimOliver** [comment]
Cool. Let me know when that PR is ready. :D
