### ISSUE TITLE
Is this possible to use the same library for cropping video

### ISSUE THREAD

**Issue by masroorelahi** [TimOliver/TOCropViewController#113]
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> ---
>
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
> ---
>
> Please note that since library is done as a side-project outside of work hours, 
> a timely response cannot be guaranteed. ;)
>
> Please remove this line and everything above it before submitting. 

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expected to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

## Hardware / Software

On which version of iOS, and what sort of device did you experience this bug?

**Comment by TimOliver** [comment]
Nope. This library is for images only. Sorry!
