### ISSUE TITLE
Snapshotting view without reference to the library

### ISSUE THREAD

**Issue by judepereira** [TimOliver/TOCropViewController#116]
Hey @TimOliver, great work on this library!

I have just one particular issue - I installed this library using Cocoapods, and didn't reference it anywhere in my project. However, whenever my app went into the background, I got a warning in the console saying that I'm trying to snapshot a view before it's drawn. 

The moment I removed this pod, that warning went away.

Any clue why this is happening?

**Comment by TimOliver** [comment]
Hi @judepereira! Thanks a lot! I'm glad you're enjoying it!

Nope. I have no clue what could be causing that. The cropper only performs snapshotting when you're performing a rotation of the image, but it sounds like you're getting the error too early for it be an issue with that.

I did a quick Google search for the issue and it looks like it might actually be a bug in Apple's photo picker code: http://stackoverflow.com/questions/25884801/ios-8-snapshotting-a-view-that-has-not-been-rendered-results-in-an-empty-snapsho

Can you confirm that? Are you getting the issue when interacting with a photo picker?

**Comment by judepereira** [comment]
I don't think that's affecting me. I haven't begun integrating the photo picker yet. That's the weird part - nothing changes in my code, but just introducing the pod triggers this warning.

**Comment by TimOliver** [comment]
Hmm, I'm really not sure then. I'm using it as a CocoaPods dependency in [my own shipping app](http://icomics.co) and I'm not getting that issue.

I think we might need to leave this one until we can actually establish this is an issue being caused by this particular library, and if so, what part of the code is actually doing it. :)

**Comment by judepereira** [comment]
Hmm alright. Thank you :)
