### ISSUE TITLE
Need a tag that includes the Carthage Info.plist fix?

### ISSUE THREAD

**Issue by csimmons0** [TimOliver/TOCropViewController#119]
## Goals

Install the library using Carthage.

## Expected Results

Run "carthage update --platform ios" and get no errors.

## Actual Results

Carthage reports the following error:
Failed to read file or folder at /Users/christophersimmons/Library/Developer/Xcode/DerivedData/TOCropViewControllerExample-atzravwhbomqucdwjbprsuykprqz/Build/Products/Release-iphoneos/TOCropViewController.framework

## Steps to Reproduce

Attempt to install with carthage version 0.16.2 and just "github "https://github.com/TimOliver/TOCropViewController"" (minus the outer quotes) in your cartfile.
Workaround: Place "github "https://github.com/TimOliver/TOCropViewController" "afc2eb82b478b65e71369383d3c4c5245de55d7f"" in your cartfile in order to include the fix to the Info.plist issue. If you don't ask for a specific revision, Carthage gets the latest tag, and the latest tag, 2.0.7, doesn't include the fix.

## Hardware / Software

iOS version is N/A, but the carthage version is 0.16.2.

**Comment by TimOliver** [comment]
I just pushed a new tag, so HOPEFULLY this is now resolved. Please let me know if it isn't. :)
