### ISSUE TITLE
Resolution changes in unexpected manner

### ISSUE THREAD

**Issue by jbrozena22** [TimOliver/TOCropViewController#121]
Hi, I have a use case that is producing unexpected results. I have an image that has a width of 3024 when it starts. I then open the cropper, and remove the bottom portion of the image while maintaining the same width.

However, if I print the image width after the crop occurs it says the new width is 1512 despite my not having touched the width. In short, it appears my image was compressed when it came out of the crop.

Is that as designed? Is there any way to tell the cropper to maintain the original resolution and not to compress?

Thanks so much and thank you for all of the work on this awesome tool!

**Comment by jbrozena22** [comment]
On further investigation, if I upload the cropped image to S3 I see that the dimensions are correct and what you would expect, so the underlying image dimensions aren't getting changed by this tool.

So why then this code:
   ```
 func cropViewController(cropViewController: TOCropViewController!, didCropToImage croppedImage: UIImage!, withRect cropRect: CGRect, angle: Int) {
        image = croppedImage;
        print("width", image?.size.width)
    }
```

results in printing a width that is exactly half what I would expect?

**Comment by TimOliver** [comment]
Hi @jbrozena22!

This was done intentionally, in this specific line of code involving cropping the `UIImage`:

```
return [UIImage imageWithCGImage:croppedImage.CGImage scale:[UIScreen mainScreen].scale orientation:UIImageOrientationUp];
```

The reason for this is to ensure the resulting image is properly configured for display on the Retina Display points/pixels system of the iOS device. Without setting the scale value to 2 on Retina devices (or 3 on iPhone 6/6s/7 Plus), trying to display any of those images without manually accounting for that results in the image being rendered at 1x, which looks blown up.

To work out the actual physical pixel size of an image represented by `UIImage`, it's best to do it like this:

```
CGSize imageSize = CGSizeMake(image.size.width * image.scale, image.size.height * image.scale);
```

I hope that answered your question! :)
