### ISSUE TITLE
Incorrect crop aspect ratio

### ISSUE THREAD

**Issue by Mazorati** [TimOliver/TOCropViewController#123]
Hello!

After cropping image with aspect ratio 9:5 (Business card) TOCropViewController return image with cropRect = (1162.0, 237.0, 3088.0, 1724.0).

My init code:

```
func imagePickerController(picker: UIImagePickerController!, didFinishPickingImage image: UIImage!, editingInfo: NSDictionary!){
        
        print("picked")
        
        let controller = TOCropViewController(image: image)
        controller.delegate = self
        controller.rotateButtonsHidden = true
        controller.aspectRatioPreset = .PresetCustom
        controller.customAspectRatio = CGSize(width: CARD_WIDTH_MULT, height: CARD_HEIGHT_MULT)
        controller.aspectRatioLockEnabled = true
        controller.resetAspectRatioEnabled = false
        
        picker.pushViewController(controller, animated: true)
        
}

func cropViewController(cropViewController: TOCropViewController!, didCropToImage image: UIImage!, withRect cropRect: CGRect, angle: Int) {
        print("crop finished: \(angle)")
        print(cropRect)
        
        pickDelegate?.didFinishPickingImage(image)
        cropViewController.dismissViewControllerAnimated(true, completion: nil)
}
```

Due to an incorrect aspect ratio the picture is not in the right frame (see image 1). Visible strip edges (white lines with blank space in ImageView).
Please help to solve this problem!

Thanks.

![sim2](https://cloud.githubusercontent.com/assets/3396425/18809790/3ffb068e-828e-11e6-8707-03e21df7e890.png)
![sim1](https://cloud.githubusercontent.com/assets/3396425/18809791/3ffc9a30-828e-11e6-931c-16effb0a72db.png)

**Comment by Mazorati** [comment]
The problem was in arguments CGSize(width: CARD_WIDTH_MULT, height: CARD_HEIGHT_MULT).
let CARD_WIDTH_MULT:CGFloat = 9
let CARD_HEIGHT_MULT:CGFloat = 5
When i change to CGSize(width: 9, height: 5) everything works great! thanks.

**Comment by TimOliver** [comment]
Hey @Mazorati! Thanks for reporting this!

Um. Wow! I'm not sure why that could be happening then. This sounds like something weird happening with the types in Swift. Since they're only being offset by a single point, it seems like an integer/floating point mismatch to me. :/

Maybe one thing to possibly try:

```
let CARD_WIDTH_MULT:CGFloat = 9.0
let CARD_HEIGHT_MULT:CGFloat = 5.0
```

Explicitly forcing the values to decimal values might help. Let me know if that works for you. :)

**Comment by Mazorati** [comment]
Hello! Thanks for fast responding!
I just change:
`controller.customAspectRatio = CGSize(width: 9.0, height: 5.0)`
CropRect result: (0.0, 170.0, 2487.0, 1388.0) - the same issue :(

or
`controller.customAspectRatio = CGSize(width: Double(9.0), height: Double(5.0))`
(342.0, 589.0, 1459.0, 815.0) - in this case, for example, should be (342.0, 589.0, **1467.0**, 815.0)

The only way i think to solve this is to crop again after TOCropController did crop :)

**Comment by TimOliver** [comment]
Hmm, can you send that image? I can only really test it easily in Objective-C, but I'd like to test it out in the demo app to see if I can replicate it. :)

**Comment by Mazorati** [comment]
@TimOliver This problem occurs with any image. Just create ImageView with фызусе кфешщт 9:5 and put there an image from didCropToImage action and see that it **does not** bound this imageView rect. So the aspect ratio is incorrect - not 9:5.
Basically, this problem occurs when you change the cropping area. If you do not change - it all works well.

**Comment by TimOliver** [comment]
I had a play with the custom aspect ratio feature and noticed there were some floating point errors being introduced (A value was -0.5 when it was expected to be 0.0). I've pushed a new version fixing those issues. Please give that one a try and see if it fixed the issues for you. :)

**Comment by Mazorati** [comment]
@TimOliver perfect! Thanks!
