### ISSUE TITLE
I need Rect Crop from Circular style

### ISSUE THREAD

**Issue by Mercidez** [TimOliver/TOCropViewController#124]
I use circular style when I cropping image but If I want to when didfinish is rect crop , is it possible?

**Comment by TimOliver** [comment]
Um, what do you need exactly? The `CGRect` value of the image region when you cropped with the circular mode enabled?

**Comment by TimOliver** [comment]
Alright. I just double-checked the code. Yes, if you implement the `- (void)cropViewController:(TOCropViewController *)cropViewController didCropImageToRect:(CGRect)cropRect angle:(NSInteger)angle;` method, even when circular cropping is enabled, you'll get the appropriate `CGRect` of the area that was cropped. :)

I hope that helped!
