### ISSUE TITLE
Custom rotation

### ISSUE THREAD

**Issue by Mazorati** [TimOliver/TOCropViewController#125]
Hello!
Thank you for your library! 
It would be great if it were possible to rotate the picture under cropping area at any angle.
Tupping with two fingers, and rotation for example at 14 degrees. 
Thank you!

**Comment by TimOliver** [comment]
Thanks a lot @Mazorati! Glad you're enjoying the library.

You're not the first to ask about this. ;) The original issue asking about this was #3, but like I said in there, it's out of the scope of this library. It would require a huge amount of research, rewriting and testing.

Sorry!

**Comment by Mazorati** [comment]
Thanks @TimOliver !
How about in order to make the ability to crop a picture with external region? Or can you help me to do this? (Some tips)
Some thing like this:
![xxof6r016_m](https://cloud.githubusercontent.com/assets/3396425/19019882/3de5e528-889f-11e6-86df-12bc9c7baedc.jpg)
