### ISSUE TITLE
Crop problem with swipe the vertex of the grid.

### ISSUE THREAD

**Issue by MaStarJi** [TimOliver/TOCropViewController#127]
=================================================

I'm developing wt TOCropViewController 2.0.7 and xcode 8.0
It's okay to crop when swipe the edge lines of grid.
However, swipe the vertex of grid, it doesn't move to center of an image and zoom in incredibly.

You can check this out on this video above.
https://www.youtube.com/watch?v=3tsEwI8ErmI

I didn't edit the orignal library any code.

How can I fix this problem?

**Comment by TimOliver** [comment]
Hmmm... I've never seen it behave like that before. I've been playing with it heavily on my iPhone 7 running iOS 10, and while I've seen other glitches, the panning  code has still been fine.

I just pushed version 2.0.8 to fix those iOS 10 bugs, so it might be worth updating and trying that version. 

Beyond that, I'll need some more information. What is the view controller structure you've got when you push this controller on top of it?

**Comment by MaStarJi** [comment]
Dear. Tim.

I solved the problem.
It’s been crushed with other library called CCBottomRefreshControl. I’v just deleted that library then everything’s OK.

Thank you for your consider anyway :)

**Comment by TimOliver** [comment]
Haha! Oh jeez. I wouldn't have picked that. 

Oh well. Thanks for letting me know!
