### ISSUE TITLE
Crop Image with a Specific Frame Size and Zoomed In

### ISSUE THREAD

**Issue by bhushans** [TimOliver/TOCropViewController#130]
Hello,

I am trying to use the ToCropViewController to crop an image with a specific frame size of 131.5pt * 75 pt, and I need the image to be of the zoomed into the size of 144 pt * 108 pt, with the Crop Frame starting from CGPoint(x:5, y: 10)

I tried setting the aspect Ratio, but it didnt have any effect.
Does anyone have any idea on how can I create this effect.

Bhushan

**Comment by TimOliver** [comment]
Um. What's your particular use-case here? Why do you want an initial zoom size?

It's not possible to manually constraint the controller to an explicit point/pixel size. There's an issue tracking a minimum size ( #46 ) and one tracking a completely locked size ( #68 ), but I don't have time to add/test any new features at the moment.

**Comment by bhushans** [comment]
The particular use case is to have an image of a particular size been cropped when we display it to the user, so the user can just move the crop frame on the image and focus on the image part they want to crop.  Not able to pin point to an exact pixel at a starting point is ok, but having a fixed crop frame is essential for my use-case.

**Comment by TimOliver** [comment]
Hmmm, okay. 

Well you can use the `- [TOCropViewController imageCropFrame]` property to set an initial crop value for the image. You could then combine it with a clamped aspect ratio to ensure the user can only generate an image of that shape, and then resize it to the appropriate size yourself afterwards. :)

**Comment by bhushans** [comment]
Hi Tim,

How would I set the clamped aspect ratio and also how I ensure that the
user is not able to change the crop frame size.

Bhushan Shah

**Comment by TimOliver** [comment]
Hi! You can set `aspectRatioLockEnabled = YES` and `resetAspectRatioEnabled = NO` to make it that the user can't ever resize or reset the crop box's aspect ratio. You can then use `customAspectRatio` to manually set the ratio you need. :)

**Comment by bhushans** [comment]
Thanks a lot.

Bhushan Shah

Bhushan Shah

**Comment by TimOliver** [comment]
No worries!
