### ISSUE TITLE
Toolbar customization

### ISSUE THREAD

**Issue by akovalov** [TimOliver/TOCropViewController#131]
Is it possible to customize appearance of toolbar? For example make cancel button as icon not text, change frame of toolbar, order of buttons etc.

**Comment by TimOliver** [comment]
Not at the moment sorry. That's all hard-coded. 

It'd be pretty trivial to expose those properties and then control them from your own code though. :)

**Comment by akovalov** [comment]
I like to use CocoaPods and didn't want to copy source code into project and edit them. 
So I've come up with quick simple customization.
If anybody needs it https://gist.github.com/akovalov/6784e526ee273decefa7a21312066a1a.
Thanks for really nice component.

**Comment by TimOliver** [comment]
Cool! Good to hear you came up with a usable solution then.

If you ever want to make this an official part of the project, feel free to file a PR. :)
