### ISSUE TITLE
2 different shown of crop view?, aspect ratio crop?

### ISSUE THREAD

**Issue by adinertia** [TimOliver/TOCropViewController#133]
Hello, 

Thanks for great library! 
I have few question.

i'm using in swift the code bellow:

```
let cropViewController = TOCropViewController(image: image!)
cropViewController.delegate = self
cropViewController.aspectRatioLockEnabled = true
cropViewController.aspectRatioPickerButtonHidden = true
cropViewController.rotateButtonsHidden = true
cropViewController.aspectRatioPreset = .presetSquare
cropViewController.resetAspectRatioEnabled = false
cropViewController.cropView.cropBoxResizeEnabled = false
present(cropViewController, animated: true, completion: nil)
```
1. I don't know is this a bug or i'm somethnig missing but when crop present, sometimes it's shown like 2 differents views. Here is ![picture1](https://cloud.githubusercontent.com/assets/22740154/19553138/373ca80c-96b3-11e6-82a5-190b19dfb96c.jpg) and ![picture2](https://cloud.githubusercontent.com/assets/22740154/19553143/3dd5bf8c-96b3-11e6-8b97-e6e9ca5763ed.jpg) but allways must be as picture 2. I've also noticed that when crop view is shown the reset button is already active to revert back is this ok or ?
2. How crop aspect ratio works ? I've noticed on iphone photos in .presetSquare mode it will crop automaticly to 1000 x 1000 but the problem is with picutre like 720 x 540, the croped aspect ratio will automaticlly go to 270 x 270 why not have as 540x540 if is possible ?

Thanks

**Comment by TimOliver** [comment]
Oh dear! Can you please post that picture here so I can try it myself?

Also, I did a bunch of layout fixes with the aspect ratio very recently, please make sure you're on the latest version of this library. :)

**Comment by adinertia** [comment]
Thanks for reply. 
I update library 4 days ago, i can update it again now if you mybe made some changes in this 4 days. 

Here is the picture of 720 x 540 that couse problem with ratio to 270 x 270 (not 540x540 if is possible) and also couses frame view like posted picture 1 above. And also original picture of picture1.
Thanks for helping out!

720x540
![720-540](https://cloud.githubusercontent.com/assets/22740154/19618459/24f5a628-984b-11e6-806a-e2bfe63fdeb6.jpg)
and original
![img_1579](https://cloud.githubusercontent.com/assets/22740154/19618461/2d5a15c4-984b-11e6-88f0-e51c7673aadb.jpg)

**Comment by TimOliver** [comment]
Thanks for that! Aha! It was a legit bug. One of the optimisations I'd made to when the crop controller presented on screen had disabled the initial call to re-layout images that had aspect ratios set in advance.

I've fixed it and pushed a new CocoaPods release. Please download it and see if that's working for you now.

As for the image size, when you crop an image, it sets the appropriate Retina display scale on the image so it'll display correctly on your device's screen (270*2 = 540), so it's `image.size` property is in points, not pixels. The raw pixel size is how you expect it. :)

**Comment by TimOliver** [comment]
Gonna take a leap of faith here and assume it was fixed. :) Please re-open if otherwise. XD
