### ISSUE TITLE
CustomAspectRatio does not work.

### ISSUE THREAD

**Issue by yigitserin** [TimOliver/TOCropViewController#139]
Hey there pretty good framework overall. One issue tho:

In my project, I need a 3x1 ratio image picker. Since it is not included in presets, I had to use customAspectRatio property of controller. However, it does not work for me. 

For testing purposes, I used 16x9. Here is results:

```
        cropVC.aspectRatioPreset = .Preset16x9  //Works as intented
        cropVC.customAspectRatio = CGSizeMake(16.0, 9.0) //Does not work
```

**Comment by TimOliver** [comment]
Hi! I just tested it and it was fine for me. When you say 'Does not work for you', what is it actually doing?

**Comment by yigitserin** [comment]
When I go into crop view controller, the crop rectangle's ratio is equal to image's ratio. I will provide screenshots later.

**Comment by yigitserin** [comment]
[First I am going the provide the whole code.](https://gist.github.com/yigitserin/4cf5cbbde9707e94349de336a4130fe6)
[And a link to example image I am working with](http://i.imgur.com/DbFGmae.jpg)

So here is what it looks like. When I set it to `cropVC.aspectRatioPreset = .Preset16x9`, it opens like this:

![image](https://cloud.githubusercontent.com/assets/8073308/20346067/dd5bb700-ac02-11e6-8e52-064f8f6bec8c.png)

However, when i set to: `cropVC.customAspectRatio = CGSizeMake(16.0, 9.0)` it opens like this:

![image](https://cloud.githubusercontent.com/assets/8073308/20346126/21544e0e-ac03-11e6-8460-85d093c24302.png)

Hope we can find a solution for this.

**Comment by TimOliver** [comment]
Hmm, I quickly tried it inserting your code into the sample app, and it worked fine for me.

```
    TOCropViewController *cropController = [[TOCropViewController alloc] initWithCroppingStyle:self.croppingStyle image:image];
    cropController.delegate = self;
    cropController.customAspectRatio = CGSizeMake(16.0, 9.0);
    
    cropController.aspectRatioLockEnabled = YES;
    cropController.aspectRatioPickerButtonHidden = YES;
    cropController.resetAspectRatioEnabled = YES;
    cropController.rotateButtonsHidden = YES;
    cropController.rotateClockwiseButtonHidden = YES;

```

![simulator screen shot 17 nov 2016 7 21 21 am](https://cloud.githubusercontent.com/assets/429119/20395057/7a4ab712-ac96-11e6-9c8a-dce77d44f1e3.png)

I did some fixes for the aspect ratio about a month ago. Have you downloaded the latest version?

**Comment by yigitserin** [comment]
Ahh, I have been using 2.0.7 version. After update it works fine. Thanks!

**Comment by TimOliver** [comment]
Haha glad I could help! Don't forget to always check you're running the latest version! ;D

Enjoy!
