### ISSUE TITLE
Aspect Ratio Constraint 

### ISSUE THREAD

**Issue by HHK1** [TimOliver/TOCropViewController#14]
Setting the aspect ratio does not properly work. In my case I was trying to obtain an exact 2:3 ratio

I'm logging the `cropBoxFrame` just before cropping the image, but the ratio of it's size is no longer 2:3, resulting in a cropped image that is not in the correct size. 

I'll probably investigate further, for now I'm calling several times `setAspectLockEnabledWithAspectRatio`. Its extremely ugly, but eventually leads to a correct `cropBoxFrame`.

**Comment by TimOliver** [comment]
Thanks for the post!

Erm, okay. That's a bit weird. Can you please post the code you're using to present the view controller so I can see that for myself?

Thanks a lot! I'm really busy right now, so depending on how complex this issue is, I don't think I can help out much at the moment.
