### ISSUE TITLE
Bundler error After pod install

### ISSUE THREAD

**Issue by taojigu** [TimOliver/TOCropViewController#140]
My Code Version is 8.1
After I pod 'TOCropViewController','~>2.0.11'
when I build, I get error:

/Users/gu/Library/Developer/Xcode/DerivedData/DDReaderPlus-frpaqczgjayuxtbtazrrcvsiplmx/Build/Products/Debug-iphonesimulator/TOCropViewControllerBundle.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1

**Comment by TimOliver** [comment]
Hi! Have you done a `pod repo update` recently? :)

**Comment by taojigu** [comment]
0.38.2

**Comment by TimOliver** [comment]
That's a super old version of CocoaPods! Try [updating it](https://guides.cocoapods.org/using/getting-started.html), and then running `pod update`  instead of `pod install`. :)

Either way, this isn't an error that's fixable within this library, so I'm closing this issue. Good luck! :)

**Comment by taojigu** [comment]
Thank you very much

**Comment by TimOliver** [comment]
No worries! If you still get the issue, try looking around the [CocoaPods repo](https://github.com/CocoaPods/CocoaPods) to see if there's anything else you might need to do. :)
