### ISSUE TITLE
didCropTo image not fired

### ISSUE THREAD

**Issue by davidseek** [TimOliver/TOCropViewController#142]
Currently trying to implement it into a Swift 3 project.

`didFinishCancelled cancelled` is fired and handled when cancel button pressed.
But when I hit the Done button `didCropImageTo cropRect` is fired.
Do I need to set the `CGRect` somehow manually to the `UIImage`?

I have set the delegate correctly... Otherwise the other 2 functions wouldn't be fired...
But no matter what I try... `didCropTo image` function is not getting triggered...

All I'm doing is trying to print the delegate trigger:

```
func cropViewController(_ cropViewController: TOCropViewController, didCropImageTo cropRect: CGRect, angle: Int) {
        print("didCropImageTo") //triggered on Done button
    }
```
    
    
    
```
func cropViewController(_ cropViewController: TOCropViewController, didCropTo image: UIImage, with cropRect: CGRect, angle: Int) {
        print("didCropTo") //not triggered at all
    }
```

What am I missing? Help is very appreciated.

**Comment by davidseek** [comment]
All I'm doing is trying to print the delegate trigger:

`    func cropViewController(_ cropViewController: TOCropViewController, didCropImageTo cropRect: CGRect, angle: Int) {
        print("didCropImageTo")
    }
    
    
    
    func cropViewController(_ cropViewController: TOCropViewController, didCropTo image: UIImage, with cropRect: CGRect, angle: Int) {
        print("didCropTo")
    }`

**Comment by TimOliver** [comment]
Hi @davidseek!

The delegate logic is called here if you want to check it out: https://github.com/TimOliver/TOCropViewController/blob/master/TOCropViewController/TOCropViewController.m#L775

Only one delegate method is called. If you set more than one, only the first one in this conditional list is called. Those two delegate methods are basically the same, except one will provide you with a cropped version of the image, and the other will only provide you with a `CGRect` of where the user cropped the image.

I hope that helped!

**Comment by davidseek** [comment]
Yes. It did. Thank you... So all I needed to do was to delete the other function... damnit. That would have saved some time xD

**Comment by TimOliver** [comment]
No worries! Sorry about that! I probably should indicate in the documentation that only one method is called, or maybe even review that policy on only executing one of the delegate callbacks. I wanted to avoid calling the one that provides the `UIImage` since it's a very heavy operation to generate that.

On that same note, I probably should look at refactoring those delegate methods so they look a bit nicer in Swift 3 too! XD

Glad I could help!

**Comment by davidseek** [comment]
Okay so - just to know if I get your right - the better practise would be to take the CGRect and put it onto an Image myself instead of taking the Image from the second func?

**Comment by TimOliver** [comment]
So the `CGRect` you get back in that delegate method is the position and size of the crop region that the user selected, in the coordinate space of the original image. If you want, you can take that `CGRect` and then crop the original image you provided to the crop view controller on your own.

The second delegate method is more of a convenience method. It does the cropping internally and then provides you with the cropped image, as well as the `CGRect` it used to produce that cropped image.

So, if you absolutely need a `UIImage` of the cropped region, use the delegate method that provides the image. If you just want the `CGRect` so you can save it and do your own cropping later, use the other one. :)

**Comment by davidseek** [comment]
Thanks for the clarafication
