### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by brandonscript** [TimOliver/TOCropViewController#144]
Hey Tim — I'm looking at including your lib in a project of mine that I'm working on. It's written in Swift, and for me, there is some value in having this run natively in Swift. If you're interested, I could re-contribute the converted project back here in a branch? If not, I'll just fork it and leave it alone.

**Comment by TimOliver** [comment]
G'day Brandon! 

Hahah oh blimey, a Swift version? What would that entail exactly? Would you be considering actually rewriting the whole lot in Swift? Or just making a Swift wrapper so the majority of the Objective-C stuff is obfuscated from your app's level? (One of my colleagues has done something like that before: https://github.com/Roobiq/RBQFetchedResultsController)

If you're considering just encapsulating the lot in a Swift wrapper, that would be really nice to have here on the main branch. But if you're thinking of building a completely separate one, it might be best to keep the two separate since I don't think I could maintain two separate copies (But I'd be happy to add a link in the read me). :)

**Comment by brandonscript** [comment]
Well, to be honest, what I end up doing depends completely on what my requirements are. I'll have to do some technical validation and investigation before I make that call. Whatever I decide, I'll let you know here! (Fair warning, it'll be a while before I get this far 😉)

**Comment by drougojrom** [comment]
Hi!

I've started to rewrite the whole project to swift recently. Already done with Model block and started with views. For example, part of TOCropOverlayView is also done. But if anybody wants to join and help a little bit, it would be great :)

The project is available here[https://github.com/drougojrom/RUCropController]

**Comment by TimOliver** [comment]
Hi @drougojrom!

Blimey! That's an impressive undertaking! Are you sure about that though? If you're converting this thing to Swift line-by-line, I'm wondering if it might just be easier to just use this codebase as more of an architectural guide, but re-architect it in a much more Swifty way. 

Still, I'm very curious to see what that project will turn out to be. Good luck!

**Comment by brandonscript** [comment]
For what it’s worth, I’ll eventually get around to contributing to this! I’m just so slow and busy these days, I haven’t found the motivation. ¯\_(ツ)_/¯

Brandon

**Comment by TimOliver** [comment]
Alrighty. I finally got around to doing what I said I was going to do above. :D

I've added a new component to this repo, named `CropViewController`. Following how Realm wraps its Objective-C binding in a Swift wrapper to produce a fully Swifty interface, I've done a similar thing here.

`CropViewController` is a Swift `UIViewController` subclass that wraps and internally controls a `TOCropViewController` instance as a child view controller. It doesn't expose any of the Objective-C parts directly; everything is abstracted through `CropViewController` and every relevant `UIViewController` message is passed through to the internal crop view controller. This way, the interface is 100% Swift (or as close as I could get it with some Objective-C delegate stuff), and should be a bit nicer to work with in fully Swift codebases.

I've also rewritten the sample app in Swift to demonstrate how it works. While the demo app works as well as the Objective-C one (as far as I tried), I'm sure there are other edge cases out there, so I'm going to tentatively say it's still in beta for now.

Anyway, please let me know what you think of that, and if there's any way to make it even more Swifty. :)

**Comment by ixialuo** [comment]
Hey Tim —
I used CropViewController version 2.3.4, when i written CropViewController(croppingStyle: CropViewCroppingStyle.default, image: image),it warning 'CropViewController' initializer is inaccessible due to 'internal' protection level

**Comment by TimOliver** [comment]
I don't know if there's any reason to keeping this issue open, so I'm going to close it for now. Feel free to re-open if there are any new developments! :)
