### ISSUE TITLE
question: zoom lead undefined scroll

### ISSUE THREAD

**Issue by mxyolande** [TimOliver/TOCropViewController#146]
When I enlarge the picture to the maximum, reducing the size of the crop box, the picture will do an unusual scroll to some where.

**Comment by TimOliver** [comment]
Hi @mxyolande! Thanks for the issue!

Ah. Yep! I see it. The crop controller isn't realizing it's at the mazimum zoom level. It's trying to align the picture to the assumed new zoom center, but the zoom box isn't changing. The Photos app accounts for this by simply re-enlarging the box.

I'll definitely need to fix this. I'm not sure when I'll get time to though, sorry.

**Comment by TimOliver** [comment]
Alrighty. I just pushed a new version that will disregard changing the scroll view offset if the zoom scale of the image is already maxed out. It could probably use a bit more refining, but at the very least it behaves a lot nicer than before.
