### ISSUE TITLE
Request to release a ".framework" file

### ISSUE THREAD

**Issue by krish-dev** [TimOliver/TOCropViewController#147]
This is a very good lib. I want to create Cordova plugin by using this lib. is it possible release a ".framework" file for this lib, So I can consume this lib easily in Cordova plugin. actually, I have manually added the lib into Cordova plugin but its throwing the following error.

![screen shot 2017-01-16 at 3 37 47 pm](https://cloud.githubusercontent.com/assets/7298557/21978731/dbd406d8-dc01-11e6-9262-589971773ed4.png)

**Comment by TimOliver** [comment]
Yep! The library can be built to a framework! It was necessary for Carthage support.

You should be able to build a copy of the framework and then import it into your project.

![screen shot 2017-01-24 at 12 38 22 am](https://cloud.githubusercontent.com/assets/429119/22212967/853e9bea-e1cd-11e6-8eae-1ca499c799e8.png)

**Comment by krish-dev** [comment]
thanks @TimOliver . I'm closing this issue.
