### ISSUE TITLE
after adding TOCropViewController file manually still, getting file not found error

### ISSUE THREAD

**Issue by VijaylaxmiH** [TimOliver/TOCropViewController#148]
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here.
>
> ---
> 
> For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods ('gem install cocoapods'), and the latest version of this 
> library ('pod repo update').
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ---
>
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
> ---
>
> Please note that since library is done as a side-project outside of work hours, 
> a timely response cannot be guaranteed. ;)
>
> Please remove this line and everything above it before submitting. 

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by TimOliver** [comment]
Please do not ignore my message template. I need a lot more information than that before I can help.

Please fill out exactly what's happening in this issue. :)

**Comment by VijaylaxmiH** [comment]
I have added the TOCropViewController, as instructed in the GitHub, after
adding and installing the Pod, its giving me error like use of undeclared
type TOCropViewControllerDelegate, even though i have imported the same
Bridging-Header.h file

Thank You,
Vijaylaxmi.

**Comment by TimOliver** [comment]
Um, are you installing it manually, or as a CocoaPods dependency then?

Sorry, I'm not sure if there's anything I can do to help!

**Comment by VijaylaxmiH** [comment]
I have installed it using CocoaPods, not manually,
Ok, thank you

Thank You,
Vijaylaxmi.
