### ISSUE TITLE
cropViewController delegate not being called.

### ISSUE THREAD

**Issue by tkato0909** [TimOliver/TOCropViewController#149]
## Hardware / Software

Which version of the library were you using?  2.0.11
Which version of iOS are you running? 10.1
What model of iOS device were you testing on? iPhone SE
If using CocoaPods, which version of CocoaPods are you on? 1.1.1

## Goals

What is the outcome result you want to achieve with this library? Crop an image then send it to my own API to process it and return a result to the user.

## Expected Results

What did you expect to happen? `- (void)cropViewController:(TOCropViewController *)cropViewController didCropToImage:(UIImage *)image withRect:(CGRect)cropRect angle:(NSInteger)angle
`  (In swift:     `func cropViewController(_ cropViewController: TOCropViewController, didCropTo image: UIImage, with cropRect: CGRect, angle: Int) {
`)to be called after I press 'Done'.

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)
The function was not called even with the delegate imported.

## Steps to Reproduce

What are the steps needed to reproduce this issue?
I am trying to recreate the Basic Implementation listed on the About.md page of this framework. I am using Swift but that should not be the problem as all the other functionality of the framework is working.

Thank you for all the work you have done for this framework, I really appreciate it, hopefully this issue can be resolved soon!

**Comment by alexsanderkhitev** [comment]
Hello @tkato0909 !

I faced the same problem. I called only one delegate method ` cropViewController(_ cropViewController: TOCropViewController, didFinishCancelled cancelled: Bool)`. I use this framework in my swift framework.

**Comment by TimOliver** [comment]
Thanks for the issue @tkato0909! I'm glad you like the library!

Hmm, I tried to be a bit clever with the way the delegate system worked. It was assuming you'd only ever implement one delegate method, and it would disregard the others. This has definitely caused some confusion.

I just pushed a new version that changes it so all delegates will be called if they are implemented. Please update your version and let me know if that fixes it.

Thanks!

**Comment by TimOliver** [comment]
I'm going to assume this was resolved. Feel free to re-open if you need anything else. :) Thanks!

**Comment by tkato0909** [comment]
Hi, thank you for this. This resolved my issue, keep up the great work! Thank you 👍

**Comment by TimOliver** [comment]
Awesome! Good to hear! Thanks a lot! :)
