### ISSUE TITLE
Images rendered with poor quality.

### ISSUE THREAD

**Issue by alexsanderkhitev** [TimOliver/TOCropViewController#151]
Hello @TimOliver ! I am using your framework in my swift framework. I encountered such a problem that when I show your TOCropViewController of the cell (a standard animation), the image (regardless of the position of the device) is initially displayed with a very poor quality, and if you rotate the device, the image is already displayed in good quality. Please tell me how to fix it? Below I have attached an image of this behavior.

My code

```
fileprivate func presentCropControllerFromCell(_ indexPath: IndexPath) {
        let asset = fetchResult[indexPath.row - 1]
        let targetSize = CGSize(width: asset.pixelWidth, height: asset.pixelHeight)
        
        debugPrint("targetSize", targetSize)
        
        imageManager.requestImage(for: asset, targetSize: targetSize, contentMode: .default, options: nil) { [weak self] (image, data) in
            guard image != nil else { return }
            
            let cropViewController = TOCropViewController(croppingStyle: .circular, image: image!)
            cropViewController.delegate = self
            
            self?.currentImageSource = .cell
            
            DispatchQueue.main.async {
                self?.present(cropViewController, animated: true, completion: nil)
            }
        }
    }
```

![img_0717](https://cloud.githubusercontent.com/assets/12511909/23367699/aac718c0-fd24-11e6-8ffb-0de56abefde7.PNG)

After rotation 
![img_0718](https://cloud.githubusercontent.com/assets/12511909/23367701/acd3055c-fd24-11e6-9e37-c820c0662993.PNG)

Update
I would like to just add, I tried to show a different TOCropViewController (showVC), the image rendered well, but when I press the Cancel, the controller is not hidden, but as if they were two presents simultaneously. 

Update 1
Yes, I have looked after this code comes two calls in `TOCropViewController` viewDidLoad and memory to be two objects.
![imagepickercontroller xcodeproj 2017-02-27 20-24-56](https://cloud.githubusercontent.com/assets/12511909/23369549/248c33ec-fd2b-11e6-8d3f-d39899283e90.png)

**Comment by alexsanderkhitev** [comment]
@TimOliver Sorry, it was my fault, I did not know what imageManager.requestImage block is called twice. Once again I'm sorry for your trouble.

**Comment by TimOliver** [comment]
Hey @alexsanderkhitev 

Cool! Thanks for that! I love the kinds of issues that solve themselves. 

Ahh that's good to hear. I wouldn't have known what to do otherwise. The images in the view controller itself are just normal `UIImageView` objects, so they *shouldn't* break on their own.
