### ISSUE TITLE
rotation issue

### ISSUE THREAD

**Issue by keshiim** [TimOliver/TOCropViewController#152]
Hello, I find a when I press rotation button, the image is rotate normal, but the clip rect bounds is out of the image. Can you guys fix it 

![image](https://cloud.githubusercontent.com/assets/3243095/23598662/db832c90-0276-11e7-9135-39179f90f907.png)

![image](https://cloud.githubusercontent.com/assets/3243095/23598670/e592319a-0276-11e7-846f-523c1dd9bd2f.png)

**Comment by TimOliver** [comment]
Hi @keshiim! Can you post the image you're using here?

**Comment by keshiim** [comment]
absolutely
![default](https://cloud.githubusercontent.com/assets/3243095/23605019/03858dcc-0296-11e7-8958-919d5d4322b5.jpg)

**Comment by TimOliver** [comment]
Hmm, I just tested that photo in the demo app, running on my iPhone 7 Plus, iOS 10.3. It worked fine for me!

![img_8646](https://cloud.githubusercontent.com/assets/429119/23641298/fdf0afea-0335-11e7-9419-dfac66418273.PNG)

Unless there are specific steps I need to follow, it sounds like you're just using an older version of the library. Please go back and review the [issue template](https://github.com/TimOliver/TOCropViewController/blob/master/ISSUE_TEMPLATE.md) (without deleting it this time) and make sure you're running the latest version. If not, please re-open this issue and explain in exact detail your setup and steps to reproduce. :)

Thanks!

**Comment by keshiim** [comment]
@TimOliver Thanks. I download project from Github, not use Cocoapods. So I got a old version.

**Comment by TimOliver** [comment]
Ahhh okay. Yeah, you need to run `pod update` to pull new versions from CocoaPods. I mentioned that in the issue template. ;)

Good to hear it works!
