### ISSUE TITLE
How to use it with imageView

### ISSUE THREAD

**Issue by haroonalpha** [TimOliver/TOCropViewController#153]
Sir my requirement is to **open a crop window Or ToCropViewController ** when the user select image from photo gallery or camera. First user click the image view to select image from photo library or camera and then select image. The selected image have to pass the next crop window to crop the selected image. i am unable to open the crop window of this library against selection of image from photo library. below is the code of my project.
```
func imagePickerController(picker: UIImagePickerController!, didFinishPickingImage image: UIImage!, editingInfo: NSDictionary!)
    {
        
        let cropViewController = TOCropViewController(image: image)
        cropViewController.delegate = self
        picker.present(cropViewController, animated: true, completion: nil)
    }
    
    
    func imagePickerControllerDidCancel(_ picker: UIImagePickerController)
    {
        picker.dismiss(animated: true, completion: { () -> Void in })
    }
    
   
    //        Cropper Delegate
    
    func cropViewController(_ cropViewController: TOCropViewController, didCropTo image: UIImage, with cropRect: CGRect, angle: Int)
    {
        cropViewController.dismiss(animated: true) { () -> Void in
            self.imageView.image = image
        }
    }
    
   
    func cropViewController(_ cropViewController: TOCropViewController, didFinishCancelled cancelled: Bool)
    {
        cropViewController.dismiss(animated: true) { () -> Void in  }
    }
```

**Comment by TimOliver** [comment]
Sorry. This is not enough information to be able to help. 

Please go back and fill out the issue template that was provided when you created this issue. At the very least, some code samples and more information about your app would be very helpful.

Thanks!

**Comment by haroonalpha** [comment]
Sir, check the updated comment and code plz.
