### ISSUE TITLE
status bar + navigation bar + toolbar + tab controller

### ISSUE THREAD

**Issue by bishtpradeep** [TimOliver/TOCropViewController#158]
what is the best way to use this library so that I can get:

status bar, navigation bar, toolbar and be able to see my tab controller too. So toolbar should appear just above the tab controller.

Thank you.

**Comment by TimOliver** [comment]
Hi @bishtpradeep!

Hmm, I designed this controller to be presented as a modal view controller, so embedding it in other controllers isn't 100% supported.

If you're using a standard `UITabBarController` and a `UINavigationController`, you *should* be able to make the crop view controller a child of the navigation controller and then make that a child of the tab bar controller. The toolbar will remain on the bottom as long as the controller is in portrait mode (But it's hardcoded to move to the side in landscape).

You might need to modify some of the code of the split view controller to get this working how you want. Let me know if you have any feedback on how we might be able to improve the split view controller for these sorts of circumstances.

Good luck!
