### ISSUE TITLE
How can I set limit output size

### ISSUE THREAD

**Issue by Thanhktm** [TimOliver/TOCropViewController#16]
Hi.

Thank for your library. I'm using it.

Please let's me know how can I set image output limit (maximum).

For example: My ImageView frame is 600x900. So I just want output close to that size as possible.
It's will make my app more lightweight.

Thanh.

**Comment by TimOliver** [comment]
Hi @Thanhktm!

Thanks a lot! I'm glad you're enjoying using my crop view controller library! :)

At the moment, it doesn't do any image resizing; it simply crops an image and returns the cropped version. 

If you want to clamp the overall size of the image, you can simply resize it yourself after it's been returned from the crop view controller (I do this in one of my own apps). I was considering adding resizing, but I think that's sort of outside of the scope of what this controller does.

There's a category here that you can add to your code that'll make clamping your image size as easy as one extra line of code. https://github.com/AliSoftware/UIImage-Resize

Good luck!
