### ISSUE TITLE
Cropping finished delegate selectors are not called

### ISSUE THREAD

**Issue by bartlomiejn** [TimOliver/TOCropViewController#160]
## Hardware / Software

Which version of the library were you using?
2.0.12
Which version of iOS are you running?
10.2.1
What model of iOS device were you testing on?
iPhone 6
If using CocoaPods, which version of CocoaPods are you on?
1.2.0

## Goals

- Receiving a cropping rect / cropped image to use with application

## Expected Results

- Receiving a cropping rect / cropped image to use with application- 

## Actual Results

- Finished cropping delegate methods are not called on delegate object

## Steps to Reproduce

- Install 2.0.12 version of library through Cocoapods 
- `import TOCropViewController` in view controller file
- Instantiate `TOCropViewController` and set its delegate on current view controller
- Present `TOCropViewController` on current view controller
- `didFinishCancelled` gets called properly, other delegate methods do not

Project is written in Swift 2.3, Xcode version `8.2.1`, iOS 9+

Traced through the framework files and it seems that the delegate object doesn't respond to selectors related to finished cropping. Looks like an issue with protocol selector translation to Swift.

![zrzut ekranu 2017-04-10 o 14 26 16](https://cloud.githubusercontent.com/assets/7457946/24861775/27ccb5c8-1dfa-11e7-9b1d-aea22854328a.png)

Only the first method gets called.

**Comment by TimOliver** [comment]
Hi @bartlomiejn! Thanks for the issue!

Hmm, I recently added the `NS_SWIFT_NAME` Swift redefinitions to the delegate methods in order to make them more Swifty. 

```objc
@protocol TOCropViewControllerDelegate <NSObject>
@optional

/**
 Called when the user has committed the crop action, and provides 
 just the cropping rectangle.
 @param cropRect A rectangle indicating the crop region of the image the user chose (In the original image's local co-ordinate space)
 @param angle The angle of the image when it was cropped
 */
- (void)cropViewController:(nonnull TOCropViewController *)cropViewController didCropImageToRect:(CGRect)cropRect angle:(NSInteger)angle NS_SWIFT_NAME(cropViewController(_:didCropToRect:angle:));

/**
 Called when the user has committed the crop action, and provides 
 both the original image with crop co-ordinates.
 
 @param image The newly cropped image.
 @param cropRect A rectangle indicating the crop region of the image the user chose (In the original image's local co-ordinate space)
 @param angle The angle of the image when it was cropped
 */
- (void)cropViewController:(nonnull TOCropViewController *)cropViewController didCropToImage:(nonnull UIImage *)image withRect:(CGRect)cropRect angle:(NSInteger)angle NS_SWIFT_NAME(cropViewController(_:didCropToImage:rect:angle:));

/**
 If the cropping style is set to circular, implementing this delegate will return a circle-cropped version of the selected
 image, as well as it's cropping co-ordinates
 
 @param image The newly cropped image, clipped to a circle shape
 @param cropRect A rectangle indicating the crop region of the image the user chose (In the original image's local co-ordinate space)
 @param angle The angle of the image when it was cropped
 */
- (void)cropViewController:(nonnull TOCropViewController *)cropViewController didCropToCircularImage:(nonnull UIImage *)image withRect:(CGRect)cropRect angle:(NSInteger)angle NS_SWIFT_NAME(cropViewController(_:didCropToCircleImage:rect:angle:));

/**
 If implemented, when the user hits cancel, or completes a 
 UIActivityViewController operation, this delegate will be called,
 giving you a chance to manually dismiss the view controller
 
 */
- (void)cropViewController:(nonnull TOCropViewController *)cropViewController didFinishCancelled:(BOOL)cancelled NS_SWIFT_NAME(cropViewController(_:didFinishCancelled:));

@end
```

I'd recommend double-checking your method names and make sure they match up with the Swift method names defined there. The inconvenient thing about delegate methods is if you name them wrong, they won't trigger any warnings (since they're valid methods on their own) but they simply won't get called by the view controller.

Let me know if you're still having trouble with this! I'm trying to think of other ways to make this controller a bit nicer to work with in Swift.

Thanks!

**Comment by bartlomiejn** [comment]
Hey @TimOliver, thanks for the lib, great work!

I've actually checked the source code for the library. I didn't have the time to check that, but this might be an issue with Swift 2.3. For some reason my delegate implementation doesn't respond to `TOCropViewControllerDelegate` selector calls. I'm using the method signatures suggested by autocompletion and I've also checked the `NS_SWIFT_NAME` definitions for correctness.

**Comment by bartlomiejn** [comment]
I've implemented callbacks that work along the delegate invocations on a forked repo. @TimOliver would you like this as a feature?

**Comment by TimOliver** [comment]
Hey @bartlomiejn! Thanks a lot! Glad you're enjoying my library. :)

Cool! That's certainly a great way to get around this issue. I've been considering trying to make a proper Swift wrapper to sidestep these kinds of issues but that still wouldn't have worked for Swift 2.3

I've merged your PR and I'll cut a new CocoaPods release soon. Thanks! :)

**Comment by anirudhsmarttechnica** [comment]
TOCropViewController whose view is not in the window hierarchy!??????

**Comment by TimOliver** [comment]
Hi @anirudhsmarttechnica! Can you please create a new issue and follow the template to provide as much detail as you can about the issue you're having?
