### ISSUE TITLE
Tapped Done button

### ISSUE THREAD

**Issue by gutierrezralph** [TimOliver/TOCropViewController#162]
> **Questions**: Please check the closed issues to see if it's already been asked
> I have application in xamarin that used TOCropViewController library and i added new button inside SubView ("Ok" button Just for example). my goal is, When i tapped "Ok" button, I want OK button do what Done button do when i tapped. Any hint?

**Comment by TimOliver** [comment]
Hi @gutierrezralph!

Hmm, I'm not sure how well this library integrates with Xamarin. When the 'Done' button is tapped, it calls the method [`doneButtonTapped`](https://github.com/TimOliver/TOCropViewController/blob/master/TOCropViewController/TOCropViewController.m#L706) inside the view controller itself.

You should be able to expose that method and then hook it up to your own button. Good luck!

**Comment by asadqazi** [comment]
I used the latest 2.4 version using cocoapods and still when I press the done button it does not close the crop view controller
