### ISSUE TITLE
How to change the cropper size according to image

### ISSUE THREAD

**Issue by sahabe1** [TimOliver/TOCropViewController#165]
I want to chnage the cropper size accroding to image

**Comment by TimOliver** [comment]
Hi @sahabe1! 

I'm sorry, but I can't help with this question in this current state as there's not enough information. Please go back and fill out the [issue template](https://github.com/TimOliver/TOCropViewController/blob/master/ISSUE_TEMPLATE.md) that was provided in the issue submission form with as much information as you can. :)

Thanks!

**Comment by sahabe1** [comment]
is it possible to set cropper overlay in 2:3 ratio

**Comment by TimOliver** [comment]
Yep! There's a property on `TOCropViewController` itself you can use to set the crop box aspect ratio:

```objc
@property (nonatomic, assign) CGSize customAspectRatio;
```
