### ISSUE TITLE
Rotate Only Image not CropView should not resize according to imageview size.

### ISSUE THREAD

**Issue by mowebkrunal** [TimOliver/TOCropViewController#171]
Hi, I want to rotate image only, Crop Area should not resize according to imageview size but fill imageview with CropView size. How do I do this in this library?

**Comment by TimOliver** [comment]
Hi! That's been requested and discussed here already: https://github.com/TimOliver/TOCropViewController/issues/51

It's not possible at the moment. The rotation feature mirrors the same functionality as the Photos app where the crop box rotates with the image. A PR is welcome if you want to try adding it yourself. :)

**Comment by mowebkrunal** [comment]
Oh ok. Thanks. I will do that in future when I get enough time.
