### ISSUE TITLE
rotateClockwiseButtonHidden does not work

### ISSUE THREAD

**Issue by cooerson** [TimOliver/TOCropViewController#174]
Hardware
iOS 10.0

Expected Behavior

Something (button hidden)

Actual Behavior

Nothing

**Comment by TimOliver** [comment]
Thanks for the issue @cooerson!

I just tried it in the example app (Added the line `cropController.rotateClockwiseButtonHidden = NO;`) and it worked fine for me.

Can you please give me more information on what you're trying to do? Some sample code would be great. :D

**Comment by cooerson** [comment]
![btn_hidden](https://user-images.githubusercontent.com/290716/27625013-a8059b9c-5ba8-11e7-8ac0-724ec31a22f2.jpg)

**Comment by TimOliver** [comment]
![screen shot 2017-06-28 at 10 34 22 am](https://user-images.githubusercontent.com/429119/27651498-64b6c402-5bed-11e7-99d4-18287115bf92.png)

Again, works fine for me.

Hmm, you might have found some weird edge case. Can you please post the code you're using to present the controller?

I'm very busy at the moment, so if this is a bug, I won't have time to fix it. I'd very much appreciate a PR in that case. :)

**Comment by trr-amsiq** [comment]
@TimOliver the bug is on line 124 
`self.toolbar.rotateClockwiseButtonHidden = self.rotateClockwiseButtonHidden && !circularMode;`
should be
`self.toolbar.rotateClockwiseButtonHidden = self.rotateClockwiseButtonHidden && circularMode;`

**Comment by cooerson** [comment]
@TimOliver Sorry, my mistake! This bug is in the circularMode. 😊  😂    
@trr-amsiq Thanks, that's it. But there is no need to modify line 926? 😊

**Comment by fullc0de** [comment]
@TimOliver 
`self.toolbar.rotateClockwiseButtonHidden = self.rotateClockwiseButtonHidden && circularMode;`
If circularMode is `NO`,  `self.toolbar.rotateClockwiseButtonHidden` is always set to `NO`. 
Is it right intention?

In other words, hiding a clockwise button is only available in circularMode.

**Comment by nikitsin** [comment]
Hi guys. It's incorrect behaviour 
self.toolbar.rotateClockwiseButtonHidden = self.rotateClockwiseButtonHidden && circularMode;
Use instead:
self.toolbar.rotateClockwiseButtonHidden = self.rotateClockwiseButtonHidden || circularMode;

**Comment by nikitsin** [comment]
Do you have plans for Swift implementation? I assume it's easy for support and refactoring in future (if exclude some Swift updates across new versions of language)
Thanks

**Comment by entreprenik2** [comment]
Definitely still a bug here in latest version.

**Comment by entreprenik2** [comment]
@TimOliver Here's what I'm using right now to get around it. I think @nikitsin is right.

```objc
[myVC presentViewController:toCropVC animated:NO completion:NULL];
// Adjust toolbar directly to bypass viewDidLoad bug
TOCropToolbar *toolbar = [toCropVC performSelector:@selector(toolbar)];
toolbar.rotateClockwiseButtonHidden = YES;
```
