### ISSUE TITLE
Swift Delegate Method

### ISSUE THREAD

**Issue by srosman8026** [TimOliver/TOCropViewController#176]
Hi I am currently on swift 3 and am having some issues with creating a circular crop view controller through the delegate method. Can someone please just show me their code for doing so along with the functions called that contain the newly cropped image. Thanks so much!

**Comment by drougojrom** [comment]
@srosman8026 , for example

```
extension YourVC : TOCropViewControllerDelegate {
    func openCrop(image: UIImage) {
        let crop = TOCropViewController(croppingStyle: .circular, image: image)
        crop.delegate = self
        present(crop, animated: true, completion: nil)
    }
    
    func cropViewController(_ cropViewController: TOCropViewController, didCropToCircleImage image: UIImage, rect cropRect: CGRect, angle: Int) {
        cropViewController.dismiss(animated: true, completion: {
            self.updatePhoto(image: image)
        })
    }
    
    func cropViewController(_ cropViewController: TOCropViewController, didFinishCancelled cancelled: Bool) {
        cropViewController.dismiss(animated: true, completion: {
            
        })
    }
}
```

**Comment by TimOliver** [comment]
Yep! @drougojrom is correct! Thanks for that! :)

It might be best to make a Swift example project as well...

**Comment by drougojrom** [comment]
@TimOliver , I have the separate swift project, a small one, just for demonstration. Can upload it on separate repository or add inside of your project
