### ISSUE TITLE
I have manually dragged the folder into the project .. the build fails and gives the following errors: A parameter list without types is only allowed in function definition on  this line of code : - (void)setup {     __weak typeof(self) weakSelf = self;

### ISSUE THREAD

**Issue by sundeepvig** [TimOliver/TOCropViewController#180]
- [x] I have read this issue template and provided all possible information. 
- [ ] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> **Please remove this section of the issue template before filing your issue.**
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
>
---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by sundeepvig** [comment]
I have manually dragged the folder into the project .. the build fails and gives the following errors: A parameter list without types is only allowed in function definition on this line of code : - (void)setup { __weak typeof(self) weakSelf = self;

Here is the link to the error screen shot: https://www.dropbox.com/s/wholb3uh5lf5oe1/Screen%20Shot%202017-08-04%20at%203.04.54%20AM.png?dl=0

Any help would be highly appreciated!

Note : The example project works when I download and run it .. when I pull the code into my app, we see this error.

**Comment by TimOliver** [comment]
Hi @sundeepvig!

Sorry, but I'm not sure what you could have done to cause that. It seems like something isn't configured properly in your Xcode project. It's not really anything we can fix on this end.

Make sure you drag the `TOCropViewController` folder into your Xcode project, and make sure 'Copy items if needed' is selected when Xcode prompts you to import.

Aside from that, as long as your project is Objective-C (or bridged properly in Swift) and you're running the latest version of Xcode, it should just work.

Good luck!
