### ISSUE TITLE
"Retake" and "Use photo" buttons are not pressed

### ISSUE THREAD

**Issue by antontereshko** [TimOliver/TOCropViewController#181]
I take a photo, then press "Use Photo" and "Cancel" button from TOCropViewController, then go back to the screen with the photo option. . Retake" and "Use photo" buttons are not pressed.
`       
        private void CropPhoto(object sender, UIImagePickerMediaPickedEventArgs e)
{
            var image = e.Info[UIImagePickerController.OriginalImage] as UIImage;
            var cropVC = new TOCropViewController(TOCropViewCroppingStyle.Circular, image);
            cropVC.Delegate = new CropDelegate(cropVC);
            _imagePicker.PresentViewController(cropVC, true, null);
        }
`
![kcms84lot5m](https://user-images.githubusercontent.com/25593226/29116134-93493990-7d02-11e7-9dd3-6f4de674633e.jpg)

**Comment by TimOliver** [comment]
Hi @antontereshko! Thanks for the issue, but can you please go back and fill out the issue template? I need more information on what you're trying to do here. The Camera isn't a component of this library by default.

**Comment by zhaoyunyi** [comment]
i have the same problem

**Comment by TimOliver** [comment]
I'm still not convinced this is an issue with this library. I need more information. :)

Please provide proper reproduction steps (Or a sample app I can test!). :)

**Comment by vinayakpal** [comment]
Please apply this delegate method of TOCropViewController class in your ViewController & cancel button will redirect you to your parent view rather then the retake & choose View

-(void)cropViewController:(TOCropViewController *)cropViewController didFinishCancelled:(BOOL)cancelled {
    [self dismissViewControllerAnimated:YES completion:nil];
}

**Comment by TimOliver** [comment]
@vinayakpal I just tried that. It dismissed back to the root view controller as expected.

---

Again, this doesn't seem to be an issue directly associated with this view controller; it just sounds like you need to implement your own custom dismissal logic in `- (void)cropViewController:(nonnull TOCropViewController *)cropViewController didFinishCancelled:(BOOL)cancelled` or `void (^onDidFinishCancelled)(bool isFinished)`.

There WAS a bug in the way that the 'Cancel` delegate was getting handled, so I'd at least recommend you update your version of `TOCropViewController` and try again.

Unfortunately, without a demo app or video to see what's happening, I don't know what I can do to help.

If there's some actual code you think might make this process a bit easier, feel free to file a PR. :)

Thanks!

**Comment by kunusiths** [comment]
Hello Tim Oliver,
    I have used your library tocropviewcontroller.it is wonderful.i want to know how to set automatic dimming of other view than crop view.can u tell how to adjust automatically dimming

**Comment by tylerlantern** [comment]
It still exist today.

**Comment by jjyy1008** [comment]
Still exist today.

**Comment by TimOliver** [comment]
If this is indeed an issue with `TOCropViewController` and not UIKit, please open a new issue and attach a sample app that I can use to test. :)
