### ISSUE TITLE
CropViewController won't dismiss when tap Done button 

### ISSUE THREAD

**Issue by shuai265** [TimOliver/TOCropViewController#183]
Test on simulator with iOS 10 and iPhone 6s with iOS 9.2,
![](https://ws1.sinaimg.cn/large/9608ad44ly1fimyg8rx3wj20du010mx2.jpg)

When I use TOCropViewController as the guide, I found I can't dismiss the edit view when i click the done button. However, when I click Cancel button, the edit view dismissed, but the image was cropped too. Just like the GIF show:

https://ws1.sinaimg.cn/large/9608ad44ly1fimyn3dn9hg208s0fq7wr.jpg
![](https://ws1.sinaimg.cn/large/9608ad44ly1fimyn3dn9hg208s0fq7wr.jpg)

then I change your code in the TOCropViewController.m ->- (void)doneButtonTapped , then all issues gone. I think it's better to tell you to see if there is really a error in the code, or is I made  something wrong.
```
    //The change I made
    if (delegateHandled) {
        [self.presentingViewController dismissViewControllerAnimated:YES completion:nil];
    }

    //Origin Code
   // if (!delegateHandled) {
       // [self.presentingViewController dismissViewControllerAnimated:YES completion:nil];
    //}
```

![](https://ws1.sinaimg.cn/large/9608ad44ly1fimyxwj1e8j211q0hcn0v.jpg)

**Comment by TimOliver** [comment]
Hi @shuai265! I pushed a new version of the library that refactors the delegate checking code. Can you please update to the latest version and try again?

**Comment by serjooo** [comment]
I can still confirm that this bug exists, also when I pulled using cocoapods the TOCropViewController.m file had a couple of lines missing semicolons it is around from line 829 - 848

**Comment by TimOliver** [comment]
Okay. I THINK the semicolon issue is resolved, and the delegates have been refactored now. So this SHOULD be fixed now.

Please re-open a new issue with exact reproduction steps if not! :)
