### ISSUE TITLE
iOS 11 - foregroundImageView's initial origin.y is -20 instead of 0

### ISSUE THREAD

**Issue by colinhumber** [TimOliver/TOCropViewController#184]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

Which version of the library were you using? 2.0.12
Which version of iOS are you running? iOS 11b6
What model of iOS device were you testing on? iPad Pro
If using CocoaPods, which version of CocoaPods are you on? 1.3.1

## Goals

Load an image in either orientation into the crop controller.

## Expected Results

The `foregroundImageView` appears fully within the white bounding box.

## Actual Results

The `foregroundImageView` is initially laid out correctly, with it's origin at (0, 0), but after the view has fully appear it snaps to (0, -20). If you interact with the view at all, or rotate, it returns to the desired origin of (0, 0).

## Steps to Reproduce

Launch the example project in iOS 11 and load any photo in your library.

![incorrect](https://user-images.githubusercontent.com/104855/29432281-3e1be6e6-8358-11e7-8fa0-bf66b2731434.PNG)

![correct](https://user-images.githubusercontent.com/104855/29432282-3e202c42-8358-11e7-8d4a-47db97c93ae6.PNG)

**Comment by TimOliver** [comment]
Hey @colinhumber! Thanks so much for bringing this to my attention!

I just added some extra code to disable iOS 11's smart 'safe area' mechanism, so this SHOULD be fixed now.

Could you please download the last copy of `master` and see if it's fixed for you?

Thanks!

**Comment by colinhumber** [comment]
@TimOliver Yup, that's working great! Thanks for the quick fix!

**Comment by TimOliver** [comment]
Awesome! My pleasure! Thanks so much for confirming it for me! :)
