### ISSUE TITLE
Add support to use this library inside Share Extension

### ISSUE THREAD

**Issue by shardul89** [TimOliver/TOCropViewController#186]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software
Which version of the library were you using? **2.0.12**
Which version of iOS are you running? **9, 10, 11b6**
What model of iOS device were you testing on? **5, 6, 6+, 7, 7+, iPad Air, iPad Pro**
If using CocoaPods, which version of CocoaPods are you on? **1.2.0**

## Goals
I want to use this library in one of my app's share extension.

## Expected Results
This library should compile and run properly in main application and also in its share extension.

## Actual Results
Right now if I install this library through cocoa pods for my main application target and share extension target than it gives me compilation errors due to there are two apis that you have used which are not supported to use inside share extension.

**Comment by TimOliver** [comment]
Hey @shardul89! Thanks for the issue and for filling out the form completely.

That's a fantastic idea! I'd never thought about making this library a share extension component.

What are the APIs that it's using that can't be used in the share extension?

**Comment by shardul89** [comment]
@TimOliver I have made few changes into the project and now it supports Main app + Share Extension both. Ping me if you have any doubts in the above PR.
