### ISSUE TITLE
How to set an aspect ratio?

### ISSUE THREAD

**Issue by oskarko** [TimOliver/TOCropViewController#189]
Hi people!

How can I clamp the crop box to a specific aspect ratio? I don't find it out anywhere

**Comment by TimOliver** [comment]
Hi @oskarko!

There's a property called `customAspectRatio` you can use to lock the image to your own ratio size.

```objc
/**
 A CGSize value representing a custom aspect ratio, not listed in the presets.
 E.g. A ratio of 4:3 would be represented as (CGSize){4.0f, 3.0f}
 */
@property (nonatomic, assign) CGSize customAspectRatio;
```

Hope that helped!
