### ISSUE TITLE
Aspect Ratio not applying properly

### ISSUE THREAD

**Issue by Ramev282** [TimOliver/TOCropViewController#19]
Hello Tim,
I've found one issue with applying aspect ratio and I'd like to bring it to your attention. Please try cropping a picture with width of 130px and height of 490px. If I choose a fixed aspect ratio (4:5 for an example) from the menu, It's not applying properly first time. I have to do twice to get it right. Please fix this issue as soon as you can. Thank you in advance!

**Comment by TimOliver** [comment]
Hi @Ramev282!

Thanks for the bug report. I've heard there's a few glitches here and there with the system that constrains the aspect ratio.

Unfortunately, I'm going to be ridiculously busy for the next few weeks, so I'm not going to have any time to diagnose/fix the issue for a little while. If you've got some time, feel free to have a look at it yourself. If you can fix it before I can, feel free to file a PR! :)

**Comment by TimOliver** [comment]
Fixed! :grin: 

Let me know if you find any other bugs!
