### ISSUE TITLE
how can i fix the crop box size & aspect ratio before enter the TOCropViewController 

### ISSUE THREAD

**Issue by vinayakpal** [TimOliver/TOCropViewController#192]
The situation is:
i need to set a profile picture which is taken from my gallery or camera but i need only single frame which has fixed aspect ratio of 1:1 & maximum size id 400x400 can you please help

**Comment by TimOliver** [comment]
Hi @vinayakpal!

You can use `TOCropViewController.aspectRatioPreset` to set the aspect ratio to square, and then use  `TOCropViewController.aspectRatioLockEnabled` to lock it to the square shape.

This library doesn't support locking to a specific pixel size. Once the crop is complete, I'd recommend your own Core Graphics operation to resize the image afterwards. :)

Hope that helped!

**Comment by jzy476731162** [comment]
I select the cropSize as TOCropViewControllerAspectRatioPresetSquare
and set aspectRatioLockEnabled == YES at the same time,
but the reset bug is enable and would reset the cropView ratio to Imagesize
Is it a bug ?

**Comment by vinayakpal** [comment]
Hi Tim,

Thanks for your concern i just need to ask few more doubts that how can i
bypass the default imagePickerController to go directly to TOCropView
Controller.
Secondly, i also want to present the crop frame size like for photo i need
size max 400X400 & for cover image 1000X560 to be the maximum size

**Comment by TimOliver** [comment]
Sorry for the delay.

1. The standard iOS image picker isn't attached to `TOCropViewController`. It's only like that in the demo app so you can pick an image to easily test it. All you need to do is init `TOCropViewController` with `[[TOCropViewController alloc] initWithImage:myImage]` to create a new instance, and you can present it from any view controller in your app beyond that.
2. This library doesn't deal in absolute pixel sizes. You can lock down the aspect ratio (eg, 400x400 would be a 1:1 ratio), but then it's your app's responsibility to downscale or upscale images to the size you want after the fact.

I hope that helped!
