### ISSUE TITLE
Image Movement very fast issue

### ISSUE THREAD

**Issue by MVJadav** [TimOliver/TOCropViewController#194]
Hello,
i used TOCropViewController to crop image,but when i cropping image, zoomin-zoomout (Movement) is very fast. image moved very fast. that issue occured in app.

![simulator screen shot 11-sep-2017 11 07 17 am](https://user-images.githubusercontent.com/24539258/30259912-cafa9e12-96e1-11e7-87d1-5110466a34af.png)

**Comment by TimOliver** [comment]
Hi @MVJadav! You might need to upload a screen recording to show us what's happening exactly! :)

**Comment by MVJadav** [comment]
Hello Sir. 
Please check attachment video.
[movement vety fast.zip](https://github.com/TimOliver/TOCropViewController/files/1291613/movement.vety.fast.zip)

**Comment by MVJadav** [comment]
i implemented below code to crop my image. 
----------------------------------------------
func ImageCrop(image:UIImage) {
        
        
        //initializing the TOCropViewController
        let controller:TOCropViewController = TOCropViewController(croppingStyle: .default, image: image)
        controller.delegate = self
        
        controller.aspectRatioPreset = .presetSquare
        controller.cropView.aspectRatioLockEnabled = true
        controller.cropView.cropBoxResizeEnabled = false
        controller.aspectRatioPickerButtonHidden = true

        present(controller, animated: true, completion: nil)
        
    }
func cropViewController(_ cropViewController: TOCropViewController, didCropToImage image: UIImage, rect cropRect: CGRect, angle: Int) {
        
        self.updateImageViewWithImage(image: image, cropViewController: cropViewController)
    }
    
    func updateImageViewWithImage(image:UIImage, cropViewController:TOCropViewController) {
        
        cropViewController.presentingViewController?.dismiss(animated: true, completion: nil)
       
        self.IBimgLogo.image = image
    }

**Comment by TimOliver** [comment]
Ahh thanks for that! I see the problem.

You're setting the properties on `cropView` directly. That's not recommended since the view controller itself also needs to perform some management logic on top.

If you change it to:

```swift
let controller:TOCropViewController = TOCropViewController(croppingStyle: .default, image: image)
    controller.delegate = self
    
    controller.aspectRatioPreset = .presetSquare
    controller.aspectRatioLockEnabled = true
    controller.aspectRatioPickerButtonHidden = true
    controller.resetAspectRatioEnabled = false;
```

That SHOULD fix it. :)

Let me know how you go!

**Comment by MVJadav** [comment]
Hello sir, i used that changes, but still same issue occurring.....

    func ImageCrop(image:UIImage) {
        let controller:TOCropViewController = TOCropViewController(croppingStyle: .default, image: image)
        controller.delegate = self
        controller.aspectRatioPreset = .presetSquare
        controller.aspectRatioLockEnabled = true
        controller.aspectRatioPickerButtonHidden = true
        controller.resetAspectRatioEnabled = false
        present(controller, animated: true, completion: nil)
 }

**Comment by TimOliver** [comment]
Hmm. It's working fine for me in the demo app. Are you using the latest version of the library?

**Comment by MVJadav** [comment]
yes sir. we are using latest version of the library pod.....

**Comment by MVJadav** [comment]
[Untitled.zip](https://github.com/TimOliver/TOCropViewController/files/1291911/Untitled.zip)

please see that screens, when i going to crop my image i face that issue, movement is very fast.

**Comment by MVJadav** [comment]
Hello Sir i'm using tab bar in my App. you can see screens....

![screen1](https://user-images.githubusercontent.com/24539258/30266943-98706d10-96fe-11e7-973f-12fe20f0040a.png)
![screen2](https://user-images.githubusercontent.com/24539258/30266942-986e7596-96fe-11e7-82be-fe973d2a050c.png)
![screen3](https://user-images.githubusercontent.com/24539258/30266946-987ddcac-96fe-11e7-8ec8-e861ccf069ee.png)
![screen4](https://user-images.githubusercontent.com/24539258/30266945-987ca18e-96fe-11e7-8dcb-8e8e42d89a90.png)
![screen5](https://user-images.githubusercontent.com/24539258/30266949-98821c36-96fe-11e7-80de-d97f106e97e7.png)
![screen6](https://user-images.githubusercontent.com/24539258/30266948-988208e0-96fe-11e7-8592-162981aaa779.png)
![screen7](https://user-images.githubusercontent.com/24539258/30266951-9899379a-96fe-11e7-835c-a47b807241e0.png)

**Comment by TimOliver** [comment]
I've got nothing. If I can't replicate it on my own devices, I can't fix it. Sorry.

Make sure you've properly got the latest version by running 'pod repo update'. If it keeps happening, see if you can replicants it in a demo app for me. :)

**Comment by MVJadav** [comment]
i got issue.
when i use **https://github.com/vlasov/CCBottomRefreshControl** in my app then i face that issue. 
Can you resolved that issue..?

**Comment by MVJadav** [comment]
is it possible custom rotate image with 'TOCropViewController' pod....?

**Comment by TimOliver** [comment]
Hmm, if there's a category in another project that modifies the behaviour of `UIScrollView`, that could certainly do it. I don't know if that's something I can explicitly support though. Sorry.

In any case, I had to substantially modify some of the workings of this library for iPhone X support, so it might be worth testing again.

Good luck!

**Comment by vientn1998** [comment]
I am error same video of MVJadav. You can help me @TimOliver ?
Example on github i am fine. But when i import pod on project.  but still same issue occurring

**Comment by TimOliver** [comment]
Hi @vientn1998! I can't offer free tech support, so I can't promise if I can actually help or not. 😅 Please open a new issue and provide as much info about your app and any other third party libraries you might be using. 🙏
