### ISSUE TITLE
Edit Frame overlaps with the status Bar

### ISSUE THREAD

**Issue by mugunth87** [TimOliver/TOCropViewController#195]
When i load the library the top frame of the edit functionality overlaps with the status bar. Hence when i try to crop at the top instead of cropping the notification screen opens up. I have attached the screenshot of the issue. I'm using the latest version of the library.
![img_0003](https://user-images.githubusercontent.com/16566598/30291979-b95870ca-96f1-11e7-8b44-2872e30b8509.PNG)

**Comment by TimOliver** [comment]
Ahh I don't think anyone has tried pushing a non-circlular cropper to a UINavigationController before.

This should be a really easy fix. It's just a matter of setting cropView's contentInset to account for the status bar.

I don't have anymore time to work on it this this week, so a PR would really be appreciated. :)

**Comment by TimOliver** [comment]
I ended up fixing this in my iPhone X support. It should be all good now. :)
