### ISSUE TITLE
Changing "Done" button title from another class

### ISSUE THREAD

**Issue by anilios** [TimOliver/TOCropViewController#20]
Is there a way to access Done button's title from other class ?

**Comment by TimOliver** [comment]
Hi! Not at the moment, but it would be really easy to add. It's just a matter of adding a new external property to override the internal value.

If you're up for it, feel free to make the modifications yourself and then file a pull request! :)

Thanks!

**Comment by TimOliver** [comment]
In PR https://github.com/TimOliver/TOCropViewController/pull/32, the Done button in the toolbar has now been exposed, so you should be able to do this now.

Let me know how it goes!

**Comment by adrianodiasx93** [comment]
```
let toCropViewController = TOCropViewController(croppingStyle: .circular, image: pickedImage)
toCropViewController.delegate = self
toCropViewController.toolbar.doneTextButton.placeholderText = "Confirmar"
toCropViewController.toolbar.cancelTextButton.placeholderText = "Cancelar"
present(toCropViewController, animated: true, completion: nil)
```

Is this how should I do it? Currently not working. Currently, the renaming does not work.
