### ISSUE TITLE
Customize Texts

### ISSUE THREAD

**Issue by Mahan3340** [TimOliver/TOCropViewController#202]
Hi , please add Some methods to Customize font , color , and text of  "done" and "cancel" buttons

**Comment by drougojrom** [comment]
@TimOliver , I've done this in my project already, can send a PR, if you approve.

**Comment by Mahan3340** [comment]
@TimOliver  yea do so please I really need this feature

**Comment by TimOliver** [comment]
Cool! Yeah @drougojrom, if you've already designed a public interface, I'd be happy to take a look at merging it in! :)

**Comment by Malecks** [comment]
I've submitted a PR to set a custom string for both the `Done` and `Cancel` buttons here - #210

**Comment by Mahan3340** [comment]
thanks , custom fonts added too ?

**Comment by TimOliver** [comment]
Oh dear. No, it was just changing the text that gets displayed.

What would the best way to add more control be? Adding an optional `NSAttributedString` alternative?

**Comment by Mahan3340** [comment]
thanks for your quick replies , i just need font and color to be added to this new feature and you may want yo add it as setFont and setColor methods or a whole NSAttributed , do the one thats easier for you :D please

**Comment by sahandnayebaziz** [comment]
@Mahan3340 @TimOliver We already have access to each `UIButton`, so that should be enough!

For example, I was hoping to make them both white in my app, and I was able to do that with the following after initializing `CropViewController`:

```swift
vc.toolbar.doneTextButton.setTitleColor(.white, for: .normal)
vc.toolbar.cancelTextButton.setTitleColor(.white, for: .normal)
```

**Comment by sahandnayebaziz** [comment]
@Mahan3340 So, from there, you can do anything you can do to a `UIButton`, like change the font of `.titleLabel`, etc, etc :) 

https://developer.apple.com/documentation/uikit/uibutton
