### ISSUE TITLE
Set the minimum cropping box to 300 (width) x 500 (height)

### ISSUE THREAD

**Issue by hazzaldo** [TimOliver/TOCropViewController#208]
Hi, thanks Tim for this great cropping tool. I wanted your wisdom on the following: I wanted to set the minimum cropping size to 300 (width) x 500 (height) in pixels. I'm not sure if I've done this correctly, but in `TOCropView.m` I changed the lines:
`contentRect.size.width = CGRectGetWidth(self.bounds) - ((kTOCropViewPadding * 2) + self.cropRegionInsets.left + self.cropRegionInsets.right);`
and
`contentRect.size.height = CGRectGetHeight(self.bounds) - ((kTOCropViewPadding * 2) + self.cropRegionInsets.top + self.cropRegionInsets.bottom);`  
so that the `contentRect.size.width` value is set to 300 and `contentRect.size.height` is set to 500. 
Now when I pinch-in to minimise the crop box it does stop at certain point in size where I can't minimise its size any further. However, when I let go, it would expand again to the screen size, and expanding the cropped content with it (which start to pixelate the cropped image content). And I can keep minimising the crop box and it expands again, expanding the content. And I can go on as long as I want. So how do I stop the crop box from expanding the first time, and just stays fixed where I left it, but ensure the minimum cropping size is 300 (w) x 500 (h)? 

Many thanks in advance.

**Comment by TimOliver** [comment]
Hi @hazzaldo! Thanks for the kind words!

We've had a feature request for a minimum cropping size before: https://github.com/TimOliver/TOCropViewController/issues/46

Given the zooming nature of the crop box, it'd be a matter of calculating the smallest size the crop box frame is allowed to be, relative to the size of the image on-screen, and then making sure the user can't shrink the crop box beyond that.

I'd like to add it at some point, but I've got so many other projects in the works, I can't really do too many specific feature requests. Sorry!

Probably the easiest thing I can recommend is if you can use the aspect ratio lock, use that to clamp the crop box to the aspect ratio of 500/300 and then use post processing afterwards to upscale if you need.

I hope that helped!
