### ISSUE TITLE
When presenting from popover view controller on iPad

### ISSUE THREAD

**Issue by DarkDarius** [TimOliver/TOCropViewController#21]
This bug with transition occurs, when i present this beautiful view controller from popover view controller on my iPad. 

For some reasons "presenting view controller" (my popover) gets frame from "presented view controller" (my cropViewController) during transition. 

Now i forked your control and simply removed that line of code:
previousController.view.frame = containerView.bounds;
In file TOCropViewControllerTransitioning.m

I'm Waiting for update.

Thank you!

Watch video: 
https://youtu.be/-d6oGx6KwWE

**Comment by TimOliver** [comment]
Done! Thanks for that! :)
