### ISSUE TITLE
Clockwise Image rotation issues + crash on commit 15e45fc, Nov 17, 2017 

### ISSUE THREAD

**Issue by rogomantik** [TimOliver/TOCropViewController#212]
- [ x] I have read this issue template and provided all possible information. 

## Hardware / Software
iphonex simulator
iphone8 simulator
iphone 6
last version ios 11

drop files + bridging header
1 file changed TOCropViewControllerTransitioning to fix the streched image when calling fromView

```
UIImageView *imageView = nil;
    if ((self.isDismissing && !CGRectIsEmpty(self.toFrame)) || (!self.isDismissing && !CGRectIsEmpty(self.fromFrame))) {
        imageView = [[UIImageView alloc] initWithImage:self.image];
        
        if (self.fromView && [self.fromView isKindOfClass: [UIImageView class]]) { //ADDED
            imageView.contentMode = self.fromView.contentMode; //ADDED
        } //ADDED
        
        imageView.frame = self.fromFrame;
        [containerView addSubview:imageView];
    }
```

using swift 4

## Instructions for example app
press plus, crop image
select an image (open crop controller)
press 1 time rotate clockwise
press done
the image is correctly displayed in the example
touch the image (open again crop controller)  (_open angle 90_)
**After the animation the image is rotated 1 time anticlockwise**

if instead of pressing  1 time rotate clockwise you press 3 times anticlockwise the bug is not present
(_in this case the open angle is  -270_)

I'm fixing by 
```
 var mAngle: Int = 0 { //@property (nonatomic, assign) NSInteger angle;
        didSet {
            if mAngle == 90 {
                mAngle = -270
            }
        }
    }
```

## Issue on commit 15e45fc, Nov 17, 2017 
on iphone x simulator
iphone 6 8.1 simulator

Instructions
press plus, crop image
select an image (open crop controller)
rotate in any direction 
press done
the image is correctly displayed in the example
touch the image (open again crop controller)

> 2017-11-17 17:20:41.511162+0100 TOCropViewControllerExample[76990:21157502] *** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x000000010c3f61cb __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x000000010b90af41 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010c46ab95 +[NSException raise:format:] + 197
> 	3   QuartzCore                          0x000000010d0601bc _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
> 	4   QuartzCore                          0x000000010d050c76 -[CALayer setPosition:] + 43
> 	5   QuartzCore                          0x000000010d05130b -[CALayer setFrame:] + 549
> 	6   UIKit                               0x000000010d2ca45e -[UIView(Geometry) setFrame:] + 368
> 	7   TOCropViewControllerExample         0x000000010afa336f -[TOCropView setCropBoxFrame:] + 1455
> 	8   TOCropViewControllerExample         0x000000010afa8750 -[TOCropView rotateImageNinetyDegreesAnimated:clockwise:] + 4672
> 	9   TOCropViewControllerExample         0x000000010afa74fc -[TOCropView rotateImageNinetyDegreesAnimated:] + 60
> 	10  TOCropViewControllerExample         0x000000010afa5241 -[TOCropView setAngle:] + 225
> 	11  TOCropViewControllerExample         0x000000010afc7206 -[TOCropViewController setAngle:] + 70
> 	12  TOCropViewControllerExample         0x000000010afc2480 -[TOCropViewController presentAnimatedFromParentViewController:fromImage:fromView:fromFrame:angle:toImageFrame:setup:completion:] + 832
> 	13  TOCropViewControllerExample         0x000000010afac414 -[ViewController didTapImageView] + 1060
> 	14  UIKit                               0x000000010d812efb -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
> 	15  UIKit                               0x000000010d81bd83 _UIGestureRecognizerSendTargetActions + 109
> 	16  UIKit                               0x000000010d81962e _UIGestureRecognizerSendActions + 307
> 	17  UIKit                               0x000000010d81889a -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 1002
> 	18  UIKit                               0x000000010d7fdbfd _UIGestureEnvironmentUpdate + 1306
> 	19  UIKit                               0x000000010d7fd697 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
> 	20  UIKit                               0x000000010d7fc743 -[UIGestureEnvironment _updateGesturesForEvent:window:] + 288
> 	21  UIKit                               0x000000010d292228 -[UIWindow sendEvent:] + 4102
> 	22  UIKit                               0x000000010d235d96 -[UIApplication sendEvent:] + 352
> 	23  UIKit                               0x000000010db77fce __dispatchPreprocessedEventFromEventQueue + 2809
> 	24  UIKit                               0x000000010db7ac23 __handleEventQueueInternal + 5957
> 	25  CoreFoundation                      0x000000010c3992b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	26  CoreFoundation                      0x000000010c438d31 __CFRunLoopDoSource0 + 81
> 	27  CoreFoundation                      0x000000010c37dc19 __CFRunLoopDoSources0 + 185
> 	28  CoreFoundation                      0x000000010c37d1ff __CFRunLoopRun + 1279
> 	29  CoreFoundation                      0x000000010c37ca89 CFRunLoopRunSpecific + 409
> 	30  GraphicsServices                    0x0000000112ac79c6 GSEventRunModal + 62
> 	31  UIKit                               0x000000010d21923c UIApplicationMain + 159
> 	32  TOCropViewControllerExample         0x000000010afb611f main + 111
> 	33  libdyld.dylib                       0x000000011072cd81 start + 1
> 	34  ???                                 0x0000000000000001 0x0 + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by TimOliver** [comment]
Ahh thanks for that! I discovered it myself yesterday too.

I fixed it and just pushed the changes now. Let me know if the issue is still persisting for you. :)
