### ISSUE TITLE
Carthage Issue with 2.2?

### ISSUE THREAD

**Issue by inPhilly** [TimOliver/TOCropViewController#213]
- [ X] I have read this issue template and provided all possible information. 

---
I just downloaded the latest version from Carthage, and now the files can't be found. Using 
#import <TOCropViewController/TOCropViewController.h>
in an Objective C app.
---

## Hardware / Software

Which version of the library were you using?"2.2"
Which version of iOS are you running?Simulator (any version)
What model of iOS device were you testing on?Simulator (any device)
If using CocoaPods, which version of CocoaPods are you on?N/A

## Expected Results

What did you expect to happen? Build and run without getting the error:
'TOCropViewController/TOCropViewController.h' file not found

## Actual Results

What happened instead?
Build and get error: 'TOCropViewController/TOCropViewController.h' file not found

## Steps to Reproduce

update TOCropViewController in Carthage, make sure everything setup properly for Carthage, Build app

**Comment by TimOliver** [comment]
Oh dear. I didn’t touch any of that stuff. It should have kept working. Something must have changed with the way the dynamic framework is built. I’ll have to check it when I get a chance.

**Comment by TimOliver** [comment]
Huh. Okay yeah, `TOCropViewController.h` wasn't being included in the public headers for the framework.

I've just released v2.3.2. Hopefully that should fix it!

**Comment by inPhilly** [comment]
2.3.4 builds fine. Thanks : )
