### ISSUE TITLE
Unable to initialize CropViewController because all of initializer are internal ones except required public init?(coder aDecoder: NSCoder)

### ISSUE THREAD

**Issue by jcooperation0137** [TimOliver/TOCropViewController#214]
I've used CropViewController 2.3.4 through cocoaPods.
I've imported the CropViewController module into my view controllers.
But I could not use CropViewController because all of initializer are internal functions, not public.
So I've used init?(coder aDecoder: NSCoder) and then could not set the image to be cropped.
How to solve this issue?
Hope your response.
Thanks.

**Comment by TimOliver** [comment]
Oops! Oh dear! I think I needed to mark those two methods as explicitly `public`. Sorry!

I just made them public now, please try and pull directly from `master` and try it again:

```
pod 'CropViewController', :git => 'https://github.com/TimOliver/TOCropViewController.git'
```

**Comment by jcooperation0137** [comment]
Thanks for your help. @TimOliver.
