### ISSUE TITLE
Can't hide rotation button

### ISSUE THREAD

**Issue by freaqed** [TimOliver/TOCropViewController#215]
First of all - big thanks for such a great library. This is one of my favorites.

- [+] I have read this issue template and provided all possible information. 
- [+] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

Which version of the library were you using? **2.1.0**
Which version of iOS are you running? **iOS 11.1**
What model of iOS device were you testing on? **iPhone 7/6s, Simulator**
If using CocoaPods, which version of CocoaPods are you on? **1.3.1**

## Goals

I'm trying to hide rotation button using library's public API.

## Expected Results

Rotation button (http://joxi.ru/12MZwqYU4W7EjA) is hidden.

## Actual Results

Rotation button present without respect to API calls.

## Steps to Reproduce

Run crop controller as follows:
```
let croppingStyle: TOCropViewCroppingStyle = preset == .circular ? .circular : .default
let cropController = TOCropViewController(croppingStyle: croppingStyle, image: image)
cropController.delegate = self
cropController.customAspectRatio = CGSize(width: 5, height: 10)
cropController.rotateClockwiseButtonHidden = true // this one
cropController.rotateButtonsHidden = true         // and this one do nothing
cropController.aspectRatioLockEnabled = true
cropController.resetAspectRatioEnabled = false
```

**Comment by TimOliver** [comment]
Hi @freaqed! Thanks for the thorough report! I'm glad you found this framework useful.

I just tested it myself and it seemed fine to me.

We're on version 2.2 of the library now, can you try pulling the latest version and trying to see if that fixes it?

Thanks a lot!

**Comment by freaqed** [comment]
Thanks for such a fast response!
Just checked v. 2.2 - result is the same. 
I've created a clean project which reproduces an issue - https://www.dropbox.com/s/p5y7hi329tonvmg/TestCropTool.zip?dl=0
And result I've got from running test project - http://joxi.ru/DmBz9OLUNp8agm
Suppose this button (in a red frame) shouldn't be there.

**Comment by TimOliver** [comment]
Oh wow. Okay. Not great.

I think the reason it was a bug was because the controller was being really conservative with setting up the rotation buttons, so there was a logic glitch where one was created, but then the command to hide it wasn't getting through.

I just made the whole logic a lot more simple. Try pulling straight from `master` now, and only setting `cropController.rotateButtonsHidden = true`. It SHOULD work now. :)

**Comment by freaqed** [comment]
Now it works like a charm!
Thanks, @TimOliver!
