### ISSUE TITLE
swift pod

### ISSUE THREAD

**Issue by rakeshkathoju** [TimOliver/TOCropViewController#218]
how to download swift pod file

**Comment by TimOliver** [comment]
Hi @rakeshkathoju!

Please do not delete the issue template and replace it with a single sentence. I can't help with just that amount of info. 😅

The name of the Swift pod is `CropViewController`. Please refer to the [CocoaPods installation manual](https://guides.cocoapods.org/using/the-podfile.html) for properly formatting your Podfile.

Good luck!

**Comment by HariNarayanan777** [comment]
i am getting error when i install swift pod file into my project , like : 

> " [!] Unable to find a specification for `CropViewController`"

please tell what the issue it was
its fine in Objective-C

**Comment by TimOliver** [comment]
You might need to call `pod repo update` to reload your local copy of the master CocoPods specs if you haven’t done it in a while.

**Comment by HariNarayanan777** [comment]
yeah yes yes,,,, after  update the pod
> pod repo update

` pod 'CropViewController'` was successfully installed.. Thank you so Much TimOliver
