### ISSUE TITLE
image position 

### ISSUE THREAD

**Issue by rakeshkathoju** [TimOliver/TOCropViewController#221]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> how can i use  cropview from storyboard. and set image position to center 
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
>
---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by TimOliver** [comment]
Uhh, thanks for submitting a new issue, @rakeshkathoju. But you're supposed to fill out those questions at the bottom! 😅

Anyway, to answer your question as best as I can: `TOCropViewController` doesn't implement `IBInspectable`, so it can't really be configured in Interface Builder.

You should be able to use the 'User Defined Runtime Attributes' window in IB to set any initial parameters you'd like the crop view controller to have.

![screen shot 2017-11-27 at 5 37 35 pm](https://user-images.githubusercontent.com/429119/33260040-ae1fa0c2-d399-11e7-9149-63b8f3d922c3.png)

I'm not sure what you mean by 'set image position to center'. The image is automatically centered by default. If you want to zoom in, you'll need to manually calculate the crop frame of the region you want to focus on, which might need to be done in code over IB.

Good luck!

**Comment by rakeshkathoju** [comment]
this is what i am getting 
![simulator screen shot - iphone 8 plus - 2017-11-27 at 17 06 58](https://user-images.githubusercontent.com/23329327/33264915-75821262-d395-11e7-82e1-ce361b76f0f9.png)

by my expected is 
![simulator screen shot - iphone 8 plus - 2017-11-27 at 17 07 02](https://user-images.githubusercontent.com/23329327/33264924-859f746e-d395-11e7-89b9-beaa38a7da8a.png)
