### ISSUE TITLE
zoom out image

### ISSUE THREAD

**Issue by rakeshkathoju** [TimOliver/TOCropViewController#222]
- [ ] I have read this issue template and provided all possible information. 
- [ ] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> how can i enable  zoom out . i need to crop zoom out image and crop it 
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
>
---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?
![simulator screen shot - iphone 6 - 2017-11-27 at 18 21 16](https://user-images.githubusercontent.com/23329327/33267543-de87d0c6-d39f-11e7-8958-6028ea900f80.png)

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

if i zoom out it is resetting to original position

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by TimOliver** [comment]
Oh I see. You want to be able to continue zooming out the image, and then insert padding around the image.

Sorry, that's not possible in this library. If you want to add padding to a picture, it might be best to just Core Graphics to generate the final image with the padding in your own code.

Since a lot of the layout code depends on the minimum scale size of the scroll view, it would be a pretty fundamental change to the way this crop view controller works to add that in. Sorry.
