### ISSUE TITLE
cropView

### ISSUE THREAD

**Issue by rakeshkathoju** [TimOliver/TOCropViewController#226]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> ** i need to show images in from gallery and need to show cropable area for every image  can i achieve this using CropView.h please let me know **
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
>
---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by TimOliver** [comment]
Hi @rakeshkathoju!

No I don't think this is possible. This library doesn't have any integration with a gallery of pictures; only one at a time. If you want to highlight the croppable region of each image in a list, you might need to implement that yourself.

Also, there's no file called `CropView.h` in this library, only `TOCropView.h` and that one is where all of the view logic for the cropper is managed.

In future, please make all efforts to fill out the issue template more thoroughly. The main sections I'm after for this sort of issue are the *Goals* and *Expected Results* section.

Thanks!
