### ISSUE TITLE
Title In iPhone X Incomplete display

### ISSUE THREAD

**Issue by yangyu2010** [TimOliver/TOCropViewController#228]
TOCropViewController title "Crop Image" in iPhone X Incomplete display

**Comment by TimOliver** [comment]
Can you please attach a screenshot? Thanks!

**Comment by TimOliver** [comment]
Aha! I just tried it myself and confirmed it. It was a bug in the layout code.

Fixed as of version 2.3.6. :D Thanks for the issue!
