### ISSUE TITLE
Crash when Add CropViewController using Carthage!

### ISSUE THREAD

**Issue by UzumakiAlfredo** [TimOliver/TOCropViewController#229]
Hi, thanks for this cool framework.

My app crashes when when wants to launch with this error:

dyld: Library not loaded: @rpath/CropViewController.framework/CropViewController

**Comment by TimOliver** [comment]
Thanks! Glad you like it!

Uhh, I normally use CocoaPods, so I don't know a lot about Carthage. It SOUNDS like you're not adding the `framework` to the Embedded Binaries section of your app in the project settings.

https://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

I can't really help out any further without reproduction steps. Good luck! :)

**Comment by rodericj** [comment]
I had a similar issue @UzumakiAlfredo, I had to actually add both `CropViewController.framework` and `TOCropViewController.framework` to the Run Script phases.

**Comment by TimOliver** [comment]
Hmm, that doesn't sound correct. The goal of `CropViewController.framework` is to contain all of the Objective-C and Swift files needed for it to run. Having `TOCropViewController.framework` as well contributes to the dynamic framework slowing down app launch times problem.

I'll have to have another play with it to see.

**Comment by rodericj** [comment]
I just removed TOCropViewController from my copy frameworks phase and got 

```
 dyld: Library not loaded: @rpath/TOCropViewController.framework/TOCropViewController
  Referenced from: /x/y/z/my.app
  Reason: image not found
```

¯\_(ツ)_/¯
