### ISSUE TITLE
reset button, revert back the customAspectRatio and aspectRationLock settings

### ISSUE THREAD

**Issue by adli** [TimOliver/TOCropViewController#230]
## Hardware / Software

Which version of the library were you using? 2.3.5
Which version of iOS are you running? 11.2
What model of iOS device were you testing on?  iPhone 6s simulator
If using CocoaPods, which version of CocoaPods are you on?   1.4.0.rc.1

## Goals

What is the outcome result you want to achieve with this library?
crop an image in square form for user profile picture

## Expected Results

What did you expect to happen?

when setting   
customAspectRatio  = CGSize(width:1, height: 1) 
aspectRationLockEnabled = true   

it should only allow cropping a square rectangle  even after clicking on Reset Button on the toolbar

## Actual Results

What happened instead?  
if you click on Reset button on the toolbar, it ignore the customAspectRatio setting.

**Comment by TimOliver** [comment]
You need to set `resetAspectRatioEnabled = NO` as well. :)

**Comment by adli** [comment]
Thanks I didn't know about that :)
