### ISSUE TITLE
Use of unresolved identifier 'CropViewController' after successful installation of CropViewController  using Pods

### ISSUE THREAD

**Issue by dddOO7** [TimOliver/TOCropViewController#232]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---
I have installed CropViewController using CocoaPods, and I have also verified about I am using latest version of CocoaPods and my pod repo is also updated.

But after successful installation of CropViewController, I am trying to implement CropViewController using your given sample code but I am getting  **Use of unresolved identifier 'CropViewController'** error. My projects has other pods also and they all working fine. But I am not able to find why compiler not found CropViewController which I can see inside Pods directory of my project.

**Comment by TimOliver** [comment]
Hi @dddOO7! I just tried it myself. It looks like you needed to type `import TOCropViewController` as well to get it working.

I just completely refactored how that stuff works, so all of the Objective-C code is wrapped up alongside the Swift code, meaning that shouldn't be necessary anymore.

Try running `pod update` on your project directory and let me know if that works. Thanks!

**Comment by dddOO7** [comment]
Hi @TimOliver thanks for information, I have tried `pod update` and `import TOCropViewController`, but  as I am working in swift, so for me `import CropViewController` works to resolve **Use of unresolved identifier 'CropViewController' error**.

Thanks!

**Comment by Md-Sadham** [comment]
I did manual installation of your frameworks for my projects. After importing, now am facing "No Such Module 'CropViewController'". What should I Do now? Give solution without suggesting pod.

**Comment by truptisride** [comment]
import CropViewController it will solve problem for swift users

**Comment by truptisride** [comment]
@TimOliver swift example is not compiling pls updated on the same

**Comment by VanithaVijayakumar** [comment]
> I did manual installation of your frameworks for my projects. After importing, now am facing "No Such Module 'CropViewController'". What should I Do now? Give solution without suggesting pod.



> I did manual installation of your frameworks for my projects. After importing, now am facing "No Such Module 'CropViewController'". What should I Do now? Give solution without suggesting pod.

Even I'm facing the same issue did you fix the issue?

**Comment by VanithaVijayakumar** [comment]
Hi, @TimOliver I did the manual installation of your frameworks for my projects. After importing, now am facing "No Such Module 'CropViewController'". What should I Do now? Give solution without suggesting pod.
