### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gkedmi** [TimOliver/TOCropViewController#235]
Hi
I wanted to ask how to make profile picture with a crop image of hexagon and not a circle?
Thanks a lot
Gilad

**Comment by TimOliver** [comment]
Hi @gkdemi!

That's not possible with the present implementation. Only a static circle, or a resizable square is possible.

You could potentially modify the library yourself to do it. All the circle graphic is is setting a `CALayer` to the `mask` property of the foreground view.

https://github.com/TimOliver/TOCropViewController/blob/master/Objective-C/TOCropViewController/Views/TOCropView.m#L217

You could easily change that from a circle to a hexagon in a pinch.

Good luck!
