### ISSUE TITLE
When reset ratio to current ratio, the height is larger than the expectation.

### ISSUE THREAD

**Issue by zhuhao5828** [TimOliver/TOCropViewController#239]
When reset ratio to current ratio, The height is larger than the expectation.
eg:
if current ratio is 1:1
![1x1_1](https://user-images.githubusercontent.com/7801093/35180464-ce124f84-fdeb-11e7-8107-dc15cf2b8506.png)

after reset to square, the height is larger than the width:
![1x1_2](https://user-images.githubusercontent.com/7801093/35180465-e0339cea-fdeb-11e7-810e-256399726bb5.png)

and if current ratio is 3:2
![3x2_1](https://user-images.githubusercontent.com/7801093/35180469-f9e16974-fdeb-11e7-901b-f44b282dddce.png)

after reset to 3:2, the height is also larger than the expectation:
![3x2_2](https://user-images.githubusercontent.com/7801093/35180473-1add7faa-fdec-11e7-837b-768572d741d4.png)

**Comment by TimOliver** [comment]
Hi @zhuhao5828!

Hmm, I'm not sure how to reproduce this. Can you please post the code you've used to set up and present the controller, and then what buttons to tap in order to get this to happen?

I'm assuming this is a problem that's happening if you set a preset aspect ratio, and then hit reset.

**Comment by zhuhao5828** [comment]
Hi @TimOliver 
Just run the example app, then tap '+' to choose a photo with 'CropImage' option, and then tap clampButton and choose 'Original' option, and then you will get this.

Also, if you reset ratio two consecutive times with the same option, you will get this too.

**Comment by SKerencic** [comment]
Hi @TimOliver
any updates on this issue?

@zhuhao5828 
what have i done is i called  [self.cropView setAspectRatio:aspectRatio animated:animated]; two times in 
- (void)setAspectRatioPreset:(TOCropViewControllerAspectRatioPreset)aspectRatioPreset animated:(BOOL)animated

and updated  zoomOut parameter in - (void)setAspectRatio:(CGSize)aspectRatio animated:(BOOL)animated to always be true.

not sure how this will affect any other features, but it looks fine for now

it's just a hack, but it's a start

**Comment by TimOliver** [comment]
Hi folks! I just pushed a new fix to master that should have hopefully fixed it. Please give it a try and tell me what you think. :)

**Comment by TimOliver** [comment]
Gonna close this off now. Please open a new issue if this problem is persisting. :)
