### ISSUE TITLE
TitleLabel not working in swift

### ISSUE THREAD

**Issue by ranhsd** [TimOliver/TOCropViewController#241]
Hi, I tried to set the titleLabel property of CropViewController
when I try to do it I noticed that it's **nil** I tried to find where it is being used in code (CropViewController.swift) but It's not there so I wanted to know if this is supported in swift or not.

Thanks!

**Comment by TimOliver** [comment]
Hi @ranhsd!

Oh dear. I might have forgotten to link up the `titleLabel` to the `CropViewController` wrapper class. 

I'll look into it, but I don't know when I'll have the time. It should be very simple if you want to check it out. :)

**Comment by atistank** [comment]
i'have a same problem, please help us.

**Comment by TimOliver** [comment]
This should be fixed now. `titleLabel` is exposed in Swift, and I fixed an issue where setting `title` in the Swift view controller wouldn't get passed along.
