### ISSUE TITLE
When the image is cropped too narrow, the cropview goes offscreen

### ISSUE THREAD

**Issue by 23steve** [TimOliver/TOCropViewController#242]
I was using this lib in a childviewcontroller. With UI debugging I could figure out that the frame of the childviewcontroller (the CropViewController) is okay, but it's subviews don't respect it's boundaries and can go offscreen, when cropping a too narrow image. (vertically big, horizontally small)

The bug exists on 
- the latest version, 
- the one on master branch
- on the branches with PRs

I've resolved my problem by simply returning `self.view.bounds` at 
`- (CGRect)frameForCropViewWithVerticalLayout:(BOOL)verticalLayout` in `TOCropViewController.m`.
However, that may not work for every scenario, so did not make a PR.

**Comment by TimOliver** [comment]
Thanks for the issue @23steve!

Hmm, I wonder if this was an edge case that was caused from all of the iPhone X boundary work I did. Can you please attach a screenshot and post any reliable ways of reproducing this? 

Thanks!

**Comment by TimOliver** [comment]
We've had a few more PRs and refinements since this issue, so HOPEFULLY it's fixed. Please open a new issue if the problem still persists. :)
