### ISSUE TITLE
cropViewController.aspectRatioLockEnabled = true does not work

### ISSUE THREAD

**Issue by kornha** [TimOliver/TOCropViewController#246]
Hello, 
Setting  cropViewController.aspectRatioLockEnabled = true does not work as I can click the aspect button and when its disabled chose any image shape. In addition, is there a way I can remove the button from the crop screen?

Thanks!

**Comment by kornha** [comment]
Found it out! cropViewController.aspectRatioPickerButtonHidden = true.

Thanks.

**Comment by TimOliver** [comment]
Haha too easy! :D
