### ISSUE TITLE
Hitting Reset removes the AspectRatioLockEnabled setting

### ISSUE THREAD

**Issue by shudson302** [TimOliver/TOCropViewController#247]
I need to crop an image with a set aspect ratio that the user cannot change.  The code is working properly( I cannot change the aspect ratio ) , however when I hit the reset button, it appears to clear that setting because I can then change the size of the crop box which causes a different aspect ratio.

            var viewController = new TOCropViewController(TOCropViewCroppingStyle.Default, uiimage);
            viewController.AspectRatioLockEnabled = true;
            viewController.AspectRatioPickerButtonHidden = true;
            viewController.CustomAspectRatio = new CGSize(8.0, 7.0);
            viewController.SetAspectRatioPreset(TOCropViewControllerAspectRatioPreset.Custom, true);

**Comment by TimOliver** [comment]
Hi @shudson302! You can use `TOCropViewController.resetAspectRatioEnabled` to ensure the aspect ratio is still locked while doing resets.

Hope that helped!

**Comment by shudson302** [comment]
Yes, setting that to false fixed the issue.  Thank you for your quick reply, love the control!

**Comment by TimOliver** [comment]
Cool! Glad that helped and that you found the library useful! :)
