### ISSUE TITLE
Can we used TOCropViewController  in ContainerView ?

### ISSUE THREAD

**Issue by JayMehta711** [TimOliver/TOCropViewController#251]
I have tried to add TOCropViewCntroller in ContainerView but not get proper output.

`  let vc = TOCropViewController(croppingStyle: .default, image: objImage)
        vc.delegate = self;
        vc.view.translatesAutoresizingMaskIntoConstraints = false
        self.addChildViewController(vc)
        self.addSubview(vc.view, toView: self.ContainerView)`

//addSubview Method Code.
```
func addSubview(_ subView:UIView, toView parentView:UIView) {
        parentView.addSubview(subView)
        
        var viewBindingsDict = [String: AnyObject]()
        viewBindingsDict["subView"] = subView
        parentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[subView]|",
                                                                 options: [], metrics: nil, views: viewBindingsDict))
        parentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[subView]|",
                                                                 options: [], metrics: nil, views: viewBindingsDict))
    }
```
Not getting proper view. Would you please help me for same ?
![simulator screen shot - iphone 8 plus - 2018-02-14 at 15 44 43](https://user-images.githubusercontent.com/6177191/36198964-190695ac-119e-11e8-8a6c-a5b868005d10.png)

**Comment by TimOliver** [comment]
Hi @JayMehta711!

Erm, I never really intended for the controller to be embedded in other controllers. I only designed it to be presented on it's own either modally, or in a `UINavigationController`.

That being said, the `CropViewController` controller nests a `TOCropViewController` object in there out of Swift-based necessity. In that case, all of the view controller events and properties from the outmost controller are forwarded to the internal controller.

You'll have to do the same. It's probably not enough to simply embed the view in another controller; but you need to make sure there is a proper parent/child controller setup there.

Good luck!
