### ISSUE TITLE
[!] Unable to find a specification for `CropViewController`

### ISSUE THREAD

**Issue by chetandobariya** [TimOliver/TOCropViewController#252]
I can not install cocoa pods for the swift project.

it shows following error in a terminal window.

[!] Unable to find a specification for `CropViewController`

**Comment by GrodFor** [comment]
Same problem

**Comment by TimOliver** [comment]
Have you folks run a `pod repo update` lately?

**Comment by frenchfalcon** [comment]
@TimOliver fixes the issue thank you

**Comment by TimOliver** [comment]
Glad I could help! 😆
