### ISSUE TITLE
iphone x Cropping 

### ISSUE THREAD

**Issue by rakeshkathoju** [TimOliver/TOCropViewController#256]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> I had an issue with iPhoneX can you please see attached video .
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**:
    I had an issue with iPhoneX  can u please check attached video 

[Video_file.zip](https://github.com/TimOliver/TOCropViewController/files/1788754/Video_file.zip)

>
---

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
What model of iOS device were you testing on?
If using CocoaPods, which version of CocoaPods are you on?

## Goals

What is the outcome result you want to achieve with this library?

## Expected Results

What did you expect to happen?

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

**Comment by TimOliver** [comment]
Hi @rakeshkathoju!

Sorry you're having issues with the controller. I watched the video, but there's no way for to be able to help from that. I don't know what your view controller hierarchy is like, or how the view is being presented.

If you can, please either attach a sample app with the reproducible error here, or at least write a detailed breakdown of how your app works.

In any case, I'm very strapped for free time at the moment, so I can't promise any time to look at it. If you can try and debug the issue yourself, that would be very helpful.

**Comment by TimOliver** [comment]
Closing this one. There's not a lot I can do without a sample app or more information.
