### ISSUE TITLE
Swift 4.1 support 

### ISSUE THREAD

**Issue by Mahan3340** [TimOliver/TOCropViewController#261]
## Hardware / Software MacBook Pro MPTR2 OS X 10.13.4

Which version of the library were you using? Latest
Which version of iOS are you running? Latest IOS 11.3
What model of iOS device were you testing on? iphone 6s
If using CocoaPods, which version of CocoaPods are you on? Latest

## Goals

What is the outcome result you want to achieve with this library?
the lib is working just fine

## Expected Results

What did you expect to happen?
the lib is working just fine

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)

the lib is working just fine

## Steps to Reproduce

What are the steps needed to reproduce this issue?

there are just some warnings which @FedericoSub also mentioned about 
If this bug was caused by a specific image, please post it here.

**Comment by FedericoSub** [comment]
Hi, after upgrade Xcode to 9.3 I receive Warnings using TocropViewController with this message :

/Users/FedericoVivian/Documents/Documenti personali/CSMApp/Pods/CropViewController/Objective-C/TOCropViewController/TOCropViewController.m:458:1: Implementing deprecated method
-------
//TODO: Deprecate iOS 7 properly at the right time
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration
{
--------

I tried with pod update so I have last release but same error.
Any suggest?
thanks

**Comment by TimOliver** [comment]
We'll follow this up in #262 :)
