### ISSUE TITLE
Problem with Swift 4.1

### ISSUE THREAD

**Issue by FedericoSub** [TimOliver/TOCropViewController#262]
- [ x] I have read this issue template and provided all possible information. 
- [x ] I'm using CocoaPods and have run `pod update` before filing this issue.

## Hardware / Software

Which version of the library were you using?
Which version of iOS are you running?
11.3
What model of iOS device were you testing on?
Iphone 7,8,X
If using CocoaPods, which version of CocoaPods are you on?

Hi, after upgrade Xcode to 9.3  I receive Warnings using TocropViewController with this message :

/Users/FedericoVivian/Documents/Documenti personali/CSMApp/Pods/CropViewController/Objective-C/TOCropViewController/TOCropViewController.m:458:1: Implementing deprecated method

//TODO: Deprecate iOS 7 properly at the right time
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
•(void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration
 {

I tried with pod update so I have last release but same error.
 Any suggest?
 thanks

**Comment by FedericoSub** [comment]
Sorry am I the only one with this problem?
How Can I solve the warning ?

thanks

**Comment by TimOliver** [comment]
Oh dear. The Xcode macros for suppressing deprecation notices must have changed. I'll have to look into it.

**Comment by TennisDrum** [comment]
I've just run into this too. Xcode 9.3.1.  It's just a warning - so code is working for testing. Thanks for the help.

**Comment by TimOliver** [comment]
The macros seem like they're being ignored. I changed them to something else. Hopefully that fixed it.
