### ISSUE TITLE
UIImage+CropRotate issue (Method definition for 'croppedImageWithFrame:angle:circularClip:' not found)

### ISSUE THREAD

**Issue by salvasp** [TimOliver/TOCropViewController#268]
- [x] I have read this issue template and provided all possible information. 
- [ ] I'm using CocoaPods and have run `pod update` before filing this issue.

I'm using the master branch at commit d42ae60a7682e6a1d1fe75b811ed6e0d59152207 (May 2, 2018)
> ## Issue Types
>
>Code bug
>**Method definition for 'croppedImageWithFrame:angle:circularClip:' not found**
---

There is an issue in UIImage+CropRotate

UIImage+CropRotate.h declare
`-(nonnull UIImage *)croppedImageWithFrame:(CGRect)frame angle:(NSInteger)angle circularClip:(BOOL)circular;`

UIImage+CropRotate.m implements
`- (UIImage *)croppedImageWithFrame:(CGRect)frame angle:(NSInteger)angle circularClip:(BOOL)circular scale:(CGFloat)scale`
scale parameter added

The scale parameter is never passed in TOCropViewController.h and TOActivityCroppedImageProvider.h

UIImage+CropRotate.m (croppedImageWithFrame) uses
self.scale (UIImage.scale) when UIGraphicsBeginImageContextWithOptions
and scale (parameter) in return <-- is here the bug?

**I removed the  _scale:(CGFloat)scale_ parameter and replaced in return scale with self.scale or croppedImage.scale   (?)**
Seems to work with rectangular and circular crop (Simulator)

PS. The example crashes with
This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryAddUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by MiMo42** [comment]
+1
Needs fix

**Comment by HDClear** [comment]
This issue has been resolved in the new version.

**Comment by MiMo42** [comment]
You added the definition
- (nonnull UIImage *)croppedImageWithFrame:(CGRect)frame angle:(NSInteger)angle circularClip:(BOOL)circular
But now there is no implementation for it.
This is why compiler throws a warning and there are crashes at runtime .
If you define the method in a Header File, you have to provide a method in your implementation that matches exactly the parameter list that has been defined in H-File. 

Your Implementation (in .m-file) looks like this:
- (UIImage *)croppedImageWithFrame:(CGRect)frame angle:(NSInteger)angle circularClip:(BOOL)circular scale:(CGFloat)scale
There is an additional scale parameter.
But there is no definition in H-File for that,

**Comment by malandiwang** [comment]
Needs fix

**Comment by TimOliver** [comment]
Ah, this might be the result of another PR that was filed earlier. It's probably a really easy fix.

I can do it when I get some time, but if anyone else feels up to it, please file a PR. :)

**Comment by YSDC** [comment]
Hi,
I was looking for a crop image library, and your projects looks great. But as a first experience, having the application crash doesn't make me very confident to add it to our company applications.

Do you know when the master branch will be updated in order to test it?

**Comment by TimOliver** [comment]
Hi folks! After 5 months of moving to another country, I'm finally back up to full running capacity for my libraries.

I can't believe everything about this issue. I can't believe someone filed a PR with such a flagrant crash, I can't believe that I didn't catch it myself, and I can't believe how everyone reported it and asked for it to be fixed, but even after I asked for a PR, it took weeks before someone actually filed one. 

Anyway, it's fixed, I now have a computer again, and once I've thoroughly tested this library with all of the other PRs I've merged, I'll bump the CocoaPods version.

I'll be stepping back and having a think on how to better go about building some unit tests for this library so it's easier to catch these things in future.

**Comment by TimOliver** [comment]
@YSDC Thanks! Glad you like the look of the library. It's fixed on master now, but I'm still testing it for issues.

It's awesome that your company is considering integrating it, but please keep in mind, this is a project that I work on in my free time, so I can't promise any support. The library is open source though, so if it crashes again, you can always get in there and fix it yourself. :)

Let me know how you go with it!
