### ISSUE TITLE
iOS 10 the toolbar misplaced & status bar disappear

### ISSUE THREAD

**Issue by whitefox0102** [TimOliver/TOCropViewController#271]
hi

I setup this program in my project

but I have two issues

1. when I run on IOS 10 have this issue
![2018-05-10 10 16 34](https://user-images.githubusercontent.com/19722149/39848742-4a5d9b66-543b-11e8-8ddf-b50bec1309b6.png)

the toolbar misplaced even I run iPhone 6 or plus

2.after I croped the photo, the top status bar is disappear.
  even run another device 
![2018-05-10 10 16 50](https://user-images.githubusercontent.com/19722149/39848814-c1087060-543b-11e8-8de9-f4c289c08242.png)
![2018-05-10 10 16 58](https://user-images.githubusercontent.com/19722149/39848815-c1394064-543b-11e8-842b-cbb84d4d8c07.png)

please help me~~

thanks~

**Comment by TimOliver** [comment]
Oh no! Looks like a bug. I'll have to check it. Thanks for the heads-up!

**Comment by mindgrub-rkoch** [comment]
Any update on this? I'm encountering the issue as well.

**Comment by TimOliver** [comment]
No updates sorry folks! I'm still not in a position to work on my OSS projects for now.

PRs would be greatly appreciated. :)

**Comment by muhlenXi** [comment]
Has this bug been fixed？ Status bar is disappear when capturing image from the camera

**Comment by TimOliver** [comment]
@muhlenXi Please read above. 🙏

**Comment by TimOliver** [comment]
Hi folks! I tried testing the sample app out in the simulator running 10.3, but I couldn't reproduce it.

In any case, I've just released a new version. Please try updating to it (make sure to run `pod spec update` for CocoaPods).

If you're still having the problem in a new version, please open a new issue and give the steps needed to cause this issue happening in the sample app.

Thanks!
