### ISSUE TITLE
After click button done, CropViewController doesn't dismiss.

### ISSUE THREAD

**Issue by petrovRV** [TimOliver/TOCropViewController#273]
Hello. When I clicked button Done, CropViewController doesn't dismiss, instead of I see "action sheet" [shared](https://drive.google.com/open?id=16KULBVbBBA6RN70RagDzkReO0gPyLSG6).
How can I close CropViewController after pressed button "done"?

**Comment by asadqazi** [comment]
I used the latest 2.4 version using cocoapods and still when I press the done button it does not close the crop view controller
