### ISSUE TITLE
Implement localization example

### ISSUE THREAD

**Issue by Rob117** [TimOliver/TOCropViewController#280]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

I read the issue submission guide.

I checked closed and existing issues, I could not find this specific one. I combed through the example application and the source code, and I'm still not sure how to _set_ a specific locale. Do you have any guidance for that? Like, when I create the controller, do I just set something equal to "ja"?

**Comment by TimOliver** [comment]
Hi @Rob117!

Languages are controlled by the system language of the device. You can set separate language versions of the simulator to test this concurrently by doing this: https://stackoverflow.com/questions/23110074/how-to-set-specific-language-in-ios-simulator

Hope that helped!

**Comment by Rob117** [comment]
Thank you!
