### ISSUE TITLE
How do I resize the ViewController.

### ISSUE THREAD

**Issue by tejaskutal** [TimOliver/TOCropViewController#281]
Is it possible to resize the TOCropViewController, I need to display two view controllers, with seperate cropping functionality, both consuming half of the screen. I have added a container view, which contains two different view controllers. However when I add TOCropViewController on one of the view controllers, it occupies the entire screen. Any way to fix this?

**Comment by TimOliver** [comment]
Hi @tejaskutal! Sounds like you might need to implement a custom `UIViewController` parent container to handle laying out two instances of `TOCropViewController`. I probably should warn that the library was designed to only every be used in a full-screen context, so it may behave in weird ways.

Good luck!
