### ISSUE TITLE
Implementing deprecated method Warning on Xcode 9.4 and Swift 4.1

### ISSUE THREAD

**Issue by ethanwa** [TimOliver/TOCropViewController#283]
Anyone else seeing this warning `Implementing deprecated method`? Looks like I am getting three of them with Xcode 9.4 and Swift 4.1.

**Comment by MayurTanna1** [comment]
hi if you are getting error at

`self.automaticallyAdjustsScrollViewInsets = NO;`

in "TOCropViewController.m" file


you can use 

UIScrollView *sc = self.view.subviews.firstObject.subviews.firstObject;
 [sc setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentAlways];

i have done the same for this 1 warning

**Comment by TimOliver** [comment]
It looks like Xcode has started to ignore the deprecation warning suppression macro. How inconvenient.

I fixed the ones I could find by replacing them with macros that require a specific minimum iOS version. If you see anymore, please file a PR using the same macro I did.

That'll definitely suppress the warnings, although given how ancient iOS 7 is, it might be best to start refactoring the code to remove all of that legacy code now. 😅

**Comment by Janneman84** [comment]
4 years later and I'm getting the same deprecation warning now. Also I'm getting a warning about 'topLayoutGuide' being deprecated too:

> 'topLayoutGuide' is deprecated: first deprecated in iOS 11.0 - Use view.safeAreaLayoutGuide.topAnchor instead of topLayoutGuide.bottomAnchor

Same file on line 1299

**Comment by lchccieurope** [comment]
@TimOliver can you consider the PR https://github.com/TimOliver/TOCropViewController/pull/542/commits/4d812ae867614f5a5136f698f3694a9a57c122ea

**Comment by lchccieurope** [comment]
Hi @TimOliver,
it's old, but good code,
could you please consider the PR https://github.com/TimOliver/TOCropViewController/commit/4d812ae867614f5a5136f698f3694a9a57c122ea
