### ISSUE TITLE
Force image to square ratio.

### ISSUE THREAD

**Issue by valtambok** [TimOliver/TOCropViewController#29]
Is there a way to force the cropView to be locked at a square ratio (and hide crop/clamp button)?

**Comment by zobnec** [comment]
Yeah.I also want how to lock it!

**Comment by sammy-SC** [comment]
Hello,

check out this fork https://github.com/siong1987/TOCropViewController.

**Comment by TimOliver** [comment]
Thanks a lot for that guys! I've merged that branch in, so locking the crop view to a specific ratio is now possible!
