### ISSUE TITLE
picute is not in right position

### ISSUE THREAD

**Issue by halocq** [TimOliver/TOCropViewController#295]
- [ ] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

---
like this
> ## For CocoaPods Users

![image](https://user-images.githubusercontent.com/11287047/43876637-93ba6a62-9bc8-11e8-8e76-df90eed8792b.png)

**Comment by TimOliver** [comment]
Hi! This should have been fixed. Can you please pull the latest from master and check if the issue is in there too?

**Comment by halocq** [comment]
Yes, thanks, it's fixed. But croped image have a black line in the top. 
![image](https://user-images.githubusercontent.com/11287047/43879936-ea1401ba-9bd8-11e8-9aea-d2176cd031b1.png)

**Comment by TimOliver** [comment]
Oh dear! Yep, I tested it out and discovered there's some imprecision in how the final cropping region is calculated.

I just pushed a potential fix to `master`. Please try it and see if that fixes it! :)

**Comment by TimOliver** [comment]
Okay. I think this is fixed now. Closing it off.

If you can still replicate it, please open a new issue. :)
