### ISSUE TITLE
Wrong animation after rotation when croprect and angle are predefined

### ISSUE THREAD

**Issue by lukasMH** [TimOliver/TOCropViewController#299]
## Hardware / Software

Version of library: 2.3.7
iOS version: 11.4
iOS device: X
CocoaPods version: 1.5.3

## Goals

- fix rotating animation when croprect and angle are predefined

## Expected Results

- image should be rotated to proper position after tap on rotate button

## Actual Results

- image is rotated, but after animation crop rect is resets to full image crop
- it usually happens when rotation ends at angle 0

## Steps to Reproduce

screen record:
https://www.dropbox.com/s/yt6tpa8ezwyh77f/TOCropViewController_bug.mov?dl=0

how to reproduce issue:
- set initial angle
- set initial cropRect
- open image in CropViewController
- rotate (1, 2, 3 times)

same behaviour is in your example when I uncommented following lines and change imageCropFrame:
cropController.angle = 90; // The initial angle in which the image will be rotated
cropController.imageCropFrame = CGRectMake(100,100,2548,4088); //The initial frame that the crop controller will have visible.

**Comment by TimOliver** [comment]
Hi @lukasMH!

Thanks so much for the bug report and the detailed reproduction steps.

I managed to reproduce the issue here, and I THINK I managed to fix it.

Can you please pull latest from `master` and see if that's fixed it for you?

Thanks!

**Comment by lukasMH** [comment]
Hi, looks like it is fixed 👍
just increase pod version please, because in pods project there is still previous version
thank you! :)

**Comment by TimOliver** [comment]
Yay! No problems! I'll cut a new release version as soon as I can. Thanks for that!  :)
