### ISSUE TITLE
Seems localizable does not work.

### ISSUE THREAD

**Issue by ZuYuanZhou** [TimOliver/TOCropViewController#30]

**Comment by TimOliver** [comment]
Seems good to me!

If there's a specific language not working for you, let me know!

![simulator screen shot 19 dec 2015 11 10 36 pm](https://cloud.githubusercontent.com/assets/429119/11913654/c97120ee-a6a5-11e5-857e-3fcad7e244b6.png)

**Comment by Sander-Kornev** [comment]
I faced with the same problem.
Currently I am adding Arabic localization.
![screen shot 2016-02-10 at 12 55 42](https://cloud.githubusercontent.com/assets/3295273/12945357/9c17c4e4-cff5-11e5-97cd-9989f4a5ef93.png)
iOS 9, iPod touch, current language is Arabic, status bar is flipped and title of navigation bar is localized, but buttons on TOCropToolbar aren't localized.

In your screenshot did you try your project with cocoapods?

**Comment by adrianodiasx93** [comment]
@TimOliver, it seems that Portuguese-BR is not working.
I am using the lib in my swift project as a carthage dependency.

**Comment by TimOliver** [comment]
Hmm, are you able to confirm it's not working in the demo app? I wonder if this is a localization problem, or a dynamic framework problem with Carthage.
