### ISSUE TITLE
TOCropViewController needs to be updated for Swift 4.2 compatibility.

### ISSUE THREAD

**Issue by ethanwa** [TimOliver/TOCropViewController#300]
TOCropViewController needs to be updated for Swift 4.2 compatibility. I'm getting a request to convert to it in Xcode 10 GM with changes requested.

**Comment by TimOliver** [comment]
What? `TOCropViewController` is an Objective-C library. 🤔

I noticed you were spamming the same message to a lot of other repos. Please go back and make a real issue with what actually needs updating. 🙏
