### ISSUE TITLE
Retriewe PHasset or NSURL once image is cropped

### ISSUE THREAD

**Issue by jeromeDms** [TimOliver/TOCropViewController#304]
Hi All
I'm using this cropper in my objective C project.
It is working perfectly. My problem is once the image is cropped, user can click the image to make it fullscreen, for this I'm using ASMediaFocusManager as the full screen image viewer.
ASMediaFocusManager requires an URL (distant or local) to display the image in full screen mode.
One method would be to use PHAsset to get a local URL of the cropped image, but I do not want to save the cropped image into the photo library.
Any help would be greatly appreciated.
Thanks to all

**Comment by TimOliver** [comment]
Thanks for the issue folks!

Umm, I think this is a little out of scope for this library. This library only outputs a `UIImage` instance, and then returns responsibility back to your app to handle it. It doesn't save the image to disk, so there's no URLs on this end.

For apps that need a local URL, you could save a copy of the image to your `tmp` directory, which is periodically cleaned, so you don't have to care too much about disk space. 

But if you need it to be a URL for a third party library, I'd definitely recommend trying to file a PR with that library to allow `UIImage` objects. Saving to disk and reading back again will most likely result in a loss of quality and overhead.

I don't think there's anything we can do on this end, so I'm closing this issue. Good luck!
