### ISSUE TITLE
Remove dimming effect and set initial position of the cropping view.

### ISSUE THREAD

**Issue by andresinaka** [TimOliver/TOCropViewController#310]
First of all @TimOliver thanks for this awesome library! Maybe you or someone else can help me with some questions:

I'm using the library and I couldn't find how to do the following:
1- Avoid the dimming effect. While you are editing the image you can see the whole image and as soon as you stop editing, the image outside of the `cropView` gets dimmed out. Is it possible to disable that dimming? I want to always show the whole image.
2- Is it possible to make the image take the whole height of the screen initially?
3- Is it possible to set the initial position of the cropView? I want to put a custom (x,y) for the box.

Thanks again for this awesome work!!

**Comment by TimOliver** [comment]
Hi @andresinaka! Thanks a lot! I'm glad you like the library!

1. Someone just filed a PR that lets you remove the translucency effect. You can do this by choosing `cropController.cropView.translucencyAlwaysHidden = YES;` in the very latest version.
2. You can set `cropController.imageCropFrame` to set an initial frame (In the coordinate space of the image) that the box will be zoomed in.
3. Same as above. The `CGPoint` of `imageCropFrame` handles position, and the `CGSize` handles the size.

Good luck!
