### ISSUE TITLE
Toggle to Hide/Show Grid and Blur Effect

### ISSUE THREAD

**Issue by yudiz-mahavir** [TimOliver/TOCropViewController#311]
- [x] I have read this issue template and provided all possible information. 
- [x] I'm using CocoaPods and have run `pod update` before filing this issue.

## Software

Which version of the library were you using?
**2.3.7 (latest)**

Which version of iOS are you running?
**iOS 12**

What model of iOS device were you testing on?
**iPhone 8**

If using CocoaPods, which version of CocoaPods are you on?
**1.5.3**

## Goals

What is the outcome result you want to achieve with this library?
**There should be an toggle for both Grid and Blur effect if someone wants to hide/show them**

## Expected Results

What did you expect to happen?
1. User can hide/show grid
1. User can turn blur efffect on/off

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)
**There is no objects to manage above requirment**

**Comment by TimOliver** [comment]
Thanks for the PR!
