### ISSUE TITLE
Feature Request minWidth and minHeight

### ISSUE THREAD

**Issue by HerrNiklasRaab** [TimOliver/TOCropViewController#314]
Hello and thanks for the great work you provided!

Is it possible to implement something like minWith and maxWith? Because now a user can crop the image infinit small?

Current user flow:

1. Click on "Choose Image"
2. Croping the image
3. If it is to small for example 200x200 px, a error message is shown, for example:
   "Your Picture is to small, please use a photo with bigger dimensions"
4. Click second time on "Choose Image"
5. Crop image with bigger dimension
6. Done

If it would be possible to declare a minWidth and minHeigt, the flow would be:

1. Click on "Choose Image"
2. Croping the image, with restricted zoom, or show error message in the cropper
3. Done

By the way, we are using this in following flutter plugin: https://github.com/hnvn/flutter_image_cropper/issues/13

Thanks,

Niklas

**Comment by laohanme** [comment]
HI,
There's already an issue tracking that feature request: #46

**Comment by TimOliver** [comment]
Thanks for the issue @HerrNiklasRaab!

And thanks for the follow-up @laohanme! There's already an issue tracking this, so I'll close this one off.

Thanks!
