### ISSUE TITLE
disable the crop box resize

### ISSUE THREAD

**Issue by nivbp7** [TimOliver/TOCropViewController#316]
Hi Tim,
I tried to disable the crop box resize (cropBoxResizeEnabled) by setting it to NO, but can still resize the box with Pan gesture. anyway to disable it?
Thanks!

**Comment by TimOliver** [comment]
Hi @nivbp7!

You're not really supposed to touch the properties of `TOCropView` since they can be modified internally.

It'd probably be easier for you to set a custom aspect ratio and then set that one to be locked. :) Let me know if that helps!

**Comment by behzadardehei** [comment]
Hi @TimOliver 
Can you help me, I want to create custom aspect ration then I lock this.

**Comment by behzadardehei** [comment]
Hi @TimOliver
Can you help me, I want to set aspectRatioPresent to .preset16x9 then I lock this.
I want to disable aspect ratio box but I can't.
Thank you.

**Comment by behzadardehei** [comment]
Hi @TimOliver
Can you help me, I want to set aspectRatioPresent to .preset16x9 then I lock this.
I want to disable aspect ratio box but I can't.
Thank you.

**Comment by TimOliver** [comment]
Closing this off now. Thanks for the issue!

**Comment by nvdmcs** [comment]
CropView Controller

 fileName: ToCopView.m ——————
 line 247//    [self.scrollView.panGestureRecognizer requireGestureRecognizerToFail:self.gridPanGestureRecognizer];
line 248//    [self addGestureRecognizer:self.gridPanGestureRecognizer];
