### ISSUE TITLE
Compile Error of CropViewController.swift after manual implementation

### ISSUE THREAD

**Issue by hendrik244** [TimOliver/TOCropViewController#317]
- [x] I have read this issue template and provided all possible information. 
- [ ] I'm using CocoaPods and have run `pod update` before filing this issue.

---
> **Please remove this section of the issue template before filing your issue.**
>
> Thanks for considering filing an issue! Before proceeding, please consider
> the type of issue you're filing and make sure to supply the proper details 
> needed for it! :)
>
> Please note that your issue may be closed without review if you do not supply 
> the information that is requested here. Since this library is done as a side-project 
> outside of work hours, please understand that a timely response cannot be guaranteed. ;)
>
> ## For CocoaPods Users
>
> Before filing a bug report, please make sure you are using the latest version
> of CocoaPods (`gem install cocoapods`), and the latest version of this 
> library (`pod repo update`).
>
> Support for CocoaPods-related issues is not provided unless you confirm both of 
> these points in your submission.
>
> ## Issue Types
> 
> **Questions**: Please check the closed issues to see if it's already been asked
> before.
>
> **Feature Request**: Please fill in just the first two sections. Please be as thorough 
> as possible and explain how you would expect this feature to work both visually, and from an
> API perspective.
>
> **Bugs**: Please be as thorough as possible when describe the bug you've discovered. If it's 
> a visual bug, please add a screenshot. If it's an animation bug, please provide a recording 
> of the bug in action.
>
>
---

## Hardware / Software

Which version of the library were you using?
--> The current one.
Which version of iOS are you running?
--> iOS 12.1
What model of iOS device were you testing on?
--> iPhone 7
If using CocoaPods, which version of CocoaPods are you on?
--> I don't take use of CocoaPods.

## Goals

What is the outcome result you want to achieve with this library?
--> Just crop a picture after choosing it from the libary.

## Expected Results

What did you expect to happen?
--> Implementation without any problems :)

## Actual Results

What happened instead?  (Please attach a screenshot/screen recording if possible)
--> When I tried to implement this libary in my swift project by following the insturcations, I got this error list:
<img width="433" alt="bildschirmfoto 2018-11-12 um 08 24 14" src="https://user-images.githubusercontent.com/33331414/48332908-d67e2500-e655-11e8-89a2-488f8135eb39.png">

Even though I also copied the Objective-C Objects:
<img width="378" alt="bildschirmfoto 2018-11-12 um 08 24 35" src="https://user-images.githubusercontent.com/33331414/48332944-f877a780-e655-11e8-96ee-4e5cfbb2ced2.png">

I also checked the Build Phases of the project and added some files to the Compile Source of it...
Still the same error.
Would be amazing, if somebody can help me with this one.

## Steps to Reproduce

What are the steps needed to reproduce this issue?
If this bug was caused by a specific image, please post it here.

Just a manual implementation in a swift project.

**Comment by hendrik244** [comment]
I fixed it myself. The Objective-C Bridging Header File was missing.

**Comment by TimOliver** [comment]
Haha good to hear you fixed it!

**Comment by unixzilla** [comment]
> I fixed it myself. The Objective-C Bridging Header File was missing.

[https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift](url)
