### ISSUE TITLE
'id' is disallowed with ARC and frame  not working production build

### ISSUE THREAD

**Issue by narendrabro4u** [TimOliver/TOCropViewController#322]
*implicit conversion of 'TOCropViewCroppingStyle' (aka 'enum TOCropViewCroppingStyle') to 'id' is disallowed with ARC
*Redefinition of enumerator 'TOCropViewCroppingStyleCircular
*Redefinition of 'TO_CROP_VIEW_RESOURCE_BUNDLE_FOR_OBJECT' 
when archive project

**Comment by TimOliver** [comment]
Sorry for the delay!

Um, sounds like you haven't integrated the project properly. If `TO_CROP_VIEW_RESOURCE_BUNDLE_FOR_OBJECT` is getting defined twice, it sounds like there's two copies of the framework in your app.

Please remove the entire framework from your app, and try integrating it again. If you're still having problems, please create a new issue with all of the steps you took to get that error. :)
