### ISSUE TITLE
Done button does not dismiss

### ISSUE THREAD

**Issue by asadqazi** [TimOliver/TOCropViewController#334]
I used the latest 2.4 version using cocoapods and still when I press the done button it does not close the crop view controller

**Comment by ay8s** [comment]
@asadqazi You have to dismiss TOCropViewController yourself.

**Comment by TimOliver** [comment]
Exactly. Thanks for the clarification @ay8s!

A few people have commented on this, so I might need to make it more explicit.

**Comment by pawargb** [comment]
cropViewController.dismiss(animated: true, completion: nil)
I wrote above line in _didCropToImage_  from **CropViewControllerDelegate** delegate and fixed the issue
