### ISSUE TITLE
Crop image frame is not in center when toolbar is top

### ISSUE THREAD

**Issue by sesang06** [TimOliver/TOCropViewController#335]
![simulator screen shot - iphone xr - 2019-02-18 at 16 02 14](https://user-images.githubusercontent.com/18592095/53058298-dbc0fa80-34f5-11e9-991a-9ab95cd8eac9.png)

When I put toolbar at top, the default crop frame is not in center, but slightly below.

When I used your 2.0.1 version, it was exactly at center, but when I update it to 2.4.0 version,
the cropped image get down.

**Comment by sesang06** [comment]
Also, when I positioned the toolbar at top, I can't drag the crop frame upto the bottom of the toolbar.

**Comment by TimOliver** [comment]
Thanks so much for the PR!
