### ISSUE TITLE
Box is still resizable 

### ISSUE THREAD

**Issue by Ranaasad113** [TimOliver/TOCropViewController#341]
`.        self.cropViewController=CropViewController(image: chosenImage)
            self.cropViewController?.customAspectRatio = CGSize(width: 1, height: 1)
            self.cropViewController?.aspectRatioLockEnabled=true
            self.cropViewController?.resetAspectRatioEnabled=false`
After that still box is resizable??

**Comment by raullermen** [comment]
try add `self.cropViewController?.aspectRatioLockDimensionSwapEnabled = true`

**Comment by TimOliver** [comment]
Hi @Ranaasad113! I just tested that and this seems to be working fine.

Yes, the box is still resizable, but it is locked to the aspect ratio. The box still remains a square, but you can zoom in on a specific area. You can also revert this by pinching out.

If you're after a specific effect, you might need to modify this library yourself to change that behaviour. If it is an effect you think this library could use, please create a new issue documenting exactly what you want to see.

Thanks!

**Comment by AwaisFayyaz** [comment]
I am using this code and Box is not resizable. i wanted it to be square only and its working perfectly fine.

cropVC = TOCropViewController.init(image: image)
cropVC.delegate = self
cropVC.setAspectRatioPresent(.presetSquare, animated: true)
cropVC.aspectRatioLockEnabled = true
present(AccountSettingsVC.cropVC, animated: true, completion: nil

Thanks Tim Oliver. Save me a lot of development Time.
