### ISSUE TITLE
ERROR ITMS-90535 while uploading app to iTunes Connect

### ISSUE THREAD

**Issue by mohamadqanbari** [TimOliver/TOCropViewController#345]
When uploading my app to App Store Connect, i got this distribution error:

ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/kipo.app/Frameworks/TOCropViewController.framework/TOCropViewControllerBundle.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

I'm using:
cocopods TOCropViewController 2.4.0
xcode 10.2 beta

**Comment by TimOliver** [comment]
Oh dear! Thanks for the heads-up! I'll see if I can fix that.

**Comment by mohamadqanbari** [comment]
This issue occurred in Xcode 10.2 beta.
in Xcode 10.2 final app successfully uploaded into App Store Connect.
