### ISSUE TITLE
Lock aspect ration but allow user to flip between landscape and portrait

### ISSUE THREAD

**Issue by DuncanACampbell** [TimOliver/TOCropViewController#35]
Hey!  Awesome view controller!  It's exactly what I'm after so thank you.

I have a question - I want my users to be able to crop their photos at a locked aspect ration of 4:3.  HOWEVER, they should be able to take any size of photo and choose to either crop it at 4:3 or 3:4. 

i.e. the photo maybe a landscape photo, but they want to crop out a portrait-shaped section with aspect ration 3:4.  Equally, they may want to crop out a landscape-shaped section with aspect ration 4:3.  

Does your library allow this?  Or you have any code which might let me do this? 

Thanks so much!

**Comment by TimOliver** [comment]
Hi Duncan!

Thanks a lot! I'm glad you've found my cropper view controller to your liking! :)

Hmm... that's an interesting scenario. Sadly, at the moment, it doesn't allow any explicit option to choose between 4:3 or 3:4 mode; it automatically picks the appropriate option depending if the image is taller or wider.

It should be relatively trivial to expose that setting as a configurable property of the library. Feel free to give that a shot and let me know how you go! :)

-Tim
