### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by NagamaniSeken** [TimOliver/TOCropViewController#351]
Help me how to change localization according to my application language settings

**Comment by TimOliver** [comment]
Hi @NagamaniSeken!

Um, I don't know anything about your setup or the language you want to support, so there's not a lot I can do to help, sorry!

Please go back and update this issue with more information on what you're trying to do here. Thanks! :)

**Comment by TimOliver** [comment]
Closing this off due to inactivity. Please open another issue if you're still having trouble with this!
