### ISSUE TITLE
CropViewController 2.5.0 not pushed to CocoaPods

### ISSUE THREAD

**Issue by sjrmanning** [TimOliver/TOCropViewController#352]
https://cocoapods.org/pods/CropViewController — TOCrop... is updated but the Swift version is still at 2.4.0. Any chance we could get this updated? :)

**Comment by TimOliver** [comment]
Hi Simon!

Oh dear! You're right! I'm not sure how that happened. There must be a bug in my deploy script.

I just pushed v2.5.0 of `CropViewController` now. Can you confirm you can see it on your end?

Thanks!

**Comment by sjrmanning** [comment]
Got it! Thanks Tim! ☺️
