### ISSUE TITLE
Resize Image with aspect ratio

### ISSUE THREAD

**Issue by VivekVithlani** [TimOliver/TOCropViewController#355]
Hello,

This is awesome controller 🥇 , Thank you very much for creating this controller.

Can you please add/update some functionality  in your controller ?

I need to resize image as per given aspect ratio size.
Example -  if I set aspect ratio size is 300x300 / 1080 x 720 then image will resize and get exact size of image which is given aspect ratio.

Thank you,
Vivek.

**Comment by TimOliver** [comment]
Hi @VivekVithlani! Thanks a lot! I'm glad you like this controller!

Hmm, you can set custom aspect ratio sizes. Can you please give me a picture example of what you're trying to achieve?

Thanks!

**Comment by vijaypatidar2102** [comment]
Is the custom aspect ratio can be made fixed so the user can't change this but can zoomIn and zoomOut ?

**Comment by TimOliver** [comment]
@vijaypatidar2102 Yep! That should be possible. :)

This thread is a bit outdated now, so I'm going to close it off. If you have further questions, please open a new issue. Thanks!
