### ISSUE TITLE
Support for the Swift Package Manager

### ISSUE THREAD

**Issue by OscarGorog** [TimOliver/TOCropViewController#359]
Is support for Xcode 11's "Swift Package Manager" coming?

Thanks

**Comment by TimOliver** [comment]
One of the SPM engineers showed me how to create packages for Objective-C libraries in the labs at WWDC last week. I'd probably need to play with it more considering this library has two different types of frameworks in it.

No plans for now. Maybe when Xcode 11 is closer to GM.

**Comment by OkiRules** [comment]
Ok great!

--
Oscar Gorog

**Comment by OkiRules** [comment]
Any update on this?

**Comment by TimOliver** [comment]
Nope! Very busy at the moment. Sorry!

**Comment by ethanwa** [comment]
I second this request. Thank you!

**Comment by TimOliver** [comment]
Sorry folks. I just tried to add SPM support to [my latest library](https://github.com/TimOliver/TOSegmentedControl) and [failed miserably.](https://stackoverflow.com/questions/57950089/creating-new-swift-package-header-not-found) 

I have no idea what to do when there are different levels of headers as it doesn't look like there's an easy way to do Objective-C bridging.

This task is probably at least a day of poking the repo trying to make it work, and I simply don't have the time for that (especially if there's no guarantee of it working).

If anyone's had experience making Swift Packages for Objective-C libraries, helping me out here would be very much appreciated.

Thanks!

**Comment by sauravm97** [comment]
Looks like you managed to partially solve the issue you were having. Any updates?

Thanks

**Comment by TimOliver** [comment]
[There's a PR in progress](https://github.com/TimOliver/TOCropViewController/pull/391). But I want to work out how to integrate it without having to do anything totally crazy like re-organizing files, or using relative file paths.

Please feel free to help!

**Comment by TimOliver** [comment]
Hey folks! Long time no see! Thanks to @simone-gasparini who kickstarted adding SPM support, I was since able to learn a little more about how to integrate Objective-C libraries into SPM, so I THINK we've managed to more or less get it all working now.

I just merged a PR into `master` that adds `Package.swift` and the necessary symlinks to expose all of the header files.

Please give it a try, and let me know if that's actually working for you. Or if there's something we're still missing.

Thanks!

**Comment by ethanwa** [comment]
Sweet thanks! I'll give it a shot and let you know if we run into issues.

**Comment by ethanwa** [comment]
Here's an issue I am running into while trying to add the `master` branch:

<img width="531" alt="Screen Shot 2020-05-20 at 12 26 16 AM" src="https://user-images.githubusercontent.com/1653780/82404991-ad9bd480-9a30-11ea-9ba7-255a5255584c.png">

**Comment by TimOliver** [comment]
Oh wow! That was fast! Thanks for the feedback @ethanwa!

Aha, I think I found the problem. The Swift target was set to import all files in its folder, which included a C `.h` framework header.

I've changed it to only bring in the needed Swift files now, so HOPEFULLY it should work now.

Please give it another shot. :)

**Comment by ethanwa** [comment]
Now it builds, but I am getting the following warning:

<img width="823" alt="Screen Shot 2020-05-20 at 1 15 02 AM" src="https://user-images.githubusercontent.com/1653780/82407533-6107c780-9a37-11ea-9145-99628e7856c0.png">

**Comment by TimOliver** [comment]
Yay! At least it's building now. :D

Hmm, okay. I tried excluding the Supporting folder now (That plist is for the dynamic framework and isn't needed here). 

Hopefully trying it once more will do the trick. :)

**Comment by ethanwa** [comment]
Still getting the Warning.

**Comment by TimOliver** [comment]
Hmm.

Okay, I refactored `Package.swift` to explicitly disregard the folder holding the plist, and tested it in a sample app with no issues.

Give it a try now. If it's still happening, I'm not sure what else it could be.

**Comment by ethanwa** [comment]
Looks like that caused `#import <MBProgressHUD/MBProgressHUD.h> file not found` now.

**Comment by TimOliver** [comment]
Um hmm. That's not a dependency of this library so it shouldn't be related.

**Comment by ethanwa** [comment]
Sorry my fault, you're right. But I am getting a second Error `Could not build Objective-C module 'TOCropViewController'` which may be causing that error to occur in my Bridging Header.

**Comment by TimOliver** [comment]
Hmm. Okay. I can’t replicate that over here (Putting it into a sample app, it worked fine for me), so I’m at a loss.

Can you please describe how you’re importing the library? Have you put the headers in your bridging file?

**Comment by ethanwa** [comment]
I do have a Bridging Header file but it doesn't have anything about TOCropViewController in it. I am adding both Swift and Objective-C targets when adding this Package.

It actually looks like the error is in the Bridging Header file for another Package I am using for SwiftTheme. Here are some screenshots:

<img width="699" alt="Screen Shot 2020-05-20 at 1 44 22 PM" src="https://user-images.githubusercontent.com/1653780/82479211-11111b00-9aa0-11ea-8a39-66d80c4563e7.png">

<img width="690" alt="Screen Shot 2020-05-20 at 1 44 56 PM" src="https://user-images.githubusercontent.com/1653780/82479283-2b4af900-9aa0-11ea-98db-98721e0f86da.png">

<img width="823" alt="Screen Shot 2020-05-20 at 1 44 31 PM" src="https://user-images.githubusercontent.com/1653780/82479293-2dad5300-9aa0-11ea-9166-488e97b9dd5f.png">

**Comment by TimOliver** [comment]
Alrighty folks! I just pushed v2.5.3 that officially features SPM support! 🎉

A HUGE thanks to @simone-gasparini for kickstarting the process on this. We got there in the end. 😁

I'm closing this issue now. If you discover anything broken in the SPM support, please open a new issue.

One final thing. If you're using this library in a commercial capacity, please consider donating or subscribing to it. This project is something I do in my free time for now, but I'm hoping I can eventually do this stuff full-time. Thanks! ❤️
