### ISSUE TITLE
Toolbar at top

### ISSUE THREAD

**Issue by Urkman** [TimOliver/TOCropViewController#36]
Is there an easy way to have to toolbar to top?

**Comment by TimOliver** [comment]
Sadly not. The toolbar is currently only configured to display along the bottom, or along the side when the view controller's view is wider than taller.

It shouldn't be too hard to add though. If you'd like to create that, I'm glad to accept pull requests! :)

**Comment by Urkman** [comment]
I created a pull request... Just take a look
