### ISSUE TITLE
Always get stuck on Xcode 10.12.1 for release building

### ISSUE THREAD

**Issue by melote** [TimOliver/TOCropViewController#363]
I used the 2.5.0 and 2.5.1 vesion of CropViewController for swift, Always get stuck on Xcode 10.12.1 for release building, cannot find why.
<img width="657" alt="WX20190709-123922@2x" src="https://user-images.githubusercontent.com/6263648/60859867-a0299180-a246-11e9-9b8e-20fd31c69ccb.png">

**Comment by TimOliver** [comment]
Hi @melote!

Oh dear! Er, I have no idea. An Xcode build should never hang. Are you sure it never progresses?

Can you share some more information? How are you integrating `CropViewController` into the project. And why do you have over 999 build warnings? ;)

**Comment by melote** [comment]
Never mind, it seems the Xcode bug, by the way, all of warnings is about the nullable things, no worries.

**Comment by TimOliver** [comment]
Haha cool! Good to hear you were able to work out what the problem was!

Haha ahhh okay. I've worked on projects with that many warnings before as well. The struggle is real. XD
