### ISSUE TITLE
How to create original done button

### ISSUE THREAD

**Issue by muranobu** [TimOliver/TOCropViewController#364]

**Comment by muranobu** [comment]
I have solved the problem myself.

**Comment by twinkalGSensussoft** [comment]
How you have done this? Can you please give explanation here? @ muranobu

**Comment by NAOYA-MAEDA-APP** [comment]
Hi, Sample code is here.

1. Create original cropViewController.
```
let cropViewController = CropViewController(image: OriginalImage)
```

2. Add cropViewController to Container View
```
self.addChild(cropViewController)
self.cropContainer.addSubview(cropViewController.view)
```

3. Adjust cropViewController frame.
```
cropViewController.view.frame = CGRect(x: self.cropContainer.frame.origin.x, y: self.cropContainer.frame.origin.y, width: self.cropContainer.frame.width, height: self.cropContainer.frame.height)
```

3. If you want to hide default toolbar, you must below code.
```
cropViewController.toolbar.isHidden = true
```

4. Display cropViewController.
```
cropViewController.didMove(toParent: self)
```

5. Define original done action and call doneButtonTapped!().
```
@IBAction func cropDoneButtonTUP(_ sender: UIButton) {       
      self.cropViewController.toolbar.doneButtonTapped!()
    }
```

**Comment by twinkalGSensussoft** [comment]
What if I don't want only 90-degree rotation?. I want to add a rotation gesture to it, is it possible? If yes then please help me out.
thanks in advance.
