### ISSUE TITLE
Doesn't work on iOS 13.1 

### ISSUE THREAD

**Issue by yh101** [TimOliver/TOCropViewController#368]
After selecting a photo, only black empty image appears in cropping view. (tested on 2.4.0, swift 5)

**Comment by TimOliver** [comment]
Thanks for the feedback! I don’t have any time to investigate right now so any help in diagnosing the issue would be appreciated!

**Comment by kiransarvaiya** [comment]
TimOliver I have one solution but just am testing final once

**Comment by rodmaz** [comment]
This seems to be an issue w/ permissions.

```
createDataWithMappedFile:1508:  'open' failed '/var/mobile/Media/PhotoData/CPLAssets/group498/E850D458-F829-4B19-8FBF-95D6F6CC34BA.HEIC'	error = 1 (Operation not permitted)
```

Do you see the same logs?

**Comment by OkiRules** [comment]
This is not an issue with the CropViewController. It is a permission issue with iOS. You now manually have to request access to the photo library otherwise you will be returned a black image.

**Comment by rodmaz** [comment]
My app does have full album permission. This does not seem to be the case.

**Comment by OkiRules** [comment]
It works for me. Can you provide some sample code?

--
Oscar Gorog

**Comment by yh101** [comment]
It works as usual in 13.1 beta2. This issue could be a bug for 13.1 beta 1 only.

I'd like to share more testing info:

(1) My app does not request explicit permission of photo library access.
- https://stackoverflow.com/questions/46404628/ios11-photo-library-access-is-possible-even-if-settings-are-set-to-never
(2) There was no issue on up to iOS 12.4.1 (Latest) - everything has worked out well!
(3) There was no test in iOS 13.0 beta, but I guess there was no problem in version 13.0.
(4) I got the problem in 13.1 beta 1
(5) The problem was fixed in version 13.1 beta 2

**Comment by OkiRules** [comment]
In iOS 13 you now need to request photo access permissions, see my code above.

--
Oscar Gorog

**Comment by yh101** [comment]
Could you please share with me official docu or any info about permission change in iOS 13?

**Comment by OkiRules** [comment]
There is none:(

--
Oscar Gorog

**Comment by ethanwa** [comment]
I'm also seeing this issue. With approved access, view disappears and shows a black screen. I have done the following:

```
func cropViewController(_ cropViewController: CropViewController, didCropToImage image: UIImage, withRect cropRect: CGRect, angle: Int)
    {
        let status = PHPhotoLibrary.authorizationStatus()
        switch (status)
        {
            case .authorized:
                DispatchQueue.main.async {
                    cropViewController.dismiss(animated: true, completion: nil)
                    self.itemImageView.image = image
                }
                
            case .notDetermined:
                PHPhotoLibrary.requestAuthorization { (granted) in
                    if granted == .authorized
                    {
                        DispatchQueue.main.async {
                          self.itemImageView.image = image
                          cropViewController.dismiss(animated: true, completion: nil)
                        }
                    }
                    else if granted == .denied
                    {
                        self.photoDenied()
                    }
                    else if granted == .restricted
                    {
                        self.photoRestricted()
                    }
                    else
                    {
                        print("Unknown error.")
                    }
                }
                
            case .denied:
                self.photoDenied()
                
            case .restricted:
                self.photoRestricted()
            
            @unknown default:
                print("Unknown error.")
        }
    }
```

**Comment by Pratik-Sodha** [comment]
Same issue facing. After selecting image, only black screen appear.

**Comment by Stijnk008** [comment]
This can be fixed like this 

`let viewController = cropViewController.children.first!
        viewController.modalTransitionStyle = .coverVertical
        viewController.presentingViewController?.dismiss(animated: true, completion: nil)`

**Comment by Pratik-Sodha** [comment]
@Stijnk008 Thank you. It's working fine.

Changes require to update in repo.

**Comment by madhavajay** [comment]
@Stijnk008 You sir are an absolute legend! You just saved me hours before a Live Demo Day. *phew*!

**Comment by JustinGanzer** [comment]
Still experiencing this issue in the most recent official 13.1.2 release. The solution of Stijnk008 does still work in this case.
Does the library need an update?
Could anyone explain as to why the behaviour is this odd with the new ios versions?

**Comment by psyco1095** [comment]
this working for me:

func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
        guard let image = (info[UIImagePickerController.InfoKey.originalImage] as? UIImage) else { return }
        let cropController = CropViewController(croppingStyle: croppingStyle, image: image)
        cropController.delegate = self
        cropController.customAspectRatio = CGSize(width: 1.0,height: 1.2)
        cropController.aspectRatioLockEnabled = true
        cropController.resetAspectRatioEnabled = false
        cropController.modalPresentationStyle = .fullScreen
 
        picker.dismiss(animated: true, completion: {
            let viewController = cropController.children.first!
            viewController.modalTransitionStyle = .coverVertical
            viewController.presentingViewController?.dismiss(animated: true, completion: nil)
// the code below allows you to present the cropController ( for me )
            self.row?.delegate?.present(cropController, animated: true, completion: nil)  
        })
    }

**Comment by TimOliver** [comment]
Hey folks! Um, so I just added `modalPresentationStyle = .fullScreen` to the library in the master branch. This SHOULD hopefully resolve the majority of the weird behaviours the library was exhibiting.

If you're still having this issue, can you please pull from master and see if that's fixed?

In the meantime, I've noticed there's a lot of visual glitching on non-FaceID devices, so I have to prioritise that now.

Thanks!

**Comment by TimOliver** [comment]
Cool. I think this has been resolved. Please open a new issue if anyone else runs into the same issue!
