### ISSUE TITLE
Issue when going back to crop view controller

### ISSUE THREAD

**Issue by khushbooOpenxcell** [TimOliver/TOCropViewController#371]
I crop the Image and take the selected image(highlighted in square box) to the next screen. But, when I hit back and arrive back on crop screen, the image selection square is shifted from the already selected part. 

Here is the code, how i am presenting the cropcontroller

`let cp = CropViewController(image: image)
cp.aspectRatioPreset = .presetSquare
cp.aspectRatioLockDimensionSwapEnabled = true
cp.aspectRatioPickerButtonHidden = true
cp.aspectRatioLockEnabled = true
cp.resetButtonHidden = true
cp.onDidCropToRect = {
            image,rect,a in
let aStoryBoard = StoryboardRefrence.instance(ref: .Main)
let headlineView = aStoryBoard.instantiateViewController(withIdentifier:ViewControllersIdentifiers.headLineViewController) as! HeadLineViewController         self.controller?.navigationController?.pushViewController(headlineView, animated: true)
        }
        self.navigationController?.pushViewController(cp, animated: true)`

**Comment by TimOliver** [comment]
Hi @khushbooOpenxcell!

Sorry, I can't help with that amount of information. I'm not sure what's going on there.

Can you please attach some screenshots?

**Comment by TimOliver** [comment]
Going to close this off as there's nothing I can do to resolve this.

If it's still happening, please create a sample app showing the problem and I can promise to try and take a look.
