### ISSUE TITLE
Cropping Live Photos shows empty UI

### ISSUE THREAD

**Issue by rodmaz** [TimOliver/TOCropViewController#375]
**Describe the bug**
When user picks an photo from album (using `UIImagePickerController`) and the photo is a "Live Photo", the crop UI shows an empty image.

**To Reproduce**
1. Pick an image from album which is a Live Photo
2. Cropping component shows up but shows an empty image.

**Expected behavior**
Component should extract the image from Live Photo and display it correctly.

**Screenshots**

![IMG_1728](https://user-images.githubusercontent.com/55300/65059929-44b60700-d94d-11e9-88b7-a7c5c6d721e6.PNG)

**iOS Device:**
 - Device: iPhone 7 Plus, iPad 4gen
 - OS: iOS 12.4.1, iOS 13.1
 - Library Version: 2.5.1

**Comment by rodmaz** [comment]
Never mind. A quick solution is to avoid Live Photos in UIPicker

Instead of this: 

```
        UIImagePickerController *mediaPickerController = [[UIImagePickerController alloc] init];
        mediaPickerController.mediaTypes = @[(NSString *)kUTTypeImage, (NSString *)kUTTypeLivePhoto];
```

We should only pick images:

```
        UIImagePickerController *mediaPickerController = [[UIImagePickerController alloc] init];
        mediaPickerController.mediaTypes = @[(NSString *)kUTTypeImage];
```

Live photos will still be displayed in the picker but this will make sure the media picked contain only image data.

**Comment by TimOliver** [comment]
Oh wow. That's fascinating to see. Thanks for letting me know @rodmaz!

Yeah, I wonder if we should add the ability to extract images from Live Photos, but that might be out of scope for this library. We'll have to see if it's something a lot of people might want.

Thanks again!
