### ISSUE TITLE
App goes to a blank screen after dismissed or dismissAnimatedFrom. no error info and no clue - Swift

### ISSUE THREAD

**Issue by anuradhss** [TimOliver/TOCropViewController#377]
**Describe the bug**

This happened with new Xcode and iOS updates ( don't know if this is the exact issue). it was working fine. but with the `dismiss` or `dismissAnimatedFrom` called, whole screen turn into a blank black. no any error or nothing.

**To Reproduce**

- To make sure, I created a new project and implemented the `CroppedViewController`, it gives me the same result. here is how I use it. everything woks fine until here.

```
public func updateImageViewWithImage(_ image: UIImage, fromCropViewController cropViewController: CropViewController) {
        imageView.image = image
        layoutImageView()
        
        self.navigationItem.rightBarButtonItem?.isEnabled = true
        
        if cropViewController.croppingStyle != .circular {
            imageView.isHidden = true
            
            cropViewController.dismissAnimatedFrom(self, withCroppedImage: image,
                                                   toView: imageView,
                                                   toFrame: CGRect.zero,
                                                   setup: { self.layoutImageView() },
                                                   completion: {
                                                    self.imageView.isHidden = false })
        }
        else {
            self.imageView.isHidden = false
            cropViewController.dismiss(animated: true, completion: nil)
        }
    }
```

**Expected behavior**
Cropped image should show and `CroppedViewController` should dismiss.

**Screenshots**
Here is a gif to give you a clear idea.

![GitErrGif](https://user-images.githubusercontent.com/45997816/65760384-88bdbe80-e13a-11e9-98a1-32cf1b2e80b8.gif)

**iOS Device:**
 - Device: tested with (iPhone 7+, iPhoneX)
 - OS: all are iOS 13
 - Library Version - latest
 - Language - Swift

**Additional context**
- I tried to just `dismiss` the `CroppedViewController`, but it also didn't success.
- Forked and cloned the project and went through it. seems like issue is with `CropViewController.swift`, not with `TO`
- Finally Thanks for this awesome library.

**Comment by lmr-soltanov** [comment]
@anuradhss 

cropViewController.modalPresentationStyle = .fullScreen

Should fix this issue

**Comment by anuradhss** [comment]
@lmr-soltanov yep, it works and updated at the repo as well. thanks

**Comment by piyushghoghari08** [comment]
Thank you @lmr-soltanov & @anuradhss 
It's working.

**Comment by uchiha-itachi95** [comment]
modalPresentationStyle = .fullScreen is not working for me. Is there any other solution for this problem?
