### ISSUE TITLE
setting the default image size

### ISSUE THREAD

**Issue by AbiramiBala** [TimOliver/TOCropViewController#38]
Can you help me to do the following..
after selecting an image if the done button is pressed without editing the photo, then the image should change to its default size/frame as 16:9 and it should be displayed on the first view controller....

Please help me to do it as soon as possible

**Comment by TimOliver** [comment]
Um.... sorry. I'm a bit confused as to what you're asking.

You want to crop an image to 16:9 even if the user doesn't edit it at all...?

**Comment by AbiramiBala** [comment]
yes....it should be done when the user click done button even if the user doesn't edit it at all...

**Comment by AbiramiBala** [comment]
hi...... im waiting for your reply........

**Comment by TimOliver** [comment]
Hmm, have you tried setting the `defaultAspectRatio` setting? That'll force all images to be clamped to the preset you choose.

I'm happy to hear you're enjoying my library, but I sadly don't have the time to provide specialised support.
