### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by paulocmbraga** [TimOliver/TOCropViewController#380]
Hi,

The Portuguese translation from Portugal is the same as Brazilian Portuguese, but it is necessary to create the directory "pt-br".
Could you include the translation for Portuguese from Brazil?

Thanks!

**Comment by TimOliver** [comment]
Hi @paulocmbraga!

That's a fantastic idea! Thanks for that! I just created a PR and merged it into master. :)

Please give it a test and let me know if that looks good to you!

**Comment by paulocmbraga** [comment]
Perfect Tim!! Thank you!!

**Comment by TimOliver** [comment]
No worries! Thanks for the suggestion! :D
