### ISSUE TITLE
Uploading Circular Image

### ISSUE THREAD

**Issue by jvashisht** [TimOliver/TOCropViewController#381]
I am uploading circular image to Server for my App , but when i try to display that uploaded image the sides are coming white please check the attach image for Clearity.
http://prnt.sc/pjf6m4
Please help me to resolve this issue.
Thanks

**Comment by danhhgl** [comment]
I think you uploaded this image with jpeg extension so the tranparency was converted to white. Let try to upload it as an png type of image.

**Comment by jvashisht** [comment]
Thanks for your reply.
I have uploaded extension as png , but it didn't work.

**Comment by jvashisht** [comment]
Issue is resolved now. Thanks for your Help 👍

**Comment by TimOliver** [comment]
Cool thanks!
