### ISSUE TITLE
Dismissing cropViewController multiple times causes pop to root view controller

### ISSUE THREAD

**Issue by greyorngegrey** [TimOliver/TOCropViewController#388]
**Describe the bug**
I have a view where the user can upload multiple photos. When the user chooses a photo for the first time `cropViewController` displays and once they've selected the area they want to crop the controller dismisses going back to the screen I started at. But when another photo is selected and tries to dismiss `cropViewController` it takes me back to my root view controller.

**Comment by TimOliver** [comment]
Hey @greyorngegrey! Thanks for the reporting the issue!

I can't do anything if I can't reproduce it. Can you tell me a little bit more on how you've structured your app and how you're presenting the controller?

Better yet, a sample app showing the problem would help a lot!

Thanks!
