### ISSUE TITLE
iPhone X and above not supported?

### ISSUE THREAD

**Issue by OkiRules** [TimOliver/TOCropViewController#389]
See image:

![7A1FA00E-8A3B-48E3-B244-5AC68B3AC203](https://user-images.githubusercontent.com/18746541/67541248-007c0a80-f734-11e9-83fc-75e3c9c4c078.png)

**Comment by TimOliver** [comment]
Um. ¯\_(ツ)_/¯

**Comment by TimOliver** [comment]
There's literally nothing I can do with the amount of information you've given me. 

Unless you can give me reproduction steps, please diagnose the problem and file a PR. :)
