### ISSUE TITLE
How can disable the crop view moving

### ISSUE THREAD

**Issue by HTKT** [TimOliver/TOCropViewController#390]
Hello,

May i know how to disable the cropview moving, i would like to fixed the crop view, user will NOT move it, only zoom in/out and rotate the image then crop?

Thanks for your help.

**Comment by TimOliver** [comment]
Hi @HTKT. Um, I don't think there's any way to do that by default. You'll need to add that functionality yourself.

Sorry I couldn't have better information!

**Comment by TimOliver** [comment]
Closing this off now. If this is a feature a lot of people might like, it might be worth exploring making a PR for it.

Thanks!

**Comment by meiqi1992** [comment]
@HTKT resolved it? need this feature

**Comment by thangpq-ahiho** [comment]
anyone have solved it? it's exactly good feature!
