### ISSUE TITLE
Portrait Photo taken from IPhone appears as Landscape i.e rotated to the left by 90deg

### ISSUE THREAD

**Issue by mbullock976** [TimOliver/TOCropViewController#398]
**Describe the bug**
When I take a photo while holding my Iphone in the Portrait position, the photo taken appears in landscape i.e the photo appears rotated to the left by 90 degrees and I have to manually rotate.

**To Reproduce**
1. Hold Iphone in portrait
2. Take photo 
3. Photo appears in landscape mode rotated to right 90deg

**Expected behavior**
Photo taken in Portrait to appear in Portrait in the Crop viewer

**Screenshots**
Photo taken using the device camera to appear in portrait mode, when holding the device in portait
![image](https://user-images.githubusercontent.com/23292121/71289630-78963380-2365-11ea-94d0-cf09350b0930.png)

**iOS Device:**
 - Iphone 7 and Iphone x
 - OS 13.2.2
 - Library Version 2.5.2

Code below. I have a extension method to fix the rotation below, but I'd rather not have to use that as it's more of a workaround to an issue

[assembly: ExportRenderer(typeof(CropView), typeof(CropViewRenderer))]

    public class CropViewRenderer : PageRenderer
    {
        private CropViewDelegate _selector;
        private Stream _image;
        private bool _isShown;
        private Action<byte[]> _callback;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var page = (CropView)Element;
            _image = page.OriginalImage;
            _callback = page.NavigationCallback;
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            try
            {
                if (!_isShown)
                {

                    _isShown = true;

                    var image = new UIImage(NSData.FromStream(_image));
                    //var img = image.FixRotate();
                    _image = null;

                    _selector = new CropViewDelegate(this, _callback);
                    var picker = new TOCropViewController(image)
                    {
                        Delegate = _selector
                    };

                    PresentViewController(picker, false, null);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }
    }

    public class CropViewDelegate : TOCropViewControllerDelegate
    {
        private readonly UIViewController _parent;
        private readonly Action<byte[]> _callback;

        public CropViewDelegate(UIViewController parent, Action<byte[]> callback)
        {
            _parent = parent;
            _callback = callback;
        }

        public override void DidCropToImage(TOCropViewController cropViewController, UIImage image, CoreGraphics.CGRect cropRect, nint angle)
        {
            try
            {
                if (image != null)
                {
                    var bytes = image.AsJPEG().ToArray();
                    _callback(bytes);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
            finally
            {
                image?.Dispose();
            }

            _parent.DismissViewController(true, async () =>
            {
                await Xamarin.Forms.Application.Current.MainPage.Navigation.PopAsync().ConfigureAwait(true);
            });
        }

        public override void DidFinishCancelled(TOCropViewController cropViewController, bool cancelled)
        {
            _parent.DismissViewController(true, async () =>
            {
                await Xamarin.Forms.Application.Current.MainPage.Navigation.PopAsync().ConfigureAwait(true);
            });
        }
    }

    public static class UiImageHelper
    {
        public static UIImage FixRotate(this UIImage image)
        {
            return new UIImage(image.CGImage, 1.0f, UIImageOrientation.Right);
        }
    }

**Comment by TimOliver** [comment]
Thanks for the thorough report @mbullock976!

Hmm, I just tried it on my iPhone (Take photo with Camera app, open in the sample app), and the rotations were fine.

How are you taking the photos exactly? I've seen images been presented sideways on iOS because the `UIImage` code didn't take the rotation metadata into account before. Hopefully that's not the case here.

Maybe take a look here, and see if you can use those APIs to create a new `UIImage` with the image with the rotation adjusted.

https://stackoverflow.com/questions/31420356/saving-thumbnail-of-uiimage-flips-the-image-sideways-upside-down

Hope that helps!

**Comment by mbullock976** [comment]
Hi @TimOliver 
Sorry I forgot to update this post. There is nothing wrong with your ToViewController

It was a problem with another Api I was using

You can Close this issue

Thanks

**Comment by TimOliver** [comment]
Cool! Thanks!
