### ISSUE TITLE
Free angle rotation

### ISSUE THREAD

**Issue by kronik** [TimOliver/TOCropViewController#40]
Do you plan to add free angle rotation support similar to embedded gallery app?

**Comment by TimOliver** [comment]
I would love to have that feature! But sadly, in retrospect, I think I that architectural design I went with for this version of the controller makes that impossible.

This controller handles the cropping region by overlaying a second copy of the image on top of the dimming view, that's clipped to the size of the cropping box. I'm pretty sure the Apple one just does it the traditional way, with 4 separate copies of the dimming view creating a 'hole' over a single instance of the image.

If that's the case, then I'd need to pretty much re-do the whole lot from scratch to implement fine-grain rotations.

It's something I'd definitely be interested in trying out for a potential version 2.0, but I don't have any time/plans to do that any time soon.

If you want to give it a try yourself using parts from this view controller, you've got my full support. :)
