### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by anmolrajpal** [TimOliver/TOCropViewController#403]
**Add support for Swift Package Manager**

It will be helpful especially for developers who do not want to use xcworkspace file. Also, if possible, a working example of SwiftUI project

**Comment by TimOliver** [comment]
Hi @anmolrajpal!

We're already tracking that here: https://github.com/TimOliver/TOCropViewController/issues/359. Any help would be appreciated.

Thanks!

-Tim
