### ISSUE TITLE
Support for Transparent images

### ISSUE THREAD

**Issue by sur950** [TimOliver/TOCropViewController#404]
Hi,

My image is transparent black logo and crop tool is adding black colour as default in background and after cropping, I see complete black screen and I would be very happy if you can add support for transparent images.

Thank you.

**Comment by TimOliver** [comment]
Hi @sur950!

I just tested to double-check. The cropper does in fact support transparent images. As long as the image provided contains an alpha channel (ie, it was based off a PNG image, or one with `opaque` explicitly set to false), it has been explicitly built to preserve the transparency information.

In future, please do not delete the issue template; please provide as much information as you can in order I can help better.

If you're still having issues, please open a new issue and provide me with exact steps to reproduce.

Thanks!
