### ISSUE TITLE
How to show Navigation Controller?

### ISSUE THREAD

**Issue by UlanNurmatov** [TimOliver/TOCropViewController#412]
I'm pushing CropViewController to a NavigationController stack and trying to show the Navbar with .hidesNavigationBar = false, but it doesn't work. How do I do it properly? 

  ```
        let cropViewController = CropViewController(croppingStyle: .default, image: image)
        cropViewController.delegate = self
       cropViewController.hidesNavigationBar = false
       self.navigationController?.pushViewController(cropViewController, animated: true)
```

**Comment by TimOliver** [comment]
Hi @UlanNurmatov!

Hmm, I just tested it in the sample app (There's an example of pushing it to a navigation controller here: https://github.com/TimOliver/TOCropViewController/blob/9630fa47af1083650aed265f28fbcab43436d2d8/Swift/CropViewControllerExample/ViewController.swift#L69) and it worked fine.

Could you please provide some more info on how your app is set up?

**Comment by UlanNurmatov** [comment]
@TimOliver I'm sorry, there was a mistake in my code. 
`.hidesNavigationBar` works as it should.
