### ISSUE TITLE
How to rotate the picture at any angle?

### ISSUE THREAD

**Issue by DeTong** [TimOliver/TOCropViewController#414]
**What are you trying to achieve with this library exactly? Please describe.**
Hi~
First , this library is really good.

I want the image to rotate at any angle, such as 12 or 77.

How to do?

:)

**Comment by TimOliver** [comment]
Thanks @DeTong! Glad you like the library! :)

You can't. Sorry. It's unsupported. It was discussed at the start of this project's life (https://github.com/TimOliver/TOCropViewController/issues/3), but I don't have the spare time to devote to something like that.

If you feel up to the task, feel free to file a PR. :)

At some point, I'm considering doing a modern rewrite in Swift. If I do, I'll make sure that's a launch feature.

Sorry I couldn't help more!

**Comment by DeTong** [comment]
Hmm...
good idea!
(๑˙~˙๑)
