### ISSUE TITLE
Missing button in Catalyst

### ISSUE THREAD

**Issue by randymortensen** [TimOliver/TOCropViewController#439]
**Describe the bug**
The "accept" button is missing in the crop view when running the TOCropViewControllerExample as a catalyst macOS app.

**To Reproduce**
1. Checkout latest code
2. Open project in Xcode, assign "team" to all targets, check macOS in Deployment Info, build and run
3. Press "+" to a select a photo and select "Crop Image"
4. See missing "accept" button

**Expected behavior**
The "accept" button is missing from the upper left corner. All other buttons work as expected. 

**Screenshots**
![Screen Shot 2020-10-27 at 1 56 47 PM](https://user-images.githubusercontent.com/32440094/97356340-bd300c80-185d-11eb-9b4d-02f3ab322b6b.png)

**iOS Device:**
 - MacBook Pro (Retina, 13-inch, Early 2015)
 - macOS Catalina 10.15.7
 - Library Version 2.5.5

**Additional context**

**Comment by masaldana2** [comment]
fix: replace line 245 on TOCropToolbar.m
to        frame.size.height = 100.0f;

**Comment by randymortensen** [comment]
Awesome, that works! Thanks for the fix. 

I just noticed that the upper left and right "resize handles" are obscured (by the window title). Is it better to open a new issue for that or continue in this one?

**Comment by TimOliver** [comment]
Ahhh. I see. It's being obscure by the toolbar. 😅

Okay no worries! That should be easy enough to solve by adding a check for the Mac Catalyst environment, and then insetting the buttons via the safe area inset when it is! I'll do that when I get the chance.

**Comment by TimOliver** [comment]
This should now be addressed by PR #464. I'll close this off now. If you find any other issues, please create a new issue.

Thanks!

**Comment by randymortensen** [comment]
Great! Thanks for the update.
