### ISSUE TITLE
The nullable `doneButtonColor` and `cancelButtonColor` in `objC` causes an error in `Swift`

### ISSUE THREAD

**Issue by michaelhenry** [TimOliver/TOCropViewController#457]
**Describe the bug**
The nullable `doneButtonColor` and `cancelButtonColor` causes an error in `Swift`

**To Reproduce**
1. Just rebuild the project with the current master branch using swift then XCode will complain about `doneButtonColor` and `cancelButtonColor` being as an `optional`

**Expected behavior**
Xcode should build without errors.

**Screenshots**
![Screen Shot 2020-12-17 at 11 01 13 am](https://user-images.githubusercontent.com/717992/102420882-3fb39c00-4057-11eb-9f2d-996c406f9e2e.png)

**iOS Device:**
 - all device 
 
- Xcode 12.2

**Comment by michaelhenry** [comment]
PR -> #458

**Comment by TimOliver** [comment]
Fixed! Thanks for that @michaelhenry!
