### ISSUE TITLE
Cannot find type 'TOCropViewControllerDelegate' in scope

### ISSUE THREAD

**Issue by premkumarsepuri** [TimOliver/TOCropViewController#460]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**iOS Device:** 
 - Device: [e.g. iPhone6]:- iPhone 6s
 - OS: [e.g. iOS8.1] 14.2
 - Library Version [e.g. 22]

**Additional context**

**Comment by premkumarsepuri** [comment]
Cannot find type 'TOCropViewControllerDelegate' in scope.  when tried to import im getting this error in Xcode 12.4

**Comment by TimOliver** [comment]
Sorry @premkumarsepuri. There's not enough information here for me to help.

How did you import it exactly?

**Comment by premkumarsepuri** [comment]
now it is working fine .
