### ISSUE TITLE
Saving the image with circular crop 

### ISSUE THREAD

**Issue by Snow-Tech** [TimOliver/TOCropViewController#474]
Hi, i'm saving the circula crop image in a server, but I want to know, how can I save the image without the circular shape?
It's possible to remove the circular shape?

**Comment by nightbird8n** [comment]
Hi @TimOliver ,
Can I get square image(not circular cropped image) when crop circle(I want to use circle mask to crop, but I want a square cropped image)? Is this possible?

**Comment by luke-riu** [comment]
@Snow-Tech
The image is cropped and masked before being rasterised. Checkout the implementation below to make them square going forward.

@nightbird8n 
I was able to achieve this by using the nice, bundled extensions with their delegate methods.

```swift
 func cropViewController(_ cropViewController: TOCropViewController, didCropImageTo cropRect: CGRect, angle: Int) {
    let squareImg = self.image.croppedImage(withFrame: cropRect, angle: angle, circularClip: false)
  }
```

**Comment by nightbird8n** [comment]
Brilliant answer! Thank you, @luke-riu

**Comment by Snow-Tech** [comment]
> @Snow-Tech
> The image is cropped and masked before being rasterised. Checkout the implementation below to make them square going forward.
> 
> @nightbird8n
> I was able to achieve this by using the nice, bundled extensions with their delegate methods.
> 
> ```swift
>  func cropViewController(_ cropViewController: TOCropViewController, didCropImageTo cropRect: CGRect, angle: Int) {
>     let squareImg = self.image.croppedImage(withFrame: cropRect, angle: angle, circularClip: false)
>   }
> ```

Thank u @luke-riu , but I still have the same issue, I'm using the func cropViewController(_ cropViewController: TOCropViewController, didCropTo image: UIImage, with cropRect: CGRect, angle: Int), but stills show the circular cropped image.

**Comment by Snow-Tech** [comment]
Thank u, @luke-riu.
