### ISSUE TITLE
How to fix the size of the clipping area

### ISSUE THREAD

**Issue by Rookie131** [TimOliver/TOCropViewController#491]
I am using Brightroom and I find that the default crop area can be changed by the user.
I want the cropping area to be fixed in size.
How to achieve it?
<img width="384" alt="image" src="https://user-images.githubusercontent.com/86518519/125229240-eff53480-e308-11eb-9b89-596eb411cf18.png">
Just like the `make profile picture` crop area of your example is fixed
<img width="388" alt="image" src="https://user-images.githubusercontent.com/86518519/125229098-9db41380-e308-11eb-8982-c14a3fd223fd.png">

**Comment by cozzin** [comment]
@Rookie131 Hi, I hope this code helps you.

```swift
cropController.customAspectRatio = CGSize(width: 300, height: 200)
cropController.cropView.cropBoxResizeEnabled = false
```

<img src="https://user-images.githubusercontent.com/11647461/133413805-cce8c5ba-e08a-458b-873c-24eb58a921ff.png" width=300>

**Comment by Rookie131** [comment]
Hi @cozzin 
Thank you for your answer
