### ISSUE TITLE
Wrong link in GitHub-Repository

### ISSUE THREAD

**Issue by chkpnt** [TimOliver/TOCropViewController#496]
That seems to be the correct URL: 
[https://timoliver.blog/2015/06/21/tocropviewcontroller-an-open-source-image-cropper-for-ios](https://timoliver.blog/2015/06/21/tocropviewcontroller-an-open-source-image-cropper-for-ios)

**Comment by TimOliver** [comment]
Hahah thanks @chkpnt! I'm updating my blog to my new domain `tim.dev` now, so I'll update it then. :)
