### ISSUE TITLE
Forcing locked aspect ratio doesn't hide clamp button

### ISSUE THREAD

**Issue by Tramvai** [TimOliver/TOCropViewController#50]
Hi.

Setting 'lockedAspectRatio' to true does not hide the clamp button. Nor does setting 'toolbar.clampButtonHidden' to true hide it.

Is that a bug or expected behaviour?

Version 1.2.1 from CocoaPods, using in a Swift project.

**Comment by trramsiq** [comment]
It is expected!
You also have to call:
*cropViewController.toolbar.clampButtonHidden = true*

but this is broken in version 1.2.1
It will be fixed in the next version.

**Comment by Tramvai** [comment]
Thank you!

I made my own fix by editing the source code and removing the button entirely, as I have no intention of toggling it back on at this moment in time.

Looking forward to the release where it will be fixed.

Cheers. :+1:

**Comment by tristanrichard** [comment]
Just looked in the comments and apparently setting 'lockedAspectRatio' should hide the clamp button... Tim can you confirm that?
