### ISSUE TITLE
[Question] How to change cropping square size

### ISSUE THREAD

**Issue by sugitatestblue** [TimOliver/TOCropViewController#520]
**What are you trying to achieve with this library exactly? Please describe.**

I want to change cropping square size.

I want to set square.

I tried these options. but never work.
```
cropvc.customAspectRatio = CGSize(width: 300, height: 300)
//                cropvc.cropView.frame = CGRect(x: 0, y: 0, width: 300, height: 300)
                
//                cropvc.imageCropFrame = CGRect(x: 0, y: 0, width: 300, height: 300)
//                cropvc.accessibilityFrame = CGRect(x: 0, y: 0, width: 300, height: 300)
```

![change](https://user-images.githubusercontent.com/78467077/165064737-e93e144c-9416-4bfe-96ec-8d5878ec922e.png)

**Comment by sugitatestblue** [comment]
Dragging and change and change ratio.

**Comment by TimOliver** [comment]
Hi @sugitatestblue!

Hmm, what sort of feature are you building where you need the padding to be so big? If you set the aspect ratio to 1:1 and then update the padding values, maybe that will give you the effect you want here.

**Comment by TimOliver** [comment]
Closing this out now. I feel like the best thing that can be done here is to file a PR to make the insetting of the crop box controllable externally. Thanks!
