### ISSUE TITLE
Xcode 14 built error

### ISSUE THREAD

**Issue by ygf-git** [TimOliver/TOCropViewController#533]
"TOCropViewController-TOCropViewControllerBundle" requires a development team. Select a development team in the Signing & Capabilities editor.

**Comment by iworkcloud** [comment]
+1

**Comment by sabiland** [comment]
Hm I didn't have any issues building with Xcode 14.

**Comment by orzzp** [comment]
+1

**Comment by simonemarra** [comment]
I'm having the same issue when using the flutter package https://github.com/hnvn/flutter_image_cropper that uses TOCropViewController as iOS component.

Is there any suggestion?

**Comment by orzzp** [comment]
I have solved this problem temporarily with the following, but I am not sure if it will cause new problems yet.

`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end
`

**Comment by befirst** [comment]
I just chose a team inside the Signing&Capabilities -> Targets -> TOCropViewController-TOCropViewControllerBundle and it works perfectly

**Comment by befirst** [comment]
https://stackoverflow.com/questions/39945377/no-code-signature-found-after-pod-installed-in-xcode-8/39949186#39949186

the best solution if you have some CI/CD:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
       end
    end
  end
  ```

**Comment by simonemarra** [comment]
> I just chose a team inside the Signing&Capabilities -> Targets -> TOCropViewController-TOCropViewControllerBundle and it works perfectly

...Oh dear! If a debug message says Exactly what is missing, then give to the IDE it what it needs. Clean and simple!

I was blocked by my mind: "WTF, why you need my team signature if the package is signed by another developer?"

And the answer sometimes is "just try it and don't mind, you freaky-nerdy-guy!! What do you have to loose?!"

Really thank you dude!

**Comment by yuanzhiying** [comment]
+1

**Comment by gslender** [comment]
After 3.3.2 upgrade I had issues building locally but the above PODS workaround fixed it for me. Not really sure why !?

**Comment by acabreragnz** [comment]
+1

**Comment by jordanliu** [comment]
+1

**Comment by JPGuptaJee** [comment]
> https://stackoverflow.com/questions/39945377/no-code-signature-found-after-pod-installed-in-xcode-8/39949186#39949186
> 
> the best solution if you have some CI/CD:
> 
> ```
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
>         config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
>         config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
>        end
>     end
>   end
> ```

I was facing same issue and this solution worked for me perfectly Thank @befirst
