### ISSUE TITLE
how to change color of title

### ISSUE THREAD

**Issue by wkb1192** [TimOliver/TOCropViewController#535]
in SwiftUI

func makeUIViewController(context: Context) -> some UIViewController {
        let img = self.image ?? UIImage()
        let cropViewController = CropViewController(image: img)
        cropViewController.delegate = context.coordinator
        cropViewController.resetButtonHidden = true
        cropViewController.aspectRatioPreset = .presetSquare
        cropViewController.aspectRatioPickerButtonHidden = true
        cropViewController.rotateButtonsHidden = true
        cropViewController.cancelButtonTitle = "cancel!!!"
        cropViewController.doneButtonTitle = "done!!!"
        cropViewController.aspectRatioLockEnabled = true
        return cropViewController
}

I want to change color of 【cancelButtonTitle】&【doneButtonTitle】.
Please teach me!

**Comment by woxtu** [comment]
How about using `doneButtonColor` and `cancelButtonColor`?

**Comment by TimOliver** [comment]
I think @woxtu nailed it here. :)
