### ISSUE TITLE
ToCropViewController not working

### ISSUE THREAD

**Issue by margiPalanBVI** [TimOliver/TOCropViewController#547]
Helllo, 

in my project there is one extension for share, in which I want to use TOCropViewControllerso I have selected share extension target but ot doesn't work, can you guide me how can I use this TOCropViewController into Share Extention

**Comment by TimOliver** [comment]
Hi @margiPalanBVI! I can't really provide specialised support like that. Sorry!

Share Extensions are just your own provided view controller, so as long as you import the library correctly, it should just work.

I just updated the library to work a bit more reliably in SPM and Carthage. Please try again and if it still fails, please open a new issue with a sample app to show us what you're trying to do. Thanks!
