### ISSUE TITLE
PackageIndex.findPackages failed: featureDisabled

### ISSUE THREAD

**Issue by AnatoliyOstapenko** [TimOliver/TOCropViewController#551]
**What are you trying to achieve with this library exactly? Please describe.**
First of all, thanks for the framework. It's really helpful.
But I got a yellow error after adding the framework through the Swift package manager:
"PackageIndex.findPackages failed: Function disabled"
Could you please let me know how I can avoid the error?

**Comment by AnatoliyOstapenko** [comment]
UPD: I found how to resolve issue, I had to just clean all issues of product.
Thanks again)

**Comment by TimOliver** [comment]
Good to hear you fixed it @AnatoliyOstapenko! :)
