### ISSUE TITLE
How to integrate this into my ios sdk

### ISSUE THREAD

**Issue by tunglong007** [TimOliver/TOCropViewController#561]
I am trying to import the library into my custom iOS sdk in Swift. How can I achieve this?

**Comment by TimOliver** [comment]
Hi @tunglong007. It depends how you're distributing your SDK. You can potentially make your SDK define this library as a dependency in CocoaPods and SPM, and just require users also clone it with Carthage.

Short of that, you can just copy the source files to your own SDK.

Hope that helps!
