### ISSUE TITLE
Inquiry about Support for Apple's Privacy Manifest Files #2308

### ISSUE THREAD

**Issue by ferencIOS** [TimOliver/TOCropViewController#565]
Hello,

I hope this message finds you well. I'm reaching out to inquire about the project's current or planned support for Apple's Privacy Manifest Files as outlined in the [Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

Given the increasing importance of privacy and the requirements set by Apple for apps running on its ecosystem, it's essential for projects integrating or porting code to iOS to comply with these privacy guidelines. This includes the specification of privacy practices through manifest files.

Could you please provide information on whether there are any plans to incorporate features or tools within TOCropViewController that would aid in the generation or management of these privacy manifest files? Understanding your roadmap in this regard would greatly assist developers in planning their development and compliance strategies.

Thank you for your time and for all the work you put into maintaining [TOCropViewController](https://github.com/TimOliver/TOCropViewController). I look forward to your response.

**Comment by mammaiap** [comment]
when will be the next release with "Privacy Manifest" support?

**Comment by TimOliver** [comment]
Hi @ferencIOS! Thanks for the incredibly professional issue!

Admittedly I've had some confusion about what is actually required for Apple's new privacy manifest. `TOCropViewController` is a full UI component that doesn't collect any user information at all, so I was confused as to whether the manifest is even necessary.

In looking at other libraries, it looks like it's still necessary to provide an empty manifest file, just so the intent is clear.

I just cut a new release yesterday that includes a privacy manifest now, so we should be good to go. Please feel free to open another issue if you find any issues with it.

Thanks!
