### ISSUE TITLE
Privacy Manifest - Missing an expected key: 'NSPrivacyCollectedDataType'

### ISSUE THREAD

**Issue by p-nicolaou** [TimOliver/TOCropViewController#575]
**Describe the bug**
When generating the Privacy Report for my app, the report displays an error for CropViewController,
**Missing an expected key: 'NSPrivacyCollectedDataType'**

**To Reproduce**
1. Having CropViewController as a dependancy
2. Archive the app
3. From organiser, right-click your archive, 'Generate Privacy Report'
4. In the generated PDF, you can find it under, "Errors Encountered"

**Expected behavior**
There should be no errors

**Screenshots**
<img width="1104" alt="Screenshot 2024-04-11 at 17 07 00" src="https://github.com/TimOliver/TOCropViewController/assets/17762810/3a9bdff2-e3e1-4d36-b3cf-0460c4d6c3b7">

**Additional context**
I believe is down to the fact that `NSPrivacyCollectedDataTypes` is missing a "nutrition label" as described here,
[Apple](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests
)

**Comment by p-nicolaou** [comment]
See pull request #576

**Comment by LFMAKER** [comment]
@TimOliver

**Comment by dubuladuo** [comment]
Put a tag on it

**Comment by TimOliver** [comment]
PR's been merged! Thanks @p-nicolaou!
