### ISSUE TITLE
ITMS-91108: Invalid privacy manifest

### ISSUE THREAD

**Issue by ukcasso** [TimOliver/TOCropViewController#592]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when submitting an app update to the Apple App Store and receiving a rejection due to an invalid privacy manifest file. Specifically, the issue occurred with the PrivacyInfo.xcprivacy file located at TOCropViewControllerBundle.bundle/PrivacyInfo.xcprivacy. The error message received was: "ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: TOCropViewControllerBundle.bundle/PrivacyInfo.xcprivacy." This issue is particularly frustrating as it prevents the app from passing the submission process and creates delays in release schedules.

### Describe the solution you'd like
I would like the PrivacyInfo.xcprivacy file within the TOCropViewControllerBundle.bundle to be properly formatted and compliant with Apple's requirements. Specifically, the file should include valid content with correctly formatted keys and values according to the guidelines provided by Apple. This would allow the app to pass the submission process smoothly without any privacy manifest-related rejections.

### Describe alternatives you've considered
As an alternative, I have considered manually editing the PrivacyInfo.xcprivacy file to ensure that all required keys and values are included and correctly formatted. However, this approach is not ideal because it requires deep technical knowledge and could lead to errors or oversights. Another alternative could be using a different image cropping library that does not have this issue, but this would involve significant refactoring of the existing codebase.

### Additional context
This issue was highlighted by Apple in their documentation, which outlines the need for valid privacy manifests starting November 12, 2024. More details can be found in the official Apple documentation:

[Privacy Manifest Files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)
[Adding a Privacy Manifest to Your App or Third-Party SDK](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk)
Ensuring that all third-party libraries are compliant with these guidelines is crucial for smooth app submission and release.

**Comment by ukcasso** [comment]
Is it related to that PR?
https://github.com/ivpusic/react-native-image-crop-picker/pull/2045

I'm using `react-native-image-crop-picker 0.39.0`
I'll upload the latest version

**Comment by fred-bowker** [comment]
I think this has been fixed in https://github.com/TimOliver/TOCropViewController/commit/bd7287753b04cd07252a3fdfc6ab6eca6059452e

**Comment by ukcasso** [comment]
It has been confirmed that this has been resolved in version 2.7.4. I will close the Issue.

Thanks. @fred-bowker
