### ISSUE TITLE
Problem with localization while installing TOCropViewController with cocoapods

### ISSUE THREAD

**Issue by Sander-Kornev** [TimOliver/TOCropViewController#61]
Currently I am adding Arabic localization and faced with the problem, that UI elements aren't translating to different language.

![9c17c4e4-cff5-11e5-97cd-9989f4a5ef93](https://cloud.githubusercontent.com/assets/3295273/12984556/f97eea7a-d0f6-11e5-9f6a-70b29aa557ab.png)

screenshot was made on iPod touch with iOS 9.2.1, current language is Arabic, status bar is flipped and title of navigation bar is localized, but buttons on TOCropToolbar aren't localized.

This issue might be connected to one, that has been closed https://github.com/TimOliver/TOCropViewController/issues/30 .
In your screenshot in that issue did you launch your project with cocoa pods or from the example in your repository?
Because if I launch project from your example localization works as expected

p.s. And by the way, thanks a lot for the library.

**Comment by hoseokchoi** [comment]
I'm experiencing the same problem. Not only strings in `TOCropToolbar`, all strings in the library are not localized. The codes preparing localized strings try to retrieve them from `[NSBundle bundleForClass:[self class]]`, but I think the localized strings are stored in separate bundle from the classes named `TOCropViewControllerBundle` as you can check in the image below.

![pod-targets](https://cloud.githubusercontent.com/assets/9958196/13039190/4b1bc192-d3df-11e5-8efb-7556362fd63f.png)
