### ISSUE TITLE
cropView.setAspectLockEnabledWithAspectRatio not working

### ISSUE THREAD

**Issue by Minitour** [TimOliver/TOCropViewController#65]
Hi, I am developing an app using Swift 2.0 in which I need to take a photo and then crop a part with an aspect ration of 4:1 (a really wide image).
However I was unable to successfully build up the Crop controller and I am not really sure why is that.
No matter what I try I always get the same error output.

I would really appreciate if you can tell me how to set the default crop view to start at a ratio of 4:1.
Thanks :)

### My code:
```
func imagePickerController(picker: UIImagePickerController, didFinishPickingImage image: UIImage, editingInfo: [String : AnyObject]?) {
        //Dismissing the imagePicker
        imagePicker.dismissViewControllerAnimated(false, completion: nil)

        //initializing the TOCropViewController 
        controller = TOCropViewController(image: image)
        controller.delegate = self
        controller.cropView.aspectRatioLocked = true
        controller.aspectRatioLocked = true
        animated: false)
        controller.rotateButtonsHidden = true
        controller.editing = true

        //Here is where I get the error
        controller.cropView.setAspectLockEnabledWithAspectRatio(CGSizeMake(4, 1), animated: false)
        presentViewController(controller, animated: false, completion: nil)    
    }
```

### Console output:
`*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer bounds contains NaN: [nan nan; 375 667]'
*** First throw call stack:
(0x1823c1900 0x181a2ff80 0x1823c1848 0x184ab4b58 0x184ab49f8 0x187103da8 0x187112074 0x1870d22bc 0x1004ac448 0x1004ac0f8 0x1004ad040 0x1004ace40 0x100082214 0x1000827b0 0x187563570 0x18cb04fa8 0x18cb48cb8 0x18cb48b10 0x1870ebe50 0x1870ebdcc 0x1870d3a88 0x1870eb6e4 0x1870eb314 0x1870e3e30 0x1870b44cc 0x1870b2794 0x182378efc 0x182378990 0x182376690 0x1822a5680 0x1837b4088 0x18711cd90 0x10008568c 0x181e468b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by TimOliver** [comment]
Hi Tony!

That's probably happening because you're trying to set the aspect ratio
before the view has been set up.

If you move that line to under the 'presentViewController' line, it SHOULD
hopefully work. :)

**Comment by Minitour** [comment]
Hi Tim, thanks for the quick reply!

The following suggestion didn't work and result in the same error:
```
presentViewController(controller, animated: false, completion: nil)
self.controller.cropView.setAspectLockEnabledWithAspectRatio(CGSizeMake(4, 1), animated: false)
```


However, This code did work and displayed the cropView size as expected:
```
presentViewController(controller, animated: false, completion: {
            self.controller.cropView.setAspectLockEnabledWithAspectRatio(CGSizeMake(4, 1), animated: false)
        })
```

**Comment by TimOliver** [comment]
Good to hear you got it working in the end! :)
