### ISSUE TITLE
please add Vietnamses localization 

### ISSUE THREAD

**Issue by DungntVccorp** [TimOliver/TOCropViewController#69]
"Done" = "Xong";
"Cancel" = "Huỷ";
"Reset" = "Đặt lại";
"Original" = "Gốc";
"Square" = "Vuông";

thank

**Comment by hansemannn** [comment]
Fixed in https://github.com/TimOliver/TOCropViewController/pull/72

**Comment by TimOliver** [comment]
Thanks for the PR! :)
