### ISSUE TITLE
image auto crop like ios question

### ISSUE THREAD

**Issue by YIFanH** [TimOliver/TOCropViewController#73]
Dear Tim Oliver:

     I am one image processer from china and doing image croping as ios, but how to detect the rotate angle for the auto crop, i do some experiments on this quesion,but can not to find a simple rule. I am Looking forward to your reply.

**Comment by TimOliver** [comment]
Hi @YIFanH!

Haha sorry, I have no idea how Apple implemented that auto-crop feature in the Photos app. I'm curious about it too, but I'm not even sure what it's doing to the photo to get that information.

Sorry! :(

**Comment by TimOliver** [comment]
Oh hang on! I spoke too soon!

It's a Core Image filter! Go to the [Core Image Class Reference Page](https://developer.apple.com/library/ios/documentation/GraphicsImaging/Reference/QuartzCoreFramework/Classes/CIImage_Class/) and there's a method called `[CIImage 
- autoAdjustmentFiltersWithOptions:]`. One of the options you can pick is `kCIImageAutoAdjustCrop`.

Good luck!

**Comment by YIFanH** [comment]
@TimOliver 
Thanks for your reply, I uesd the lines and vanishing point feature to find the rotate angle, but the results is is different with the ios. I guess the ios only used the lines feature,So i make the  special image which only have some lines,but can not find a simple rules to find angle。
