### ISSUE TITLE
rotateClockwiseButtonHidden does not appear to work

### ISSUE THREAD

**Issue by jtmilne** [TimOliver/TOCropViewController#74]
### Hardware
Simulator iOS 9.0

### Expected Behavior
Something (a new button appearing)

### Actual Behavior
Nothing

### Steps to Reproduce
The toolbar does not change regardless if rotateClockwiseButtonHidden is set to YES or NO. I have tried setting it before presenting the view controller and in the completion handler. Same result - nothing happens.

**Comment by TimOliver** [comment]
Oh! Nicely spotted @jtmilne! I don't know when or how that happened!

I just fixed it and pushed a new release. Let me know if that's fixed it for you! Thanks!

**Comment by jtmilne** [comment]
Good news is that bug is fixed and the clockwise rotation icon is now showing up. Bad news is it seems to have introduced a new bug. Now when you rotate the aspect ratio is lost. I have a locked aspect ratio of square. Before it kept the locked aspect ratio when rotating. Now it loses the aspect ratio and reverts to the original image ratio when the image is rotated.

**Comment by TimOliver** [comment]
Oh blimey. Okay. This library is feeling more like a delicate house of cards with every commit. XD

Alright. I just pushed a new version that should hopefully have fixed that. Let me know how you go!

**Comment by jtmilne** [comment]
Problem solved. Thanks! 👍

**Comment by TimOliver** [comment]
Awesome! Thanks for reporting it to me! :)
