### ISSUE TITLE
how to make circular crop area?

### ISSUE THREAD

**Issue by faceyspacey** [TimOliver/TOCropViewController#75]
I'd like to customize this package to provide a circular overlay rather than a square one. The output result image doesn't necessarily need to produce a circular image--I just need to display to the end user that it's a circle. I plan to take the resulting square and turn it into a circle later on display, but for user experience purposes, they should feel like they are cropping a circle.

**Comment by TimOliver** [comment]
That should be pretty easy! The 'non-dimmed' part of the image is being displayed in a separate view (called the `forgroundContainerView`) so if you just modify the mask/roundedEdges of that view, you should automatically get the effect.

I just tried it and got this. 

![simulator screen shot 17 apr 2016 12 11 59 pm](https://cloud.githubusercontent.com/assets/429119/14585020/f74dac00-0495-11e6-9fb6-1802524edd2b.png)

Sadly the effect breaks the moment the crop region stops being a square, so it would need a bit of tweaking depending on your requirements.

Good luck!

**Comment by faceyspacey** [comment]
awesome thanks man! I only need a square, so I should be good.

**Comment by alibasta** [comment]
Hi guys.

I've added a pull request for this feature:

https://github.com/TimOliver/TOCropViewController/pull/92

**Comment by TimOliver** [comment]
Done! :)

Have a play with it in the new updated example app!
