### ISSUE TITLE
Image without cropping show incorrect

### ISSUE THREAD

**Issue by OrWest** [TimOliver/TOCropViewController#76]
### Hardware
iPhone 5
iOS 9.3.1
TOCropViewController (1.2.9)

### Expected Behavior
When I pick some image and press Done without any cropping I expect to see same image, which i pick earlier.

### Actual Behavior
Now after pressing Done image has some black extra view below. Also image lifts up by black view height. 

### Steps to Reproduce
I have this effect on each image, which i have picked without cropping. But if I do a little crop, black view goes, but lifts up continue.
![screen shot 2016-04-18 at 12 44 00](https://cloud.githubusercontent.com/assets/12881398/14600019/5e2c7a46-0563-11e6-942b-1e7e7a545844.png)
![image](https://cloud.githubusercontent.com/assets/12881398/14600020/5ea3b9b2-0563-11e6-8581-ef9f0fab00a5.png)

**Comment by TimOliver** [comment]
Thanks for that! Can you please upload the original image here for me to test?

**Comment by OrWest** [comment]
Here you are.
![image](https://cloud.githubusercontent.com/assets/12881398/14601488/e5ce148a-056a-11e6-9714-4dcfc18218ea.png)

**Comment by OrWest** [comment]
I think I have found what happened. I has changed logic of transition in my app. I have pushed your controller and after cropping push next controller. I changed it today to presenting and it has fixed all bugs.

**Comment by OrWest** [comment]
Sorry to trouble you. This issue should be closed.

**Comment by TimOliver** [comment]
Haha oh okay! I hadn't even gotten around to trying it yet. Thanks for that!

That being said, is there anything I can do on my end to try and prevent this bug? Or was the problem entirely in your own code?

**Comment by OrWest** [comment]
I think you should write to ReadMe about using your controller only through call presentViewController, not push to navigation to **avoid** bugs.
