### ISSUE TITLE
Once reset cropped image, Unable to crop it again.

### ISSUE THREAD

**Issue by sakshiGoel26** [TimOliver/TOCropViewController#77]
### Expected Behavior

On selecting an image for cropping, if we reset it to original image & again tries to crop it, image should be cropped.

### Actual Behavior

If I reset the image to original state & tries to crop it again, image cannot be cropped.

### Steps to Reproduce

1. Select an image & open it in Crop View.
2. Crop the image.
3. Reset it to original state.
4. Try to crop it again.
5. Image will not be cropped.

**Comment by TimOliver** [comment]
Hi! Thanks for the report.

I'm not sure how to reproduce this problem though. Can you please record a video of the bug (You can use QuickTime Player to record from an iOS device's screen), and post it here?

Thanks!

**Comment by sakshiGoel26** [comment]
Hello,

PFA: Shared Video


[TOCropViewController_ReloadIssue1.zip](https://github.com/TimOliver/TOCropViewController/files/225366/TOCropViewController_ReloadIssue1.zip)

**Comment by TimOliver** [comment]
Thanks for the video! That helped a lot!

Hmm, is aspect clamping on there? I found a bug that would lock the zoom size of the scroll view if clamping was on, and you hit the rest button last week. I've already fixed that one.

Please try downloading the absolute latest version of this library and see if it's fixed for you there. :)

**Comment by sakshiGoel26** [comment]
Yeah Thanks.. It worked. :)

**Comment by TimOliver** [comment]
Awesome! Thanks for that ! :)
