### ISSUE TITLE
Square AspectRatio Issue

### ISSUE THREAD

**Issue by raykle** [TimOliver/TOCropViewController#8]
Hi Tim!

I'm glad to find this crop lib useful for me,  I learn lot's from it and thank you.

While using it, I find two bugs.
I choose the Square AspectRatio after I choose a Pic, then I do nothing just rotate. If the pic is Not a square pic, when the pic rotate to vertical, the 'Square' grid overlay changed to the 'Original' shape again.

The second is also the 'Square' AspectRatio, I choose a vertical pic, Square AspectRatio, then I move the pic to end of the vertical pic, and then rotate, when the pic rotate to a horizontal direction, the foreground Image looks wrong. 

Thanks!
![ios simulator screen shot 2015 7 7 4 03 13](https://cloud.githubusercontent.com/assets/3097366/8541665/799665bc-24c2-11e5-89c6-8b0b504d8244.png)

**Comment by TimOliver** [comment]
Hi Ray!

Thanks a lot! I'm glad you've found this library useful!

Awww, bugger! Yep, I think I just found what you've outlined here. Nicely found.

Alright. I'll have to have a play with it and see if I can resolve these issues. Thanks for the heads-up!
