### ISSUE TITLE
How to free rotate image

### ISSUE THREAD

**Issue by andrea-86** [TimOliver/TOCropViewController#81]
It wuold be nice a free rotation, with UIRotationGestureRecognizer or with a bar(like native iOS photo edit) thet enable image rotation for all degrees. The rotation must rotate only the image inside the canvas and the crop area must be fixed, so if i rotate an image for 45° and then take the crop i get back the cropped area back to his original size(like 3:4) with the rotated image inside. Is this possible? Any suggestion?

**Comment by TimOliver** [comment]
It's not possible. 

I really would like the fine-grained rotation capability like in the iOS 8 Photos app, but it's too complicated. Due to the layer composition of this view controller, I get the feeling it would be necessary to rewrite the whole thing from scratch in order to support it. :(

Sorry.

**Comment by andrea-86** [comment]
No, problem, this is just a great job.



Andrea Nenci

2016-05-06 19:14 GMT+02:00 Tim Oliver <notifications@github.com>:

**Comment by andrea-86** [comment]
I do not know if could do with rewrite everything from scratch because
unfortunately, given my gaps in iOS development, I still have not fully
understood your code and how it manages the two display levels. Hacking
with iphone and with the last few models of Android (Samsung edge S7) I
have an idea on how to handle this. According to me only the bottom-view
layer contains a canvas and the image while the crop layer, when displayed,
is nothing more than a window to the one below. The image is rotated (and
climbing to not let blacks holes in the canvas) and redesigned on the
canvas (the dimensions of the layer and of the canvas remain the same
there).  keeping track of the scale factor and using the dimensions of the
layer of crop proportionate to the size of the image then go to make the
final image crop. Do you think is the right way?
Thanks for the advice and congratulations for the job you've do.



Andrea Nenci

2016-05-09 13:11 GMT+02:00 Andrea Nenci <andrea86.nenci@gmail.com>:
