### ISSUE TITLE
Transition after selecting image from ImagePickerSourceType to next view not smooth. 

### ISSUE THREAD

**Issue by sakshiGoel26** [TimOliver/TOCropViewController#82]
### Hardware
iphone5

### Expected Behavior
Once I select camera or gallery source type from floating button item &  select the image, in "didCropToImage" delegate I am presenting  another view  & that view should be presented immediately .

### Actual Behavior
Once I select camera or gallery source type from floating button item &  select the image, in "didCropToImage" delegate I am presenting  another view with animation property false & before next view is presented my previous view in which toCropView delegate is defined is presented & after 1-2 seconds the next view is  navigated .

### Steps to Reproduce
1. In "didCropToImage" delegate, pass the image to another view controller & present it.
2. Call "showCropViewController:0"/"showCropViewController:1".
3. Select a image.
4. Click on Done.
5. You will see, firstly previous view on which cropView delegate is define is presented & then next view.

**Comment by TimOliver** [comment]
Um. Sorry, I don't quite follow here. Can you please post a video?

Sometimes, depending on how big the image you're cropping is, a delay can't be helped. But it might be possible to refine the cropping logic to defer that sort of heavy operation until it's absolutely necessary.

**Comment by TimOliver** [comment]
Closing this. If you want to follow it up, please re-open and post a video.
