### ISSUE TITLE
The minimum width and height of the crop

### ISSUE THREAD

**Issue by tweaker** [TimOliver/TOCropViewController#84]
Hello,
Please tell me how you can set the minimum width and height of the crop the image?
For example, it could be narrowed to not less than 700x700 pixels

**Comment by TimOliver** [comment]
Hi!

There's already an issue tracking that feature request: https://github.com/TimOliver/TOCropViewController/issues/46

There's no mechanism for it at the moment. I'm considering adding it when I get a moment, but feel free to file a PR if you want! :)
