### ISSUE TITLE
Getting <UIVisualEffectView 0x14f47bf70> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

### ISSUE THREAD

**Issue by farhansyed9** [TimOliver/TOCropViewController#85]
### Hardware
iPhone 6
### Expected Behavior
Smooth transition to next view.
### Actual Behavior
Seems to be a slow lag when pressing done.
### Steps to Reproduce
Pressing Done when finished cropping

**Comment by TimOliver** [comment]
Closing this off since I'm not really sure what this issue it about (The warning message? Or some lag somewhere?)

If you want to re-open it, please upload a video of the issue you're describing. Thanks!

**Comment by farhansyed9** [comment]
There's nothing visually going on that's wrong, just when I press done, it
says that error message on the console.

On Tuesday, May 17, 2016, Tim Oliver <notifications@github.com> wrote:

> Closing this off since I'm not really sure what this issue it about (The
> warning message? Or some lag somewhere?)
>
> If you want to re-open it, please upload a video of the issue you're
> describing. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/TimOliver/TOCropViewController/issues/85#issuecomment-219916893>
>


-- 
Farhan Syed
Founder of BrandSpace
