### ISSUE TITLE
No way to restore the crop or re-adjust.

### ISSUE THREAD

**Issue by irfan4** [TimOliver/TOCropViewController#86]
There's no clear way to provide user a way to re-adjust the cropping with the same image.

**Comment by TimOliver** [comment]
There's a PR in progress now that's aiming to add this sort of functionality. I still need to review it. :)

**Comment by TimOliver** [comment]
Added in the latest update!

The API is `cropController.cropView.initialCroppedImageFrame`. I'm considering exposing it through the `TOCropViewController` class itself, but that's good for now. :)

**Comment by irfan4** [comment]
Thank you, much appreciated. Will be testing tomorrow and post my comments.
