### ISSUE TITLE
Korean strings

### ISSUE THREAD

**Issue by anamba** [TimOliver/TOCropViewController#89]
Here are the strings for Korean (which will allow us to use this component in our project). I considered making a pull request, but I think this way might actually be simpler for both of us.

ko.lproj/TOCropViewControllerLocalizable.strings:
```
"Done" = "완료";
"Cancel" = "취소";
"Reset" = "초기화";
"Original" = "원본";
"Square" = "정방형";
```

Great work, by the way! Works well, super easy.

**Comment by anamba** [comment]
Sorry about that, somehow I managed to miss the fact that there are already strings for Korean. I would still suggest changing "Square" to "정방형" to match what Apple uses.

**Comment by TimOliver** [comment]
Haha thanks for that! I just added it. :)
