### ISSUE TITLE
Last release issue

### ISSUE THREAD

**Issue by BeetLab** [TimOliver/TOCropViewController#91]
iPhone5, ios 9.2

Full-size images ( user not crops, just passes through controller ) have black stripe on the bottom.

**Comment by TimOliver** [comment]
Thanks for the issue! I just tested it myself in the simulator and it looks fine!

![simulator screen shot 27 may 2016 1 42 14 am](https://cloud.githubusercontent.com/assets/429119/15584239/53513a6e-23ac-11e6-8b0f-02465d332c45.png)

Can you please upload the image you're having this problem with for me to test?

**Comment by BeetLab** [comment]
Well, i was presenting it inside navigarion controller and everything worked fine, cause i needed status bar. Does it offense now?

**Comment by BeetLab** [comment]
I just realized that

**Comment by TimOliver** [comment]
I had a really quick play with it to see if I could come up with an acceptable way for it to be pushed onto a navigation controller.

Give the latest version a try. :)
