### ISSUE TITLE
Rotation time how to ensure that the size of gridOverlayView unchanged

### ISSUE THREAD

**Issue by huangxuan518** [TimOliver/TOCropViewController#94]
Rotation time how to ensure that the size of gridOverlayView unchanged

**Comment by TimOliver** [comment]
Um, sorry. What?

Are you asking the same thing as https://github.com/TimOliver/TOCropViewController/issues/51?

**Comment by TimOliver** [comment]
Closing this with the assumption it's the same request as #51! Let me know if otherwise! :)

**Comment by huangxuan518** [comment]
I need no matter how to rotate the picture, gridOverlayView is guaranteed for the horizontal 1:2 ratio, rather than the horizontal 1:2, rotation for the vertical into the 2:1, meaning that only the rotation of the picture, the clip box does not rotate
