### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by KimDarren** [TimOliver/TOCropViewController#95]
So many things are changed since you released this awesome library to Cocoapods.
So I cannot use many features if I install `TOCropViewController` via Cocoapods, for example, I cannot set `statusBarVisible` option in `TOCropToolbar`.

**Comment by TimOliver** [comment]
Haha thanks Kim! I'm glad you like the library!

Yep! That was on purpose. There were still a few bugs and APIs I was changing that I didn't want to commit to CocoaPods just yet.

I just finished setting all of that up, and pushed a new version to CocoaPods. :)

**Comment by KimDarren** [comment]
@TimOliver Thank you for your work, Tim!
