### ISSUE TITLE
Default Aspect Ratio Not Initially Set

### ISSUE THREAD

**Issue by mamaral** [TimOliver/TOCropViewController#96]
### Hardware

iOS Simulator (demo project)

### Expected Behavior

Setting the default aspect ratio and locking it (as shown below) should result in the initial crop rectangle being set to that default aspect ratio.

```
cropController.aspectRatioLocked = YES;
cropController.defaultAspectRatio = TOCropViewControllerAspectRatioSquare;
```

### Actual Behavior

The default aspect ratio as defined is not correctly set *until the undo button is pressed*, likely due to the fact that the method that sets the aspect ratio, `- (void)setAspectRatio:(TOCropViewControllerAspectRatio)aspectRatioSize animated:(BOOL)animated:` is not called until undo is pressed.

### Steps to Reproduce

Uncomment out the demo project code that locks the aspect ratio and sets the default aspect ratio to square, and when you edit an image it is initially a rectangle, not a square.

**Comment by TimOliver** [comment]
Thanks for the PR!

**Comment by mamaral** [comment]
No problem!
